### ISSUE TITLE
[r] Add a `context` accessor

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1011]
Context: R/Python parity work as tracked on #839.

Needs #735 as a prerequisite, in order for there to exist instance-level `context` data for the `context` accessor to access.

**Comment by eddelbuettel** [comment]
Waiting for #1038

**Comment by eddelbuettel** [comment]
@mojaveazure and I discussed this, this seems close in spiriti to all his work on `PlatformConfig`.  Maybe we should consider reassigning and/or discussing?

**Comment by johnkerl** [comment]
Cool with me as long as we're on the same page that #941 and #942 are higher-pri ...

**Comment by johnkerl** [comment]
@pablo-gar @mlin thoughts?

**Comment by eddelbuettel** [comment]
Actually my example above is not complete.  A better / full examples is

```r
> ms <- SOMAMeasurementOpen("/tmp/tiledb/soco")  # as an example to create a SOMA obj, local copy
> cfg <- ms$get_tiledb_config()
> class(cfg)
[1] "SOMATileDBContext" "SOMAContextBase"   "ScalarMap"         "MappingBase"       "R6"               
> ctx <- cfg$get_tiledb_context()
> class(ctx)  
[1] "tiledb_ctx"
attr(,"package")
[1] "tiledb"         
> 
```
