### ISSUE TITLE
[Docs] [Python] Make sure all doc strings for public methods have at least one example

### ISSUE THREAD

**Issue by pablo-gar** [single-cell-data/TileDB-SOMA#1013]
Definition of done:

1. Audit doc strings of all public methods. 
2. Write at least 1 example for those methods that have none

**Comment by maniarathi** [comment]
Below is an audit of the docstrings for public methods. Pretty much all of the examples currently live in the class docstring and not in the method docstring. @pablo-gar is that sufficient for the examples to live there? Also, among the methods that don't have examples, are there any you would prioritize for 1.0? 

**SOMACollection**
- [ ] `add_new_collection`
- [ ] `add_new_dataframe`
- [x] `add_new_dense_ndarray` (example available in class docstring)
- [ ] `add_new_sparse_ndarray`
- [ ] `close`
- [x] `create` (example available in class docstring)
- [ ] `exists`
- [ ] `get`
- [ ] `items`
- [ ] `keys`
- [x] `open` (example available in class docstring)
- [ ] `set`
- [ ] `values`

**SOMADataFrame**
- [ ] `close`
- [x] `create` (example available in class docstring)
- [ ] `exists`
- [ ] `keys`
- [x] `open` (example available in class docstring)
- [x] `read` (example available in class docstring)
- [x] `write` (example available in class docstring)

**SOMADenseNDArray**
- [ ] `close`
- [x] `create` (example available in the class docstring)
- [ ] `exists`
- [x] `open` (example available in the class docstring)
- [x] `read` (example available in the class docstring)
- [x] `reshape` (currently unsupported)
- [x] `write` (example available in the class docstring) 

**SOMASparseNDArray**
- [ ] `close`
- [x] `create` (example available in the class docstring)
- [ ] `exists`
- [x] `open` (example available in the class docstring)
- [x] `read` (example available in the class docstring)
- [x] `reshape` (currently unsupported)
- [x] `write` (example available in the class docstring)

**Comment by maniarathi** [comment]
Assigning to @pablo-gar to check whether any of these docstring examples are required for 1.0.

**Comment by pablo-gar** [comment]
Thanks for providing the detailed audit Arathi! This looks sufficient and a bit beyond sufficiency. I can close this issue and open a new to complete the missing examples post 1.0.

How does that sound?

**Comment by pablo-gar** [comment]
new ticket https://github.com/single-cell-data/TileDB-SOMA/issues/1106
