### ISSUE TITLE
[Docs] [Python] Add tutorial/notebook describing how to perform reads on TileDB-SOMA objects

### ISSUE THREAD

**Issue by pablo-gar** [single-cell-data/TileDB-SOMA#1015]
A tutorial/notebook is written in the doc-site describing how to perform reads on TileDB-SOMA objects:

- How to read a TileDB object
- Brief intro and examples, with emphasis on pyarrow as the in-memory intermediate.

**Comment by johnkerl** [comment]
@ebezzi can we close this issue?
