### ISSUE TITLE
[Docs] [Python] Add tutorial section to doc-site

### ISSUE THREAD

**Issue by pablo-gar** [single-cell-data/TileDB-SOMA#1017]
Add a high-level section "Tutorials" to the the doc-site. It must contain the notebooks from https://github.com/single-cell-data/TileDB-SOMA/tree/main/apis/python/notebooks.

Final version should look like the tutorial section of anndata:

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/29237819/224812207-2515de02-fbc8-41b8-8360-bc68f02a2ef1.png">

**Comment by johnkerl** [comment]
@ebezzi can we close this issue? Or is there more to come?

**Comment by ebezzi** [comment]
We can close it. Thanks John!
