### ISSUE TITLE
[r] Port ephemeral classes from Python to R

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1022]
Split-out from #839.

TBD how much of this, and how, goes over idiomatically to Python once #736 is merged.

In any event #736 is a prerequisite.

**Comment by pablo-gar** [comment]
#736 has been completed, this work can start now.

**Comment by johnkerl** [comment]
✨

**Comment by johnkerl** [comment]
@mlin or @mojaveazure depending on cycles/scheduling
