### ISSUE TITLE
[Bug] [python] numba/numpy requirements conflict with older pip solver

### ISSUE THREAD

**Issue by mlin** [single-cell-data/TileDB-SOMA#1051]
While going through [PyPI release procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/PyPI-packaging-WIP) for 1.0.0rc4, when I tried the suggested sanity test,

```
docker run -e VERSION=1.0.0rc4 --rm -it ubuntu:20.04 bash -ec '
  apt-get -qq update && apt-get install -y python3-pip
  pip3 install tiledbsoma==${VERSION}
  python3 -c "import tiledbsoma; print(tiledbsoma.libtiledbsoma.__file__)"'
```

Note the use of ubuntu 20.04, whose pip would use the [old dependency resolver](https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020). This led to,

```
ERROR: numba 0.56.4 has requirement numpy<1.24,>=1.18, but you'll have numpy 1.24.2 which is incompatible.
...
  File "/usr/local/lib/python3.8/dist-packages/somacore/query/_fast_csr.py", line 5, in <module>
    import numba
  File "/usr/local/lib/python3.8/dist-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/usr/local/lib/python3.8/dist-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/usr/local/lib/python3.8/dist-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```

[Our setup.py requires numpy](https://github.com/single-cell-data/TileDB-SOMA/blob/fe0cc356cd4999986f983702cd8b4a9da69ce230/apis/python/setup.py#L201) with no version constraint, and that's listed before scanpy (which is where we get the numba 0.56.4 transitive requirement). I think the old dependency resolver therefore installs the too-new version of numpy first, and then when it later gets to scanpy & numba, it isn't smart enough to backtrack & install the older, compatible numpy version.

This problem does NOT occur if we change the command to use ubuntu 22.04, whose newer pip figures out to do that.

The easiest solution is probably to move scanpy up to the top of our requirements list. We may also wish to consider adding ubuntu 20.04 to our build matrix (but, dependency caching can still confound discovery of similar issues).

**Comment by johnkerl** [comment]
#1058 is merged
