### ISSUE TITLE
[r] Review TileDB-SOMA for spec compliance

### ISSUE THREAD

**Issue by atolopko-czi** [single-cell-data/TileDB-SOMA#1062]
Review the TileDB-SOMA public *R* language API to ensure compliance with the SOMA [abstract specification](https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md) w.r.t class names, class properties, and method names , and method signatures.

Split off from https://github.com/single-cell-data/TileDB-SOMA/issues/834

See also #1126 

May overlap with notebook/vignette work

**Comment by aaronwolen** [comment]
See excellent write-up by @pablo-gar [here](https://github.com/single-cell-data/TileDB-SOMA/issues/1126).

**Comment by johnkerl** [comment]
Dup of #1241
