### ISSUE TITLE
[Bug] [r] `SOMASparseNDArray$read_sparse_matrix()` and `SOMADenseNDArray$read_dense_matrix()` don't return the appropriate value

### ISSUE THREAD

**Issue by pablo-gar** [single-cell-data/TileDB-SOMA#1068]
**Describe the bug**
`SOMASparseNDArray$read_sparse_matrix()` and `SOMADenseNDArray$read_dense_matrix()` need a proper return in the following lines respectively

https://github.com/single-cell-data/TileDB-SOMA/blob/82ec5384e123d49fe5fce3a826cac5d6bb6eaca8/apis/r/R/SOMASparseNdArray.R#L168

https://github.com/single-cell-data/TileDB-SOMA/blob/82ec5384e123d49fe5fce3a826cac5d6bb6eaca8/apis/r/R/SOMADenseNdArray.R#L165

needs to add a line, either:

```
m
```

or 

```
return(m)
```

**Comment by eddelbuettel** [comment]
@pablo-gar An R function returns the last statement (invisibly).  Witness

```r
> foo <- function() { x <- 42 }
> print(foo())
[1] 42
> 
```

To clarify: Are you requesting `return(m)` on stylistic grounds, or because you fear it is wrong?

**Comment by johnkerl** [comment]
If this is a bug report, let's get a repro in here please; if it's a style issue, let's file a follow-on task (post-1.0) wherein we can discuss whether we want to choose (and implement) a convention wherein we always have explicit `return(...)` statements -- and I see this latter as a post-1.0 discussion topic.

**Comment by pablo-gar** [comment]
Learning more about R. 

I thought it was a bug because nothing was shown when just calling the functions. Turns out the way is written it returns the assignment which is evaluated when the function is called and returned, but when it is returned it does so **invisibly**.

Explaining with code

```r
> foo_a <- function() { x <- 42 }
> foo_b <- function() { x <- 42; x }
> foo_c <- function() { x <- 42; return(x) }
> 
> foo_a()
> foo_b()
[1] 42
> foo_c()
[1] 42
```

In all cases 42 is effectively returned but for `foo_a` it is returned **invisibly**. This led me to think that when I was executing `SOMASparseNDArray$read_sparse_matrix()` nothing was being returned. 

So this problem is of style and consistency. The style for our codebase seem to be to not use `return` statements for returning values (all good), however our returns are inconsistent in that some functions return objects (like `foo_b`) and some others return assignments (like `foo_a`).

I propose we keep these consistent and suggest to always return objects as in `foo_b`. This avoids the original confusion and also keeps the code clearer IMO.

**Comment by eddelbuettel** [comment]
It's how the language is defined.  Invisible is default, but is just concerns the print behaviour:

```r
> thesilenttruth <- function() { val <- 42L }
> theloudertruth <- function() { 42L }
> thesilenttruth()
> print(thesilenttruth())
[1] 42
> theloudertruth()
[1] 42
> 

However, when you assign a value it is all equivalent

```r
> all.equal(thesilenttruth(), theloudertruth())
[1] TRUE
> 
```

**Comment by johnkerl** [comment]
I believe everything is accounted for in #1073 which is open to track this issue.
