### ISSUE TITLE
[r] [Feature request] SOMA from `SingleCellExperiment`

### ISSUE THREAD

**Issue by multimeric** [single-cell-data/TileDB-SOMA#1087]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to create a `SOMA` object from an in-memory `SingleCellExperiment`.

**Describe the solution you'd like**
I'm not sure how the new API works since there are no docs, but using the `TileDB-Inc/tiledbsc` API, I would expect something like `SOMA$from_single_cell_experiment(sce)`.

**Describe alternatives you've considered**
An SCE can be converted to a Seurat assay, and then loaded into SOMA, but I suspect this will not be a lossless conversion, and may lose certain metadata.

**Additional context**
Originally from https://github.com/TileDB-Inc/tiledbsc/issues/95.

**Comment by eddelbuettel** [comment]
Docs are available, see the `apis/r` directory and its [README.md](https://github.com/single-cell-data/TileDB-SOMA/tree/main/apis/r) leading e.g. to [this wiki](https://github.com/single-cell-data/TileDB-SOMA/wiki) page and [tutorial notebook](https://cloud.tiledb.com/notebooks/details/tiledb-genomics-dev/056c72cd-3d8d-4e1e-b5bc-92529b224386/preview).

The `pkgdown` documentation isn't linked (should we fix that, @johnkerl ?) but [available too](https://single-cell-data.github.io/TileDB-SOMA/).

**Comment by multimeric** [comment]
Thanks, I didn't realise there were online docs. Publicising the pkgdown website would be very helpful!

**Comment by johnkerl** [comment]
@multimeric confirmed readthedocs (Python) and pkgdown (R) docs for the `main` branch a.k.a 1.0 are very (very) near going online :)

**Comment by pablo-gar** [comment]
@multimeric the docs are now available at https://single-cell-data.github.io/TileDB-SOMA/

keep in mind that R API is under rapid development towards 1.0 so expect things to break in the meantime.


----- 

I would suggest this request gets addressed as soon as possible and after `from_seurat` and `to_seurat` get implemented.
