### ISSUE TITLE
[docs] [python] Lifecycle tags should exist for all methods

### ISSUE THREAD

**Issue by ebezzi** [single-cell-data/TileDB-SOMA#1088]
Lifecycle tags do not exist on all methods. At least all public methods should consistently have them. Audit all methods and add `Lifecycle: Experimental` on the missing ones.

Doc link: https://tiledbsoma.readthedocs.io/en/latest/python-api.html#module-tiledbsoma

**Comment by johnkerl** [comment]
Done with current audit (until someone adds a new docstring that lacks the iifecycle tag anyway)

https://tiledbsoma.readthedocs.io/en/latest/python-api.html

@ebezzi Please let me know if I've missed anything and we can re-open.
