### ISSUE TITLE
[docs/python] Links missing in docs

### ISSUE THREAD

**Issue by ebezzi** [single-cell-data/TileDB-SOMA#1089]
The docsite should have links to all Python objects, including:
1. Internal objects
2. Objects from `somacore` and `TileDB`
3. Common libraries: scipy, numpy, Arrow

Verify that intersphinx is set up correctly to pick those up, and add explicit `:ref:` when necessary.

**Comment by johnkerl** [comment]
This is complete except for `intersphinx`. Note that the Arrow et al. links _do_ work correctly -- they are working without the assistance of `intersphinx`.

We will be moving our doc infra to Quarto soon (#1055) and `intersphinx` may not survive the move, so I am leaving that bit as unnecessary and soon to be obsoleted.
