### ISSUE TITLE
[docs/python] Complex types are rendered poorly by Sphinx

### ISSUE THREAD

**Issue by ebezzi** [single-cell-data/TileDB-SOMA#1090]
Some types (especially union types) are rendered by Sphinx in a confusing way:

![Image](https://user-images.githubusercontent.com/7020189/224374557-b723b37a-3ab4-42f9-85fc-88207ebce5f7.png)

Find out if they can be simplified. Ideally, the type in question should not be expanded but instead link to its definition.

**Comment by thetorpedodog** [comment]
this is unfortunate and rather unhelpful, but extremely funny

**Comment by johnkerl** [comment]
Support is not live yet:

* https://github.com/sphinx-doc/sphinx/issues/1514
* https://github.com/sphinx-doc/sphinx/pull/11011

It remains to be seen whether this will land in Sphinx before or after we move from Sphinx to Quarto (#1055).

**Comment by johnkerl** [comment]
Given that we can do no more this sprint, I'm untagging this from the current sprint -- but leaving it open until (a) the above Sphinx feature lands, or (b) this issue is obviated by #1055.

**Comment by johnkerl** [comment]
Obviated by #1055
