### ISSUE TITLE
[r] LaTeX errors from `R CMD build .`

### ISSUE THREAD

**Issue by mlin** [single-cell-data/TileDB-SOMA#1102]
As of this writing, when I run `R CMD build .` in `apis/r`, [as suggested in the readme](https://github.com/single-cell-data/TileDB-SOMA/tree/main/apis/r#step-by-step), I get screen-fulls of LaTeX errors. I can sidestep these with `R CMD build --no-build-vignettes --no-manual .` which I note is [what `r-ci.sh` does](https://github.com/single-cell-data/TileDB-SOMA/blob/7af7469bfecec9079096c3f4f7470e57e74902e8/apis/r/tools/r-ci.sh#L38). Assuming we care about the LaTeX documentation (I think CRAN expects it, right?) then we should make sure it's covered by CI as well as fix whatever the immediate problems are.

Here's the first error lines I get fwiw. I've not yet made a serious attempt to look into them.

```
$ R CMD build .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘tiledbsoma’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to process help pages
* building the PDF package manual
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'Rd2.tex' failed.
LaTeX errors:
! Paragraph ended before \Rd@code@wrk was complete.
<to be read again> 
                   \par 
l.77 
     
! LaTeX Error: \begin{list} on input line 62 ended by \end{itemize}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
! Missing } inserted.
<inserted text> 
                }
l.83 \end{itemize}
```

**Comment by eddelbuettel** [comment]
We always build _with latex_ on a full sytem (as for example mine on the machine where I type this) and frequently use faster and lighter setups to expedite continuos integration.  Setting up a full texlive environment is rather expensive and I recommend to _not_ incur the cost on each build.  I simply have not seen enough failures in twenty years package authoring at this very mechanical step to care sufficiently.  Others may of course have very different preferences.

A suitable compromise may be to either add check in a pre-made 'fat' docker image, or to run fuller CI nightly.

**Comment by mlin** [comment]
@eddelbuettel @johnkerl the LaTeX problems I'm hitting with `R CMD build .` are somehow introduced by 7af7469bfecec9079096c3f4f7470e57e74902e8

If I run that command on the immediately-preceding revision b21f68e3bf24eff42dbe27f0aa4fd60aad99bdda, `R CMD build .` succeeds ~instantaneously.

With that commit, it starts an additional step `* installing the package to process help pages` which (i) fails as described above or (ii) still takes significant time (minutes) even with `--no-build-vignettes --no-manual`.

Suggestions?

**Comment by johnkerl** [comment]
👀 
cc @mojaveazure

**Comment by mlin** [comment]
Here's the full listing of my `R CMD build .` output: https://gist.github.com/mlin/51a6a92b75fd656c74f0d4e6d6d53543

This is on an ubuntu 22.10 machine with the `texlive-latex-base texinfo` apt packages

**Comment by eddelbuettel** [comment]
@mlin I am unable to reproduce this with the information provided:

```sh
edd@rob:~/git/tiledb-soma/apis/r(main)$ ./cleanup 
edd@rob:~/git/tiledb-soma/apis/r(main)$ R CMD build --no-manual --no-build-vignettes .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘tiledbsoma’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to process help pages
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘tiledbsoma_0.0.0.9012.tar.gz’

edd@rob:~/git/tiledb-soma/apis/r(main)$ R CMD build --no-manual .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘tiledbsoma’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to process help pages
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘tiledbsoma_0.0.0.9012.tar.gz’

edd@rob:~/git/tiledb-soma/apis/r(main)$ R CMD build .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘tiledbsoma’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to process help pages
* building the PDF package manual
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘tiledbsoma_0.0.0.9012.tar.gz’

edd@rob:~/git/tiledb-soma/apis/r(main)$ 
```

You may also be misdiagnosimh one issue because the 'takes minutes' is when `libtlledsoma.a` gets build as a prerequisite.

**Comment by eddelbuettel** [comment]
`R CMD build` calls a script `build` in R's own `bin/`, it calls `tools:::.build_packages()`. I am sure we can drill down.

In the meantime, can you try with the options `--no-build-vignettes --no-manual` to side-step whatever stops us here?

**Comment by mojaveazure** [comment]
I'm also not able to reproduce the error

**Comment by mlin** [comment]
Yes, I can get around this with `--no-build-vignettes --no-manual`. I'll leave this open to follow up on, at lower priority, to track down whatever seems to be unusual about my setup.

**Comment by eddelbuettel** [comment]
Happy to jump into a one-on-one or maybe try to drill it down in a Dockerfile where we control package after package. It will be something silly.  But until we known it surely is an irritant.

**Comment by eddelbuettel** [comment]
Also, just to be plain, R is 'once again different' when creating pdf as it uses the (old) tool to go from texinfo .texi to dvi to pdf. Make sure you have `texinfo` installed.

**Comment by eddelbuettel** [comment]
FWIW when I check on my laptop, which at the time had full (enough) texlive but not `texi2dvi`, R calmly noticed that

```sh
─  building the PDF package manual (4m 45.9s)       
   Warning in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  :
     texi2dvi script/program not available, using emulation          
─  cleaning src (3.6s)            
─  running ‘cleanup’     
```

(I used `rcmdcheck::rcmdcheck` here as a wrapper from a script [rcc.r](https://github.com/eddelbuettel/littler/blob/master/inst/examples/rcc.r) hence slightly different visuals on the output.)  So maybe this really is a local issue for @mlin. Happy to stand by and probe.)

**Comment by mlin** [comment]
Closing stale issue as I haven't seen this recently (probably because I switched to a new computer in the meantime :)
