### ISSUE TITLE
[python] Investigate TileDB-SOMA python package compatibility against pandas 2.0

### ISSUE THREAD

**Issue by maniarathi** [single-cell-data/TileDB-SOMA#1124]
Investigate TileDB-SOMA Python package's compatibility with pandas [2.0.0RC0](https://pypi.org/project/pandas/2.0.0rc0/) to understand what changes, if any, will be required in order to support pandas 2.0.0. 

To be assigned to behnam pending GitHub -- leaving with @maniarathi for now

cc @nguyenv as pre-heads-up.

May need sync with `pyarrow`'s `to_pandas` etc

**Comment by beroy** [comment]
https://github.com/single-cell-data/TileDB-SOMA/pull/1217

**Comment by beroy** [comment]
The main finding here is using panda 2.0 will not much affect the current TileDB-SOMA code. However, given that the main use case of panda 2.0 in TileDB-SOMA happens through arrow and current build of parrow is not using panda 2.0 it can affect TileDB-SOMA when parrow uses panda 2.0 in the future. One possible next step is to build parrow with panda 2.0 and try that on TileDB-SOMA.
