### ISSUE TITLE
[r] Integrate new `SOMAExperimentOpen` et al. with new platform config

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1151]
As tracked on #1126, the next step after the factory-method work on #1008 and #1009, and the platform-config work on #735, is to connect the two together so that one may pass a platform-config argument to an opener, etc.

As requested by @pablo-gar on #1126.

cc @eddelbuettel @mojaveazure @aaronwolen @mlin.

**Comment by johnkerl** [comment]
@pablo-gar can you double-check the plumbing is correct & close this out, per our most recent meeting?

**Comment by pablo-gar** [comment]
This has been implemented [here](https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/r/R/Factory.R). I can't find the PR but it can be considered done!
