### ISSUE TITLE
[r] improve usability of `SOMAAxisQuery` coords

### ISSUE THREAD

**Issue by mlin** [single-cell-data/TileDB-SOMA#1171]
The following works:

```{r}
expt <- tiledbsoma::SOMAExperimentOpen(
  "s3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/mus_musculus",
  tiledbsoma_ctx = tiledbsoma::SOMATileDBContext$new(c("vfs.s3.region" = "us-west-2"))
)
expt_query <- tiledbsoma::SOMAExperimentAxisQuery$new(
  expt, "RNA",
  obs_query = tiledbsoma::SOMAAxisQuery$new(coords = list(soma_joinid = bit64::as.integer64(0:1000)))
)
print(expt_query$n_obs)
```

But there are a couple pitfalls setting `coords` in the `SOMAAxisQuery`:

1. If we supply `coords = list(soma_joinid = 0:1000)` (without passing through `bit64::as.integer64`) then the query successfully returns 0 rows.
2. If we forget to put the list wrapper, `coords = 0:1000` (with/without bit64) then we get a difficult-to-understand error message `Error in eval(ei, envir) : Expecting a string vector: [type=NULL; required=STRSXP].`  The error message here should be more helpful. (Should we accept a bare vector and interpret it as `soma_joinid`? Perhaps not, because making the developer write out `soma_joinid` serves as a reminder it's zero-based.)

**Comment by eddelbuettel** [comment]
A good milestone that it works.  That said:
- point 1 is something @aaronwolen and I discussed. If and when we have the schema information and int comes in but int64 is needed then we should just upcast seamlessly.
- the list wrapper is a bit of pain too. I presume at least when we only have one dim we can similarly "listify" for the user.  In cases where there are more than dim it is difficult to do without lists.

**Comment by mlin** [comment]
@eddelbuettel thanks for the quick feedback. Re the list wrapper on point 2 -- expanding on my final parenthetical comment -- indeed my first attempt at this query had simply `coords = 1:1000`, trying to use one-based indexing as seems natural in R. But then, being forced to write out `soma_joinid = ` reminded me that the SOMA spec defines that to be zero-based. So there's some small value in requiring the explicit field name. I'm sure the zero vs one-based indexing is going to come up again and lead to a larger discussion / audit. For now I think it suffices to continue erroring out, just with a more-helpful message.

**Comment by mlin** [comment]
@eddelbuettel On the second aspect, I think rejecting it is fine, but the clarity of the error message is currently an issue -- we should give some indication of what to do instead

**Comment by eddelbuettel** [comment]
I am currently noodling around where we (safely) upcast because I very much dislike how you got 0 points when submitting standard integer (which become nonsensic values when not properly treated).

The trouble is that we don't always have the schema info at hand to assert the column is in fact `int64`.

**Comment by eddelbuettel** [comment]
Didn't get very far and this seems fairly deep inside @mojaveazure 's territory so I may have to leave this for him.

**Comment by eddelbuettel** [comment]
I have something that works in all our SOMA cases.  It now descends into a possible `coords` argument, if needed recursively, and "upcasts" any integer arguments it finds from `integer` to `integer64`.

Only problem:  It breaks on unit test on data.frame use where we have a (legitimately) 32 bit int dim column, it too gets upcast and then the result breaks.  In this case we wanted to keep integer32.  :disappointed: 

I got by that with another toggle: so when coming from `SOMADataFrame` we do _not_ enforce this upcast, in other cases (which includes the `SOMAExperimentQuery` we do.   That passes tests.

**Comment by eddelbuettel** [comment]
@mlin I also got the other point -- this now works unnamed.

```r
> library(tiledbsoma)
> uri <- "s3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/mus_musculus"
> ctx <- tiledbsoma::SOMATileDBContext$new(c("vfs.s3.region" = "us-west-2"))
> expt <- tiledbsoma::SOMAExperimentOpen(uri, tiledbsoma_ctx = ctx)
> qry <- tiledbsoma::SOMAAxisQuery$new(coords = 0:1000)
> expt_query <- tiledbsoma::SOMAExperimentAxisQuery$new(expt, "RNA", obs_query = qry)
> print(expt_query$n_obs)
[1] 1001
> 
```

In essence, I had my life easier by specifying an interface contract of what is here `coord` coming in a named list, which got (presumably accidentally) relaxed in another code path.  So we now ensure it is a named list, and all is well.

**Comment by eddelbuettel** [comment]
This has been taken care of in #1209 and can be closed.
