### ISSUE TITLE
[python/r] Establish a basic framework for perf metrics for the core classes

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1181]
## Motivation
We need to be able to identify performance regressions, compare performance against established tools (scanpy, seurat), and know where to focus our future optimization efforts. See e.g. #558, #1135.

## Goal
Produce a set of scripts for Python and R that can run time and memory usage benchmarking against the critical parts of the TileDB-SOMA API. It is reasonable to break this up into separate issues, one per language. These benchmarking scripts will support running repeatable tests on controlled, test input datasets. Test fixtures may either be dynamically generated (deterministically, not randomly) or static files, in which case they must be versioned and associable with a given version of the benchmarking scripts (should not be committed to repo).

All tests should record:
* `tiledbsoma._general_utilities.show_package_versions`
* package/library versions (`pip list` for Python, e.g.)
* Host instance characteristics: CPUs, memory, swap configuration
* TileDB config
* TileDB schemas for SOMA test data
* Timings for API calls (see below)
* PlatformConfig, if specified for API call
* memory usage: peak, final, swap (delta)

## Design Notes
Suggested list of target API classes to measure reads and writes (where applicable) for member methods:
    * `DataFrame`
    * `SparseNDArray`, `SparseNDArrayRead`
    * `DenseNDArray`, `DenseNDArrayRead`
    * `AxisQuery`: across a variety of value_filters (numerous operators) and coords (slices, lists, scalar)
    * `Collection` (less important? not performance-critical)
    * `io.ingest` (to/from methods)

For Python, the https://docs.python.org/3/library/timeit.html may be useful for performing timings.  For memory usage, https://docs.python.org/3/library/tracemalloc.html may be useful, along with https://psutil.readthedocs.io/en/latest/index.html?highlight=resource#memory.
Other potential tools are cProfile (https://www.machinelearningplus.com/python/cprofile-how-to-profile-your-python-code/) and functiontrace (https://functiontrace.com/#installation)

### End-to-End Single Cell performance including network
The performance tool can also include the S3 delay time and based on that, it can recommend partitioning or parallelization of the of the accesses to SOMA data.

### Script vs Decorator
The performance tool should be implemented as an easy to use script or a Decorator surrounding the function to be profiled.

**Comment by johnkerl** [comment]
Removing from the current sprint -- open for the next sprint

**Comment by johnkerl** [comment]
@beroy please update with current status and what you are doing on this with @ebezzi 🙏

**Comment by beroy** [comment]
The early deployment of the profiler used a fixed baseline for all the runs (PRs) but led to some false alarms. In the new design we use the current tag to compare against main (target). Also we perform runs multiple time and use stddev instead of distance only.

**Comment by johnkerl** [comment]
Thanks @beroy ! :)

**Comment by johnkerl** [comment]
Off the current sprint at present
