### ISSUE TITLE
[r] Port `TileDBCreateOptions` from Python to R

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1183]
Parent task: #1126

**Comment by johnkerl** [comment]
@eddelbuettel -- after mid-sprint time-allocation check-in with @mojaveazure -- do you think you could take this issue for the current sprint?

**Comment by johnkerl** [comment]
@eddelbuettel I have cycles; never mind.

**Comment by eddelbuettel** [comment]
I looked at it yesterday but the Python code is a little hard to read for me, and this was the first time I heard about this so it may be in better hands with you.
