### ISSUE TITLE
AttributeError: module 'tiledbsoma' has no attribute 'SOMACollection'

### ISSUE THREAD

**Issue by ankitbioinfo** [single-cell-data/TileDB-SOMA#1185]
I have recently started to look at nanostring CoxMx data, where the following codes are mentioned to load the data via python. 

```
import tiledb
import tiledbsoma
from anndata import AnnData
import scanpy as sc
 
tiledbURI = "LiverDataRelease/"
 
# set up s3 environment
config = tiledb.Config()
# config.update({"vfs.s3.region" : r.s3Region})
ctx = tiledb.Ctx(config)
 
# read in SOMACollection
pySoma = tiledbsoma.SOMACollection(tiledbURI, ctx=ctx)
pySoma.keys()
```
 
When I run the following piece of code on my machine, it gives me the following error. 
`AttributeError: module 'tiledbsoma' has no attribute 'SOMACollection'`
 
I am not sure, I have the correct version of tiledb and tiledbsoma in my machine. Can anyone help me figure out the right version or this error? 

Version in my machine 
>>> tiledbsoma.show_package_versions()
tiledbsoma.__version__        1.1.1.post32.dev99264483
TileDB-Py tiledb.version()    (0, 21, 1)
TileDB core version           2.15.0
libtiledbsoma version()       libtiledbsoma=5eaa7e3;libtiledb=2.15.0
python version                3.9.5.final.0
OS version                    Darwin 20.4.0

>>> tiledb.version
VersionHelper(version='0.21.1', version_tuple=(0, 21, 1))
 
Thanks.

**Comment by Shelnutt2** [comment]
Hello @ankitbioinfo and thank you for reaching out! The issue you are facing is related to your code snippet needing to be run on the previous version of the SOMA project, `0.1`. You can install this from pip with `pip install tiledbsoma==0.1.22`.

Was your data generated directly from the CosMx in the TileDB-SOMA form or are you converting from a h5ad file or seurat object? We have worked closely with nanostring over this past year on integrating TileDB, but as of now they are still on the previous version, `0.1`, for data generation. If you were converting the data yourself we'd be happy to provide examples of how to use the latest 1.0 API.

I'd also like to note that starting with 1.0 we've introduced backwards compatibility guarantees for both the data the APIs, so this will not be an issue going forward with this project.

We'd love to get on a call to discuss more about the differences the new `1.0` APIs and help you optimize your use of TileDB-SOMA. Please feel to reach out to me at `seth@tiledb.com` and we can get a call scheduled.`

**Comment by ankitbioinfo** [comment]
@Shelnutt2 Many thanks for prompt reply. Currently I am exploring the publicaly available CosMx data what they have it in their website. So the current data in tile_db format which I need to first extract with TileDB-SOMA package and then I can work with h5ad file. So your suggestion to downgrade the tiledbsoma works. Now I converted the data into h5ad format. 
If I need more information about the TileDB-SOMA then sure I will contact you. Thank for your help.

**Comment by lzyent** [comment]
@Shelnutt2 Hi, I tried to follow your code to import the liver dataset, but it showed an error 
`[14](file:///bigdata/zlin/CosMx/loading.py?line=13) # read in SOMACollection
     [15](file:///bigdata/zlin/CosMx/loading.py?line=14) pySoma = tiledbsoma.SOMACollection(tiledbURI, ctx=ctx)
---> [16](file:///bigdata/zlin/CosMx/loading.py?line=15) pySoma.keys()

File [~/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/soma_collection.py:133](https://vscode-remote+ssh-002dremote-002b132-002e68-002e111-002e84.vscode-resource.vscode-cdn.net//~/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/soma_collection.py:133), in SOMACollection.keys(self)
    [129](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/soma_collection.py?line=128) def keys(self) -> Sequence[str]:
    [130](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/soma_collection.py?line=129)     """
    [131](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/soma_collection.py?line=130)     Returns the names of the SOMAs in the collection.
    [132](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/soma_collection.py?line=131)     """
--> [133](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/soma_collection.py?line=132)     return self.get_member_names()

File [~/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/tiledb_group.py:259](https://vscode-remote+ssh-002dremote-002b132-002e68-002e111-002e84.vscode-resource.vscode-cdn.net//~/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/tiledb_group.py:259), in TileDBGroup.get_member_names(self)
    [254](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/tiledb_group.py?line=253) def get_member_names(self) -> Sequence[str]:
    [255](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/tiledb_group.py?line=254)     """
    [256](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/tiledb_group.py?line=255)     Returns the names of the group elements. For a SOMACollection, these will SOMA names;
    [257](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/tiledb_group.py?line=256)     for a SOMA, these will be matrix/group names; etc.
    [258](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/tiledb_group.py?line=257)     """
--> [259](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/tiledb_group.py?line=258)     return list(self.get_member_names_to_uris().keys())

File [~/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/tiledb_group.py:274](https://vscode-remote+ssh-002dremote-002b132-002e68-002e111-002e84.vscode-resource.vscode-cdn.net//~/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/tiledb_group.py:274), in TileDBGroup.get_member_names_to_uris(self)
    [269](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/tiledb_group.py?line=268) """
    [270](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledbsoma/tiledb_group.py?line=269) Like ``get_member_names()`` and ``get_member_uris``, but returns a dict mapping from
...
--> [409](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledb/ctx.py?line=408)     super().__init__(ctx, *args)
    [410](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledb/ctx.py?line=409) else:
    [411](file:///home/zlin/.rminiconda/tiledb_python/lib/python3.11/site-packages/tiledb/ctx.py?line=410)     super().__init__(*args)

TileDBError: [TileDB::GroupDirectory] Error: Cannot open group; Group does not exist.`
Could you help me pls? Thanks in advance.

**Comment by johnkerl** [comment]
Hi @lzyent !

From `Group does not exist` I'm not quite sure if all the notebook steps have been included.

For compact presentation here is a smaller-scale example:

```
# Install packages
>>> import tiledb, tiledbsoma, tiledbsoma.io
>>> import anndata as ad
>>> import scanpy as sc
>>> print(f"""
...     TileDB-Py v{tiledb.version()}
...     TileDB-Cloud v{tiledb.cloud.__version__}
...     TileDB-SOMA v{tiledbsoma.__version__}
...     """)

    TileDB-Py v(0, 22, 2)
    TileDB-Cloud v0.10.17
    TileDB-SOMA v0.1.22
```

```
# Set up data
>>> pbmc3k = sc.datasets.pbmc3k()
>>> pbmc3k
AnnData object with n_obs × n_vars = 2700 × 32738
    var: 'gene_ids'

>>> sc.pp.calculate_qc_metrics(pbmc3k, inplace = True)
>>> pbmc3k
AnnData object with n_obs × n_vars = 2700 × 32738
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes'
    var: 'gene_ids', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
```

```
# Ingest to SOMA v0.1 format
>>> soma = tiledbsoma.SOMA('pbmc3k')
>>> tiledbsoma.io.from_anndata(soma, pbmc3k)
Writing pbmc3k/X/data ...
Wrote pbmc3k/obs
Wrote pbmc3k/var
Wrote pbmc3k/X/data
Wrote pbmc3k
```

```
# Examine the full dataset
>>> soma
Name:    pbmc3k
URI:     pbmc3k
(n_obs, n_var): (2700, 32738)
X:       'data'
obs:     'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes'
var:     'gene_ids', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
obsm:
varm:
obsp:
varp:
uns:

>>> soma.obs
'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes'

>>> soma.var
'gene_ids', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'

>>> soma.uri
'pbmc3k'
```

```
# Query the full dataset to extract a slice
>>> slice = soma.query(obs_query_string='pct_counts_in_top_500_genes > 95')
>>> adata = slice.to_anndata()
>>> adata
AnnData object with n_obs × n_vars = 331 × 32738
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes'
    var: 'gene_ids', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
```

**Comment by lzyent** [comment]
> 

Hi@johnkerl, thank you for the reply! But I still encounter an error like this. I tried reinstalling tiledb, but it still doesn't work.
```
----> [8](file:///bigdata/zlin/CosMx/loading.py?line=7) TileDB-Cloud v{tiledb.cloud.__version__}
      [9](file:///bigdata/zlin/CosMx/loading.py?line=8) TileDB-SOMA v{tiledbsoma.__version__}
      [10](file:///bigdata/zlin/CosMx/loading.py?line=9) """)

AttributeError: module 'tiledb' has no attribute 'cloud'
```

**Comment by johnkerl** [comment]
@lzyent my apologies -- despite the name, `tiledb.cloud` is not a submodule of the `tiledb` package. It's separate:

```
pip install tiledb.cloud
```

**Comment by johnkerl** [comment]
Closing as stale -- @lzyent if I'm mistaken and this is still an active issue, please let me know and I'll happily re-open -- thank you!
