### ISSUE TITLE
[Bug][python] missing version in `show_package_versions()` output

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#1193]
**Describe the bug**
In release tiledbsoma==1.2.1, the `show_package_versions()` return value has an empty (non-existent) version number for libtiledbsoma:

```
In [2]: import tiledbsoma
In [3]: tiledbsoma.show_package_versions()
tiledbsoma.__version__        1.2.1
TileDB-Py tiledb.version()    (0, 21, 1)
TileDB core version           2.15.0
libtiledbsoma version()       libtiledbsoma=;libtiledb=2.15.0
python version                3.9.16.final.0
OS version                    Linux 5.15.0-1033-aws
```

I expected it to have some sort of version for the SOMA C++ layer, e.g., `libtiledbsoma=??.??.??`

**Comment by johnkerl** [comment]
@bkmartinjr weird. I see

```
>>> soma.show_package_versions()
tiledbsoma.__version__        1.1.1.post32.dev1588231737
TileDB-Py tiledb.version()    (0, 21, 0)
TileDB core version           2.15.0
libtiledbsoma version()       libtiledbsoma=5eaa7e39;libtiledb=2.15.0
python version                3.10.6.final.0
OS version                    Ubuntu 22.04
```

```
>>> soma.show_package_versions()
tiledbsoma.__version__        1.2.1.post4.dev1874900368
TileDB-Py tiledb.version()    (0, 21, 1)
TileDB core version           2.15.0
libtiledbsoma version()       libtiledbsoma=6fc0b590;libtiledb=2.15.0
python version                3.9.0.final.0
OS version                    Darwin 22.3.0
```

on Linux & Mac, respectively.

From
https://github.com/single-cell-data/TileDB-SOMA/blob/1.2.1/libtiledbsoma/src/version.cc#L49
that thing after the `libtiledbsoma=` has to be `VERSION` which is either `"dev"` or `BUILD_COMMIT_HASH`, so it must be the latter ... and then
https://github.com/single-cell-data/TileDB-SOMA/blob/1.2.1/libtiledbsoma/src/CMakeLists.txt#L18-L41

So did you get this via `pip install` or via local checkout?

**Comment by johnkerl** [comment]
Never mind; I can repro by doing `pip install tiledbsoma` (from PyPI, which I normally do not, since as a developer my normal M.O. is editable install from source) and I get

```
>>> soma.show_package_versions()
tiledbsoma.__version__        1.2.1
TileDB-Py tiledb.version()    (0, 21, 1)
TileDB core version           2.15.0
libtiledbsoma version()       libtiledbsoma=;libtiledb=2.15.0
python version                3.9.0.final.0
OS version                    Darwin 22.3.0
```

**Comment by johnkerl** [comment]
So that `libtiledbsoma=...` has only ever shown a git commit hash, or the word `dev`, or nothing
