### ISSUE TITLE
[Feature request] Roll tiledb pin from 2.15.0 to 2.15.1

### ISSUE THREAD

**Issue by eddelbuettel** [single-cell-data/TileDB-SOMA#1222]
**Is your feature request related to a problem? Please describe.**

TileDB 2.15.1 has been released

**Describe the solution you'd like**

Updated the pin for the tarball downloaded

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by johnkerl** [comment]
@eddelbuettel sorry I didn't make this clearer -- this is part of #1199

**Comment by johnkerl** [comment]
> My bad

Mine TBH. Nothing in my PR title made it clear I was bumping to 2.15.1 along the way. Fixed now. Thank you!

**Comment by eddelbuettel** [comment]
And horror of horros I didn't `git nb` first.  Very bad.  Will revert and push.

Turns out I cannot push.  Can you clean up for me please?  I did

```sh
$ git reset --hard e97048dc         # works, local
$ git push --force-with-lease origin    # rejected, as I do not own magic pixie dust
```

Sorry for the troubles.

**Comment by johnkerl** [comment]
@eddelbuettel will sync 1-1 / videochat to clean up

**Comment by johnkerl** [comment]
Done on #1199 which is merged
