### ISSUE TITLE
[r] Seurat I/O stress-testing

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1238]
* Try out several inputs
* Try out data files produced by different organizations/laboratories
* Try out various sizes
* Ingest, (full) outgest, and queries
  * Queries including by-gene, by-cell, and mixed
* No need to find the very-biggest-possible ingestion case, but do look for scaling concerns
  * Especially with an eye to the known issue #718

**Comment by pablo-gar** [comment]
testing from CZ CELLxGENE Census can be found here
https://github.com/chanzuckerberg/cellxgene-census/tree/main/api/r/cellxgene.census/tests#acceptance-expensive-tests

A summary and comparison to python performance is here:
https://docs.google.com/spreadsheets/d/1dlp6ExRLUsMz7U020VvXjMiNEhtIFZmXsFVIwWj_yzk/edit#gid=0

**These tests relate specifically to the outgestor**

We will repeat these tests at least every six months (right before we perform a [Census LTS data release](https://chanzuckerberg.github.io/cellxgene-census/cellxgene_census_docsite_data_release_info.html)) or at our discretion. 

Our assessment is:
- Seurat outgestor works as intended.
- Efficiency is sufficient.
- There are areas of improvement -- compared to anndata outgestor, Seurat is ~3-10X slower, the bigger the query the slower.

**Comment by johnkerl** [comment]
Closing out the stress-tetsing issue per se, with follow-on work as identified above tracked in #1536
