### ISSUE TITLE
[r] Support BOOL attributes in value_filter

### ISSUE THREAD

**Issue by mlin** [single-cell-data/TileDB-SOMA#1262]
where `census` is our top-level `SOMACollection` for CELLxGENE Census:

```{r}
> census$get("census_data")$get("homo_sapiens")$obs$attributes()$is_primary_data
tiledb_attr(name="is_primary_data", type="BOOL", ncells=1, nullable=FALSE, filter_list=tiledb_filter_list(c(tiledb_filter_set_option(tiledb_filter("ZSTD"),"COMPRESSION_LEVEL",-1)))) 
> census$get("census_data")$get("homo_sapiens")$obs$read(column_names="cell_type", value_filter="is_primary_data == TRUE")
Error: Currently unsupported type: BOOL
In addition: Warning message:
In stopifnot(`Argument 'qc' with query condition object required` = is(qc,  :
  NAs introduced by coercion
```

**Comment by eddelbuettel** [comment]
Thank you -- that is a defect in the `tiledb-r` package I need to address there as we 'borrow' the parsing of query conditions.  

Minimally reproducible example:

```r
> sdf <- data.frame(rows=1:10, vals=100+cumsum(rnorm(10)), lab=sample(c(TRUE,FALSE), 10, TRUE))
> sdf
   rows     vals   lab
1     1  99.3938 FALSE
2     2 100.0966  TRUE
3     3 101.2714 FALSE
4     4 101.5223 FALSE
5     5 100.2753  TRUE
6     6 100.2295 FALSE
7     7  99.6596  TRUE
8     8  98.9282  TRUE
9     9 100.3827 FALSE
10   10 101.0650 FALSE
> library(tiledb)
TileDB R 0.19.0.3 with TileDB Embedded 2.16.0 on Ubuntu 22.10. See https://tiledb.com for more information.
> fromDataFrame(sdf, "/tmp/tiledb/withbool", col_index=1)
> arr <- tiledb_array("/tmp/tiledb/withbool")
> qc <- parse_query_condition(lab == TRUE, ta=arr)
Error: Currently unsupported type: BOOL
In addition: Warning message:
In stopifnot(`Argument 'qc' with query condition object required` = is(qc,  :
  NAs introduced by coercion
> 
```

**Comment by eddelbuettel** [comment]
That appears to be a Core constraint.  A simple C++ example also fails:

```
$ g++ -std=c++17 -o qcb query_cond_bool.cpp -ltiledb; ./qcb
terminate called after throwing an instance of 'tiledb::TileDBError'
  what():  C API: TileDB Internal, std::exception; QueryCondition::apply_ast_node: Cannot perform query comparison; Unsupported query conditional type on lab
Aborted (core dumped)
$
```

**Comment by eddelbuettel** [comment]
IIRC there is ongoing work in Core about generalising the AST and 'flattening' expressions when NOT gets added etc.

**Comment by mlin** [comment]
@eddelbuettel thanks for looking into this!

> That appears to be a Core constraint.

Hmmm...the R example was ported from an existing Python one, that currently works or at least did recently. 

https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/analysis_demo/comp_bio_census_info.ipynb

```{python}
human_cell_types = (
    census["census_data"]["homo_sapiens"]
    .obs.read(column_names=["cell_type"], value_filter="is_primary_data == True")
    .concat()
    .to_pandas()
)
```

Not sure if the Core situation is more complicated than appears at first glance, or the Python binding has some higher-level workaround for it?

**Comment by eddelbuettel** [comment]
@mlin Yup, yup.  I got distracted by one small distraction in our core library and boolean attributes, and then misattributed something.  Long story short the core library is fine (we had bool for a while), and I just updated the query condition parsing (which SOMA 'borrows' or, rather, calls) to properly deal with BOOL attributes.  Now on a simply array with a boolean column:

```sh
$ r -ltiledb -e'arr <- tiledb_array("withbool"); qc <- parse_query_condition(labs == TRUE, ta=arr); query_condition(arr) <- qc; print(arr[])'
    rows     vals   labs
   <int>    <num> <lgcl>
1:     2 100.0966   TRUE
2:     5 100.2753   TRUE
3:     7  99.6596   TRUE
4:     8  98.9282   TRUE
$ r -ltiledb -e'arr <- tiledb_array("withbool"); qc <- parse_query_condition(labs == FALSE, ta=arr); query_condition(arr) <- qc; print(arr[])'
    rows     vals   labs
   <int>    <num> <lgcl>
1:     1  99.3938  FALSE
2:     3 101.2714  FALSE
3:     4 101.5223  FALSE
4:     6 100.2295  FALSE
5:     9 100.3827  FALSE
6:    10 101.0650  FALSE
$ 
```

**Comment by eddelbuettel** [comment]
@mlin With the dual change from the [branch to Core by @nguyenv](https://github.com/TileDB-Inc/TileDB/tree/viviannguyen/qc-bool-fixes) and [my PR to the R package](https://github.com/TileDB-Inc/TileDB-R/pull/540) this should 'just work'.  Thanks for the nudge, this clearly is making things better.

**Comment by mlin** [comment]
@pablo-gar @atolopko-czi @maniarathi @johnkerl FYI for tracking -- we have one more TileDB Core patch that will be necessary for tiledbsoma R 1.0

**Comment by johnkerl** [comment]
Assigning to myself for package-wangling at this point

**Comment by eddelbuettel** [comment]
That is done via TileDB 2.15.2 and the tiledb-r PR https://github.com/TileDB-Inc/TileDB-R/pull/541 making it the preferred version.
