### ISSUE TITLE
[r] [bug] `SOMAExperimentAxisQuery` `$X()` `$obs()` and `$var()` should  have an argument `iterated`

### ISSUE THREAD

**Issue by pablo-gar** [single-cell-data/TileDB-SOMA#1271]
**Describe the bug**
[r] [bug] [`SOMAExperimentAxisQuery`](https://github.com/single-cell-data/TileDB-SOMA/blob/02e0b2f9d7f728bfef7ee8d2e2df326f53c871f8/apis/r/R/SOMAExperimentAxisQuery.R#L28) `$X()` `$obs()` and `$var()` should  have an argument `iterated` hat gets passed to `read_arrow_table`

Otherwise there are no  low-latency reading capabilities o those methods from an Experiment Query.

**Comment by johnkerl** [comment]
Duplicate of #1285
