### ISSUE TITLE
[r] Build R/C++ code with shared rather than static `libtiledbsoma`

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1293]
Split out from #1277 .

PR #1280 has CI fail on MacOS, and skipped on Linux -- not clear it works either place.

This needs debugging.

**Comment by eddelbuettel** [comment]
Nit:  It's not 'Rcpp code' .  It's native (C/C++) code in an R package that happens to use Rcpp for glue.

**Comment by johnkerl** [comment]
#1302 is merged
