### ISSUE TITLE
[Bug] `AttributeError` in `tiledbsoma.io.from_anndata()`

### ISSUE THREAD

**Issue by maarten-devries** [single-cell-data/TileDB-SOMA#1294]
**Describe the bug**

I tried to use `tiledbsoma.io.from_anndata()`. I get an `AttributeError: 'Ctx' object has no attribute '_open_timestamp_ms'`. 

**To Reproduce**
```
import tiledb
import tiledbsoma as soma
import tiledbsoma.io
import scanpy as sc

config["rest.token"] = os.environ['TILEDB_API_KEY']
ctx = tiledb.Ctx(config)

adata = sc.datasets.pbmc3k_processed() 
experiment_uri = "tiledb://OUR_S3_URL" 
tiledbsoma.io.from_anndata(experiment_uri, adata, measurement_name="RNA", context=ctx, platform_config=config)  


```

**Versions (please complete the following information):**
 - TileDB-SOMA version: 1.2.2
 - Language and language version (e.g. Python 3.8, R 4.2.2): Python 3.9.16
 - OS (e.g. MacOS, Ubuntu Linux): Ubuntu Linux
 - Note: you can use `tiledbsoma.show_package_versions()` (Python) or `tiledbsoma::show_package_versions()` (R)

**Additional context**

**Comment by maarten-devries** [comment]
Perhaps I am passing in the wrong `context` here - please give me a minute while I figure that out.

**Comment by johnkerl** [comment]
@maarten-devries no worries, I have a repro I can work with

**Comment by maarten-devries** [comment]
Changing `ctx = tiledb.Ctx(config)`
to 
`tiledb_ctx = tiledb.cloud.Ctx()
ctx = tiledbsoma.SOMATileDBContext(tiledb_ctx=tiledb_ctx)`

resolves at least this issue.
