### ISSUE TITLE
[Bug] to_anndata fails on a specific SOMA artifact

### ISSUE THREAD

**Issue by ebezzi** [single-cell-data/TileDB-SOMA#1310]
**Describe the bug**
When calling `to_anndata` on this specific artifact (link below), the following error is raised:
```AttributeError: 'SparseNDArrayRead' object has no attribute 'to_numpy'```
The issue seems specific to the `obsm` array (ingest.py:1280)
The artifact was generated by opening the pbmc-small.h5ad file that exists in the repo, converting it to Seurat and then back to SOMA.

**To Reproduce**
```
import tiledbsoma as soma
pbmc = soma.open("from_seurat_soma")
io.to_anndata(
    pbmc, measurement_name="RNA"
)
```

[SOMA Artifact](https://drive.google.com/file/d/1pSw8j_VyKp4Ovty5on_Q7_ep_1x1lhjo/view?usp=share_link)

**Versions (please complete the following information):**
 - TileDB-SOMA version: 1.2.1
 - Language and language version (e.g. Python 3.8, R 4.2.2): Python 3.10
 - OS (e.g. MacOS, Ubuntu Linux): MacOS X

**Additional context**
N/A

**Comment by johnkerl** [comment]
Fixed by #1246 which is in 1.2.2
