### ISSUE TITLE
[Bug/Feature] Suggest to move two headers

### ISSUE THREAD

**Issue by eddelbuettel** [single-cell-data/TileDB-SOMA#1315]
**Describe the bug**

The directory `libtiledbsoma/src/cli/ ` contains two headers for Arrow that do not pertain to command-line functionality.
These may be better placed in `libtiledbsoma/src/utils/`, and I would be happy to send in a PR with a change which I have tested.

**To Reproduce**

Nothing to reproduce. See the `main` branch:  https://github.com/single-cell-data/TileDB-SOMA/tree/main/libtiledbsoma/src/cli

**Versions (please complete the following information):**

See the `main` branch:  https://github.com/single-cell-data/TileDB-SOMA/tree/main/libtiledbsoma/src/cli

**Additional context**

It is understood that the headers are a little in flux.  If a move to another location is already planned just note it here and close the issue.

**Comment by nguyenv** [comment]
If you already have a branch with these changes, please feel open a PR.
