### ISSUE TITLE
[Bug] Updating to 1.2.2 does not trigger update of (necessary) tiledbpy dependency

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#1322]
**Describe the bug**

Updating to `tiledbsoma==1.2.2` when you have `tiledb==0.21.2` installed will fail to update the `tiledb` package.  `tiledbsoma` 1.2.2 *requires* `0.21.3` for the newly added `config` param in `tiledb.Group`, so any any attempt to open collections in this config will fail.

Looks like a dependency specification problem in in tiledbsoma.

See chanzuckerberg/cellxgene-census#447 for test case and config it was found in

**Comment by johnkerl** [comment]
@bkmartinjr I believe the `config` param in `tiledb.Group` was added in [0.21.2](https://github.com/TileDB-Inc/TileDB-Py/releases/tag/0.21.2), and I believe this is resolved by #1299. (Note that #1299 is not yet included in a TileDB-SOMA release, but it will be included in the next one.)

**Comment by johnkerl** [comment]
@bkmartinjr correct, and @1296 addresses precisely that. I think we're on the same page. :)

**Comment by maniarathi** [comment]
Closing as completed. We'll create a new issue in cellxgene-census to remove the workaround.
