### ISSUE TITLE
[Bug] SparseNDArray incorrect shape

### ISSUE THREAD

**Issue by ivirshup** [single-cell-data/TileDB-SOMA#1327]
**Describe the bug**

SparseNDArrays seem to report their shape incorrectly (at least from expected value).

**To Reproduce**
Provide a code example and any sample input data (e.g. an H5AD) as an attachment to reproduce this behavior.

```python
import anndata as ad
from scipy import sparse

from tiledbsoma.io import from_anndata
import tiledbsoma as soma

adata = ad.AnnData(sparse.random(100, 100, format="csr", density=.1))
from_anndata("test-shape", adata, "test-shape")
# 'test-shape'

exp = soma.Experiment.open('test-shape')
exp.ms["test-shape"].X["data"].shape
# (9223372036854773760, 9223372036854773760)
```

I would have expected the array to be 100 x 100

**Versions (please complete the following information):**
tiledbsoma.__version__        1.2.1
TileDB-Py tiledb.version()    (0, 21, 2)
TileDB core version           2.15.1
libtiledbsoma version()       libtiledbsoma=;libtiledb=2.15.0
python version                3.10.10.final.0
OS version                    Darwin 20.6.0

**Comment by johnkerl** [comment]
@ivirshup thanks! There's been quite a bit of discussion here and this is by (current) design. The shape is the capacity; the dimensions of what's actually there are `obs.count` and `var.count`.

That said, I know this is counter-intuitive, as we are using `shape` in a non-standard way here ...

**Comment by johnkerl** [comment]
@ivirshup yes, by "capacity" and "max shape" I think we mean the same thing.

If you `create` a `SparseNDArray` with `shape=(100,100)` then what you can `write` to it always must have both coordinates in the 0..99 (inclusive) range. This is a use-case for "immutable" snapshot/cell-census/cell-atlas behavior.

If you `create` a `SparseNDArray` with default shape then you can `write` various dimensions to it later. This is a use-case for "mutable" behavior wherein you'll write some data to the array today, and write more tomorrow, for example.
