### ISSUE TITLE
[bug/r] The `pkgdown` CI is erroring when it runs on a release

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1329]
As seen, for most recent example, on [1.2.3](https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.2.3), it does not run to completion:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/4876455118

To do:

* Root-cause and fix the issue
* Implement/document a manual way to re-run after fail, but before the next release (note that [.github/workflows/pkgdown.yaml](https://github.com/single-cell-data/TileDB-SOMA/blob/main/.github/workflows/pkgdown.yaml) already has a `workflow_dispatch` so it ought to be manually runnable)

**Comment by eddelbuettel** [comment]
I suspect this to be a duplicate of #1334 (or vice versa). IIRC `pkgdown`, like `R CMD check` and other tasks, does everything in a temp directory with a minimal libPaths to ensure only declared packages are used.

**Comment by johnkerl** [comment]
🤞

**Comment by johnkerl** [comment]
@eddelbuettel I leave it to you to dup this to #1334 if you feel that's appropriate

**Comment by johnkerl** [comment]
I ran this manually & it completed successfully. See #1361 by @eddelbuettel for the fix.
