### ISSUE TITLE
[r] Update dev notes in `apis/r/README.md`

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1333]
As of #1301 and #1302, the developer workflow has changed. This needs to be documented in `apis/r/README.md`.

* Source of truth is `.github/workflows/r-ci.yml` -- let's have the readme point to that
* Additional "color" in the README including "Access to more test data ..." should remain there
* `cleanup` doesn't exist anymore
* `copy_source.sh` doesn't exist anymore
* `scripts/bld --prefix=/usr/local` and `sudo ldconfig` (the latter for Linux) need to be there
* Additional "color" in the README including `R CMD build ...` and `R CMD INSTALL ...` are, of course, obvious to R experts -- but in the spirit of inclusivity and polyglottalism we should retain this helpful information in the readme

See also #1334.

**Comment by eddelbuettel** [comment]
Quick adds.  Maybe
- not point to r-ci.yml, it is internal
- ~add `cleanup` back in, that is standard R package fare~ `cleanup` is [still there](https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/r/cleanup)
