### ISSUE TITLE
[r] Restore `remotes::install_github` functionality

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1334]
As a necessary consequence of #1301 and #1302, our previous `remotes::install_github` functionality is no longer functioning.

Ideally we would get this back, whlie not breaking any package-manager installs.

This will require, as a prerequisite, having an artifact that can be downloaded for C++ `libtiledbsoma`, or other means to ensure a system library.

See also #1333 and #1365.

**Comment by johnkerl** [comment]
@eddelbuettel I leave it to you to dup this to #1329 if you feel that's appropriate

**Comment by eddelbuettel** [comment]
This should be taken care of by #1361.
