### ISSUE TITLE
[r] Install failure for arm64 (Mac M2) R 4.2

### ISSUE THREAD

**Issue by davemcg** [single-cell-data/TileDB-SOMA#1342]
**Describe the bug**

```
if [ "" != "Windows_NT" ] && [ `uname -s` = 'Darwin' ] && [ -f ../inst/tiledb/lib/libtiledb.dylib ] && [ -f tiledbsoma.so ]; then install_name_tool -change libz.1.dylib @rpath/libz.1.dylib ../inst/tiledb/lib/libtiledb.dylib; install_name_tool -add_rpath @loader_path/../tiledb/lib tiledbsoma.so; fi
installing to /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/00LOCK-tiledbsoma/00new/tiledbsoma/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
Error : EphemeralCollection.Rd:7: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/00LOCK-tiledbsoma/00new/tiledbsoma/libs/tiledbsoma.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/00LOCK-tiledbsoma/00new/tiledbsoma/libs/tiledbsoma.so, 0x0006): symbol not found in flat namespace '__ZN10tiledbsoma13LOG_SET_LEVELERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
ERROR: installing Rd objects failed for package ‘tiledbsoma’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/tiledbsoma’
```
**To Reproduce**
Running `install.packages('tiledbsoma', repos = c('https://tiledb-inc.r-universe.dev', 'https://cloud.r-project.org'))` in R

**Versions (please complete the following information):**
 - TileDB-SOMA version: ?
 - Language and language version (e.g. Python 3.8, R 4.2.2): R 4.2.3
 - OS (e.g. MacOS, Ubuntu Linux): MacOS 13.3.1
 - Note: you can use `tiledbsoma.show_package_versions()` (Python) or `tiledbsoma::show_package_versions()` (R)

**Additional context**

**Comment by johnkerl** [comment]
@davemcg we don't yet have MacOS ARM64 artifacts at PyPI but I've installed from source on my M1 Mac & am happy to help with any issues as well.

**Comment by davemcg** [comment]
Thanks! I ran `scripts/bld --prefix=/usr/local` at the top level of this git dir. That seems to have run successfully (though I did have to run it with `sudo`). 

But this step is failing. The folder doesn't exist.

```
(base): r mcgaugheyd$ pwd
/Users/mcgaugheyd/git/TileDB-SOMA/apis/r

(base): r mcgaugheyd$ ./configure; R CMD INSTALL .
* installing to library ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library’
* installing *source* package ‘tiledbsoma’ ...
** using staged installation
** libs
/opt/homebrew/bin/g++-12 -llz4 -std=c++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I. -I../inst/include/ -I../inst/tiledb/include -I  -Iinclude -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppSpdlog/include' -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -I/opt/homebrew/opt/openssl/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/tcl-tk/include   -fPIC  -g -O3 -Wall -pedantic -mtune=native -pipe -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
../inst/include/tiledbsoma_types.h:7:10: fatal error: tiledbsoma/tiledbsoma: No such file or directory
    7 | #include <tiledbsoma/tiledbsoma>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘tiledbsoma’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/tiledbsoma’
```

**Comment by eddelbuettel** [comment]
Hm. The output from runnning `scripts/bld --prefix=/usr/local` should include a few lines indicating that fikes are installed. Here it is in fresh Docker container (as I don't have macOS around):

```sh
root@69296a826987:/work# scripts/bld --prefix=/usr/local
Building Release build
-- Install prefix is /usr/local.
[.... lots omitted ...]
[100%] Built target Catch2WithMain
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libtiledb.so.2.15
-- Installing: /usr/local/include/tiledbsoma/soma/logger_public.h
-- Installing: /usr/local/include/tiledbsoma/soma/managed_query.h
-- Installing: /usr/local/include/tiledbsoma/soma/soma_array.h
-- Installing: /usr/local/include/tiledbsoma/tiledbsoma
-- Installing: /usr/local/include/tiledbsoma/utils/array_buffers.h
-- Installing: /usr/local/include/tiledbsoma/utils/arrow_adapter.h
-- Installing: /usr/local/include/tiledbsoma/utils/carrow.h
-- Installing: /usr/local/include/tiledbsoma/utils/column_buffer.h
-- Installing: /usr/local/include/tiledbsoma/utils/common.h
-- Installing: /usr/local/include/tiledbsoma/utils/logger.h
-- Installing: /usr/local/include/tiledbsoma/utils/stats.h
-- Installing: /usr/local/include/tiledbsoma/utils/util.h
-- Installing: /usr/local/include/tiledbsoma/utils/version.h
-- Installing: /usr/local/include/tiledbsoma/utils/span/span.hpp
-- Installing: /usr/local/lib/cmake/tiledbsoma/TileDBSomaConfig.cmake
-- Installing: /usr/local/lib/libtiledbsoma.so
-- Set runtime path of "/usr/local/lib/libtiledbsoma.so" to "/usr/local/lib:/work/build/externals/install/lib"
-- Installing: /usr/local/include/tiledbsoma/tiledbsoma_export.h
-- Installing: /usr/local/bin/tdbsoma
-- Set runtime path of "/usr/local/bin/tdbsoma" to "/usr/local/lib:/work/build/externals/install/lib"
-- Installing: /usr/local/lib/cmake/tiledbsoma/TileDBSomaTargets.cmake
-- Installing: /usr/local/lib/cmake/tiledbsoma/TileDBSomaTargets-release.cmake
-- Installing: /usr/local/lib/pkgconfig/tiledbsoma.pc
-- Up-to-date: /usr/local/lib/libtiledb.so.2.15
Built target install-libtiledbsoma
[  7%] Built target TILEDB_SOMA_OBJECTS
[ 93%] Built target Catch2
[ 95%] Built target Catch2WithMain
[ 98%] Building CXX object test/CMakeFiles/unit_soma.dir/unit_managed_query.cc.o
[ 98%] Building CXX object test/CMakeFiles/unit_soma.dir/unit_soma_array.cc.o
[ 98%] Building CXX object test/CMakeFiles/unit_soma.dir/unit_column_buffer.cc.o
[100%] Linking CXX executable unit_soma
[100%] Built target unit_soma
[100%] Built target build_tests
root@69296a826987:/work# 
``` 

So here we see `/usr/include/tiledbsoma/` being filled, and the package installation should then find it.  Your line shows (and I indent)

```
/opt/homebrew/bin/g++-12 -llz4 -std=c++17 -I"/Library/Frameworks/R.framework/Resources/include" \
     -DNDEBUG -I. -I../inst/include/ -I../inst/tiledb/include -I  \
     -Iinclude -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' \
     -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppSpdlog/include' \
     -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk \
    -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include \
    -I/opt/homebrew/opt/openssl/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/tcl-tk/include  \
    -fPIC  -g -O3 -Wall -pedantic -mtune=native -pipe -c RcppExports.cpp -o RcppExports.o
```

and indeed -- no `/usr/local/include`.  Our builds tend to use CRAN tools for macOS, not homebrew, so I guess we have to account for this.  

As a fix, please try adding an explicit `-I/usr/local/include` to `PKG_CPPFLAGS` in `src/Makevars.in` and re-try the `R CMD INSTALL .` step.

**Comment by johnkerl** [comment]
@davemcg I just successfully installed from source on my M1.

What version of TileDB-SOMA do you have checked out?

**Comment by davemcg** [comment]
I'm at `79511bb`

I edited Makevars.in to: `PKG_CPPFLAGS = -I. -I../inst/include/ @tiledb_include@ @cxx17_macos@ -Iinclude -I/usr/local/include`

The compilation got further then cratered at:

```
* installing to library ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library’
* installing *source* package ‘tiledbsoma’ ...
** using staged installation
** libs
/opt/homebrew/bin/g++-12 -llz4 -std=c++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -L/opt/homebrew/opt/llvm/lib -Wl,-rpath,/opt/homebrew/opt/llvm/lib -o tiledbsoma.so RcppExports.o nanoarrow.o rinterface.o riterator.o rutilities.o stats.o version.o -ltiledbsoma -ltiledb -L../inst/tiledb/lib -Wl,-rpath,$ORIGIN/../tiledb/lib -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: library not found for -ltiledbsoma
collect2: error: ld returned 1 exit status
make: *** [tiledbsoma.so] Error 1
ERROR: compilation failed for package ‘tiledbsoma’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/tiledbsoma’
```

**Comment by eddelbuettel** [comment]
Hi @davemcg 

We are on slightly uncharted territory as you are on homebrew whereas we are not.  And it seems that my tip to adjust the include path help _for the compilation_.  Now we need a simular step for linking.   Now, on Linux, life is easy for me: `ldconfig` knows.  Under non-homebrew macOS we also know what to do as @johnkerl added the appropriate `install_name_tool` line:  `install_name_tool -add_rpath /usr/local/lib tiledbsoma.so` which instructs macOS to look at `/usr/local/lib` when resolving dynamic linking for the `tiledbsoma.so` library.  

I am afraid you (or another homebrew user) needs to find the matching step for your case. `otool` may help. (I think we will be better off when we have a proper artifact as `pkg-config` can then (hopefully !!) fill in the details. Until then we need to do this by hand.  Thanks for your patience in trying.)

**Comment by johnkerl** [comment]
I use Homebrew on my Macs. Let me dig in a bit more to your error message and see what I can find.

**Comment by eddelbuettel** [comment]
Oh I see -- my world is CRAN-centric and Simon usually recommends tools from https://mac.r-project.org.  I thought you had followed that advice too.

**Comment by johnkerl** [comment]
@davemcg thanks for your patience on this -- while our R API for TileDB-SOMA is near release.

On my M1, checked out to `79511bb`, from the repo base directory I did `sudo scripts/bld --prefix=/usr/local`. This results in

```
/usr/local/include/tiledbsoma/tiledbsoma
...
/usr/local/lib/libtiledbsoma.dylib
```

Then from `apis/r` I did `./configure`.

In my `src/Makevars.in` I used

```
PKG_CPPFLAGS = -Wno-deprecated-declarations -I. -I../inst/include/ @tiledb_include@ @cxx17_macos@ -Iinclude
```

Then with `R CMD INSTALL .` I have a compile line like this (line breaks added):

```
clang++
  -arch arm64
  -std=gnu++17
  -I"/Library/Frameworks/R.framework/Resources/include"
  -DNDEBUG
  -Wno-deprecated-declarations
  -I.
  -I../inst/include/
  -I../inst/tiledb/include
  -I
  -Iinclude
  -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include'
  -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppSpdlog/include'
  -I/opt/R/arm64/include
  -fPIC
  -falign-functions=64
  -Wall
  -g
  -O2
  -c RcppExports.cpp
  -o RcppExports.o
```

while yours is (linebreaks also added)

```
/opt/homebrew/bin/g++-12
  -llz4
  -std=c++17
  -I"/Library/Frameworks/R.framework/Resources/include"
  -DNDEBUG
  -I.
  -I../inst/include/
  -I../inst/tiledb/include
  -I
  -Iinclude
  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include'
  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppSpdlog/include'
  -isysroot
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
  -I/opt/homebrew/include
  -I/opt/homebrew/opt/llvm/include
  -I/opt/homebrew/opt/openssl/include
  -I/opt/homebrew/opt/gettext/include
  -I/opt/homebrew/opt/tcl-tk/include
  -fPIC
  -g
  -O3
  -Wall
  -pedantic
  -mtune=native
  -pipe
  -c RcppExports.cpp
  -o RcppExports.o
```

After that, in R, `library(tiledbsoma)` and `tiledbsoma::show_package_versions()`.

Here's what I think is going on. As we can see in our compile lines, I don't have `-I/usr/local/include` or `-L/usr/local/lib` in my `src/Makevars.in`, but it seems that my compiler is including those paths implicitly -- and likewise for the compiler running in our MacOS CI jobs. (Those are x64-64 MacOS, but, I don't think this is really an x64-64/arm64 here after all.) It appears to be simply the case that your compiler isn't including those paths.

So I think the workaround here should be for you to explicitly incliude `-I/usr/local/include` and `-L/usr/local/lib` in `src/Makevars.in`. And I think we should modify our package to do so, since not all compilers include those paths explicitly.

**Comment by davemcg** [comment]
I appreciate all of your help here. I'm also fine if you want to cut your losses (I have the python version of this running) and have me come back whenever you get this precompiled onto CRAN (?).

I ran ./cleanup and still am getting stuck in the same place (even though I know have the new paths). I do have tiledbsoma here:

```
(base):r mcgaugheyd$ ls -lh /usr/local/include/tiledbsoma/
total 16
drwxr-xr-x@  5 root  wheel   160B May  5 16:43 soma
-rwxrwxr-x@  1 root  wheel   1.8K May  5 13:03 tiledbsoma
-rw-r--r--@  1 root  wheel   1.1K May  6 21:04 tiledbsoma_export.h
drwxr-xr-x@ 12 root  wheel   384B May  5 16:43 utils
````

and
```
(base):r mcgaugheyd$ ls -lh /usr/local/lib/libtiledbsoma.dylib
-rwxrwxrwx@ 1 root  wheel   576K May  6 21:05 /usr/local/lib/libtiledbsoma.dylib
```

But still I get hung up here
```
/opt/homebrew/bin/g++-12 -llz4 -std=c++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Wno-deprecated-declarations -I. -I../inst/include/ -I../inst/tiledb/include -I  -Iinclude -I/usr/local/include -L/usr/local/lib -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppSpdlog/include' -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -I/opt/homebrew/opt/openssl/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/tcl-tk/include   -fPIC  -g -O3 -Wall -pedantic -mtune=native -pipe -c stats.cpp -o stats.o
/opt/homebrew/bin/g++-12 -llz4 -std=c++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Wno-deprecated-declarations -I. -I../inst/include/ -I../inst/tiledb/include -I  -Iinclude -I/usr/local/include -L/usr/local/lib -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppSpdlog/include' -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -I/opt/homebrew/opt/openssl/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/tcl-tk/include   -fPIC  -g -O3 -Wall -pedantic -mtune=native -pipe -c version.cpp -o version.o
/opt/homebrew/bin/g++-12 -llz4 -std=c++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -L/opt/homebrew/opt/llvm/lib -Wl,-rpath,/opt/homebrew/opt/llvm/lib -o tiledbsoma.so RcppExports.o nanoarrow.o rinterface.o riterator.o rutilities.o stats.o version.o -ltiledbsoma -ltiledb -L../inst/tiledb/lib -Wl,-rpath,$ORIGIN/../tiledb/lib -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: library not found for -ltiledbsoma
collect2: error: ld returned 1 exit status
make: *** [tiledbsoma.so] Error 1
ERROR: compilation failed for package ‘tiledbsoma’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/tiledbsoma’
```

**Comment by davemcg** [comment]
And slightly in my defense I am only using homebrew gcc because ANOTHER package needed it because the OS X gcc is kind of old. Now perhaps I *should* be putting R things into different condo envs...

**Comment by eddelbuettel** [comment]
Our issue right now seems to be that the location we chose (and for the time being even hardwired) does not come out right for your system. I have been told `otool` can help with diagnostics -- on Linux I can use `ldd` on the package's dynamic module  and it finds the libraries needed,  ie here I can `grep` the one giving you trouble:  

```sh
$ ldd /usr/local/lib/R/site-library/tiledbsoma/libs/tiledbsoma.so | grep soma
        libtiledbsoma.so => /usr/local/lib/libtiledbsoma.so (0x00007fd497fd6000)
$ 
```

We'd need to have that `libtiledbsoma.dylib` you successfully built in a place the dynamic linker on your system finds it.  We are running this command (via `src/Makevars{,.in}`) on the shared library build as part of the R package to have it look at `/usr/local/lib` but somehow that fails on your system:

```
install_name_tool -add_rpath /usr/local/lib tiledbsoma.so
```

and while that seems to work for the macOS setup we have in CI it fails on yours.  I wish I knew why.

**Comment by eddelbuettel** [comment]
It's a bit outside my area as non-macOS user but maybe we should try installing via `scripts/bld --prefix=/opt/homebrew` to have `/opt/homebrew/lib/libtiledbsoma.dylib` created.  The R link step may then work (if that is a default directoy) or be aided by another `-L/opt/homebrew/lib` in `PKG_LIBS`.   Helpful reference:  https://github.com/Homebrew/brew/issues/9214

**Comment by johnkerl** [comment]
@davemcg thank you! :) 

@davemcg @eddelbuettel there are two things here: one is finding the `tiledbsoma` library which is indeed in `/usr/local`, and the other is allowing a configuration option to find it when it's somewhere other than `/usr/local`.

These are both problems worth solving; and they are orthogonal.

@davemcg 's compile and link lines are like this:

```
/opt/homebrew/bin/g++-12
  -I"/Library/Frameworks/R.framework/Resources/include"
  -I.
  -I../inst/include/
  -I../inst/tiledb/include
  -I
  -Iinclude
  -I/usr/local/include
  -L/usr/local/lib
  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include'
  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppSpdlog/include'
  ...
  -c version.cpp -o version.o

/opt/homebrew/bin/g++-12
  -L/Library/Frameworks/R.framework/Resources/lib
  -L/opt/R/arm64/lib
  -L/opt/homebrew/opt/llvm/lib
  -Wl,-rpath,/opt/homebrew/opt/llvm/lib
  -o tiledbsoma.so
  RcppExports.o nanoarrow.o rinterface.o riterator.o rutilities.o stats.o version.o
  -ltiledbsoma
  -ltiledb
  -L../inst/tiledb/lib
  ...
```

and this is due to my unfortunate advice above about putting `-L` into `PKG_CPPFLAGS` instead of `PKG_LIBS` as I should have. (You can see above the the `-L/usr/local/lib` is appearing in the first/compile stanza and not the second/link stanza.)

For these two orthogonal issues:

* Putting the `-L/usr/local/lib` in `PKG_LIBS` rather than `PKG_CFLAGS` should result in a successful compile and link
* Improving our build setup to allow putting `libtiledbsoma` into an arbitrary location, and finding it there, I can do either on #1343 or a follow-on.

**Comment by eddelbuettel** [comment]
What I am worried about (as a non-macOS user) is the added security added (?) by some (?) of the recent releases which AFAIK are part of the reason homebrew now uses /opt as /usr/local is no longer searched by default.  But that is hearsay; I do not interface macOS directly.

The equally important story is to move on from this immediate fix and provide an artifact so that builds generalise.

**Comment by johnkerl** [comment]
@eddelbuettel we are agreed; above I noted two bullet items, one for the immediate term, and the other to generalize the build. We are on the same page.

**Comment by davemcg** [comment]
Still stuck. OK, so there was a variety of advice. 

I ran `git pull` again and now am at `817fef4df4841`. I also ran `checkout` on Makevars.in to reset all my of my failed edits.

The default Makevars.in is:
```
PKG_CPPFLAGS = -I. -I../inst/include/ @tiledb_include@ @cxx17_macos@ -Iinclude

## We also need the TileDB library
PKG_LIBS = @cxx17_macos@ -ltiledbsoma @tiledb_libs@ @tiledb_rpath@
```

I ran `git clean -dfx` and edited Makevars.in to:
```
## We need the TileDB Headers, and for macOS aka Darwin need to set minimum version 10.14 for macOS
PKG_CPPFLAGS = -I. -I../inst/include/ @tiledb_include@ @cxx17_macos@ -Iinclude -I/usr/local/include

## We also need the TileDB library
PKG_LIBS = @cxx17_macos@ -ltiledbsoma @tiledb_libs@ @tiledb_rpath@ -L/usr/local/lib
```

But it fails (again?) here:

```
/opt/homebrew/bin/g++-12 -llz4 -std=c++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -L/opt/homebrew/opt/llvm/lib -Wl,-rpath,/opt/homebrew/opt/llvm/lib -o tiledbsoma.so RcppExports.o nanoarrow.o rinterface.o riterator.o rutilities.o stats.o version.o -ltiledbsoma -ltiledb -L../inst/tiledb/lib -Wl,-rpath,$ORIGIN/../tiledb/lib -L/usr/local/lib -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/00LOCK-r/00new/tiledbsoma/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
Error : EphemeralCollection.Rd:7: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/00LOCK-r/00new/tiledbsoma/libs/tiledbsoma.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/00LOCK-r/00new/tiledbsoma/libs/tiledbsoma.so, 0x0006): symbol not found in flat namespace '__ZN10tiledbsoma13LOG_SET_LEVELERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
ERROR: installing Rd objects failed for package ‘tiledbsoma’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/tiledbsoma’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/tiledbsoma’
```

**Comment by johnkerl** [comment]
@davemcg good call about waiting for general release of the R API -- our Python API is indeed GA.

#1343 (which is under revision now) will clarify the picture.

And, no panic re resolving this -- there is a diversity of systems out there, and finding/solving the differences between your Mac setup and mine (where the install succeeds) is indeed very much worth our time. :)

**Comment by eddelbuettel** [comment]
This should now be taken care of by #1361.  We will refine further as needed but e.g. the [r-universe](https://tiledb-inc.r-universe.dev/tiledbsoma) is back and builds via `remotes::install_github()` should work too (with the proper sub-directory hint for `apis/r`).
