### ISSUE TITLE
[r] Timestamped opens

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1347]
Items marked as "1347" on #1241 

For arrays and groups:

* Open at time T1
* Some other process writes at time T2
* Original process opened at T1 does not see these changes until it closes and re-opens

For groups/collections:

* If a collection is opened at a certain timestamp, then all "child" objects accessed via that collection object are also to be opened at that same timestamp

**Comment by mlin** [comment]
Note: if a collection is opened at a certain timestamp, then all "child" objects accessed via that collection object are also to be opened at that same timestamp.

**Comment by mlin** [comment]
Confirming I'll be working on this this week (after some delays adapting cellxgene.census for the new open/close APIs)

**Comment by mlin** [comment]
Merged #1429 with READ-mode timestamp support, and broke out WRITE mode timestamp support to #1450
