### ISSUE TITLE
[Feature request] [c++,r] Refactor build

### ISSUE THREAD

**Issue by eddelbuettel** [single-cell-data/TileDB-SOMA#1353]
**Is your feature request related to a problem? Please describe.**

Builds of the R package currently require a system library which is best installed from the same repo as no artifacts are provided right now.  This breaks builds done at [r-universe](https://tiledb-inc.r-universe.dev/builds) as also seen in #1342

**Describe the solution you'd like**

When no installed `libtiledbsoma` is found, the build will fetch the repository sources (in a first step, to be refined once we have library source artifacts) and build the library so that the package build can proceed.  A second step will create an action to create a `libtiledbsoma` source artifact to be used.  Once that is done the build will be adjusted thart smaller source tarball.

**Describe alternatives you've considered**

Building binary artifacts can be consider but is more involved.

**Additional context**

[SC 28701](https://app.shortcut.com/tiledb-inc/story/28701/refactor-package-build-to-fetch-library-source-if-none-is-found)

**Comment by johnkerl** [comment]
See #1365 for longer-term/contextual tracking.
