### ISSUE TITLE
[tracker] Windows-native TileDB-SOMA

### ISSUE THREAD

**Issue by daweibushen** [single-cell-data/TileDB-SOMA#1360]
**Describe the bug**
```
pip install tiledbsoma
Building wheels for collected packages: tiledbsoma
  Building wheel for tiledbsoma (pyproject.toml): started
  Building wheel for tiledbsoma (pyproject.toml): finished with status 'error'
Failed to build tiledbsoma
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  Building wheel for tiledbsoma (pyproject.toml) did not run successfully.
  exit code: 1
  
  [5 lines of output]
  running bdist_wheel
  Checking: C:\Users\dawei bushen\AppData\Local\Temp\pip-install-725ip_cc\tiledbsoma_ce59cb0207fe481d9e0f336d8115e3fb\dist_links\dist\lib\tiledbsoma.dll exists: False
  Checking: C:\Users\dawei bushen\AppData\Local\Temp\pip-install-725ip_cc\tiledbsoma_ce59cb0207fe481d9e0f336d8115e3fb\dist_links\dist\bin\tiledbsoma.dll exists: False
  Could not find module 'tiledbsoma.dll' (or one of its dependencies). Try using the full path with constructor syntax.
  error: [WinError 2] 系统找不到指定的文件。
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tiledbsoma
ERROR: Could not build wheels for tiledbsoma, which is required to install pyproject.toml-based projects
```

**To Reproduce**
Provide a code example and any sample input data (e.g. an H5AD) as an attachment to reproduce this behavior.

**Versions (please complete the following information):**
 Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19045-SP0

**Additional context**

**Comment by daweibushen** [comment]
Thank you very much for reply，do you mean tiledbsoma will work in wondows oneday？

**Comment by daweibushen** [comment]
looking forward

**Comment by Sirik98** [comment]
Hi All,

The error still persists,Please help with the work around., Trying to install tiledbsoma in windows with python. 

 Could not find module 'tiledbsoma.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tiledbsoma
Failed to build tiledbsoma
ERROR: Could not build wheels for tiledbsoma, which is required to install pyproject.toml-based projects

**Comment by johnkerl** [comment]
@Sirik98 thank you for the feedback! I can leave this open (and should have).

Meanwhile Windows support for TileDB-SOMA is not currently available, but is on our roadmap.

**Comment by Koncopd** [comment]
Works on WSL, but would be really great to have a native build for Windows.

**Comment by johnkerl** [comment]
See also #2631
