### ISSUE TITLE
Where to go with general questions

### ISSUE THREAD

**Issue by royassis** [single-cell-data/TileDB-SOMA#1362]
Hey there, where should I post general questions ? 

I tried using the **TileDB Slack community** link in the readme, but it seems to direct me to the CZI community.

**Comment by johnkerl** [comment]
Hi @royassis ! Can you share the original URL, and the URL you got redirected to?

**Comment by royassis** [comment]
Hey @johnkerl 

Here is the link address https://czi.co/science-slack, the list text is TileDB Slack community.
I'm being rerouted here : https://app.slack.com/client/T8MB1T0MA/browse-channels

**Comment by johnkerl** [comment]
@royassis I think there's a typo in our `README.md`

**Comment by johnkerl** [comment]
@royassis please try
https://tiledb-community.slack.com/join/shared_invite/zt-ndq1ipwl-QcithaWG6j1BImtuQGSpag#/shared-invite/email

**Comment by eddelbuettel** [comment]
I think we can we close this now that the link has been fixed.
