### ISSUE TITLE
[Feature request] [python,r] Add two badges

### ISSUE THREAD

**Issue by eddelbuettel** [single-cell-data/TileDB-SOMA#1374]
**Is your feature request related to a problem? Please describe.**

Installation is recommended, respectively, from PyPI and r-universe.  We could add version badges for added visibility.

**Describe the solution you'd like**

Two lines of markdown can be added to the README.md a la

```
[![PyPI version](https://badge.fury.io/py/tiledbsoma.svg)](https://badge.fury.io/py/tiledbsoma)
[![tiledbsoma status badge](https://tiledb-inc.r-universe.dev/badges/tiledbsoma)](https://tiledb-inc.r-universe.dev)
```

yielding

[![PyPI version](https://badge.fury.io/py/tiledbsoma.svg)](https://badge.fury.io/py/tiledbsoma)
[![tiledbsoma status badge](https://tiledb-inc.r-universe.dev/badges/tiledbsoma)](https://tiledb-inc.r-universe.dev)

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by johnkerl** [comment]
Let's do it! :)

**Comment by eddelbuettel** [comment]
Anything else 'pending' you can think of while I prepare the quick PR?

**Comment by johnkerl** [comment]
Nah, that's good for now. Later there will be more but I think some good green signal high up in the `README.md` (above the scroll) has super-good optics on GitHub.
