### ISSUE TITLE
[python] Code-review follow-up

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1378]
I don't understand what behavior would lead to this case—this seems like it would violate one of the preconditions that I would expect. How do we arrive here?

_Originally posted by @thetorpedodog in https://github.com/single-cell-data/TileDB-SOMA/pull/1325#discussion_r1194163445_

Parent: #1346

**Comment by johnkerl** [comment]
@thetorpedodog here is the logic in question:
https://github.com/single-cell-data/TileDB-SOMA/blob/2fe22f86827f8dd2bae4b9001946d59dd3766fb0/apis/r/R/TileDBGroup.R#L164-L175

Here is a repro script

```
library(tiledbsoma)

uri <- '/var/s/v/ileum'
experiment <- SOMAExperimentOpen(uri)

cat("EXP          MODE:", experiment$mode(), "\n")
cat("EXP/MS       MODE:", experiment$ms$mode(), "\n")

exp_ms_rna <- experiment$ms$get('RNA')
cat("EXP/MS/RNA   MODE:", exp_ms_rna$mode(), "\n")

exp_ms_rna <- experiment$ms$get('RNA', 'WRITE')
cat("EXP/MS/RNA+W MODE:", exp_ms_rna$mode(), "\n")

experiment$close()
```

With the logic in question commented out we get

```
EXP          MODE: READ
EXP/MS       MODE: READ
EXP/MS/RNA   MODE: READ
EXP/MS/RNA+W MODE: READ
```

With the logic in question not commented out, i.e. as-is in the snippet linked to above, we get

```
EXP          MODE: READ
EXP/MS       MODE: READ
EXP/MS/RNA   MODE: READ
EXP/MS/RNA+W MODE: WRITE
```

Thoughts @thetorpedodog @mlin ? Have I mis-thought the API somehow with regard to implicit opens?

**Comment by thetorpedodog** [comment]
In the Python API, there is no way to open a sub-element in a different mode than the parent. This was how I had imagined the API contract in general; children are always in the same mode etc. as the parents. (Likewise, once you open a child once, getting it again will always return the same object.)

Is this present to support an existing use case?

**Comment by johnkerl** [comment]
@thetorpedodog the use-case is here -- before and after #1325:

* https://github.com/single-cell-data/TileDB-SOMA/blob/1ba0a95b6088a94d9e4657b39600f0ff46b86a36/apis/r/tests/testthat/test-SeuratOutgest-object.R#L16
* https://github.com/single-cell-data/TileDB-SOMA/blob/2fe22f86827f8dd2bae4b9001946d59dd3766fb0/apis/r/tests/testthat/test-SeuratOutgest-object.R#L14

**Comment by johnkerl** [comment]
@thetorpedodog @mlin I am thinking all of that could be:

* open experiment for write in the unit-test code
* inherit child mode from parent in `R/TileDBGroup.R`

?

**Comment by johnkerl** [comment]
> In the Python API, there is no way to open a sub-element in a different mode than the parent. This was how I had imagined the API contract in general; children are always in the same mode etc. as the parents. (Likewise, once you open a child once, getting it again will always return the same object.)

@thetorpedodog @mlin I'm rethinking `construct_member` in `R/SOMACollectionBase.R` as well as the above-linked snippet in `R/TileDBGroup.R` to reflect this understanding
