### ISSUE TITLE
[python] Promote some lifecycle tags from `experimental` to `maturing`

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1402]
Given we are now at 1.0 Python release.

Also relates to updating lifecycle tags from `experimental` to `maturing` in the downstream package `cellxgene-census`.

cc @bkmartinjr @pablo-gar

**Comment by bkmartinjr** [comment]
Opening bid: set all public *Python* tiledbsoma and somacore API to `maturing`.   

Please comment or counter this proposal: @johnkerl @aaronwolen @pablo-gar (and anyone else who has a viewpoint).

If you disagree with the bid, please specify which API you propose as not `maturing`

**Comment by johnkerl** [comment]
I'm in :)
