### ISSUE TITLE
[Bug] `tiledbsoma_stats_dump()` produces empty output

### ISSUE THREAD

**Issue by beroy** [single-cell-data/TileDB-SOMA#1410]
**Describe the bug**
tiledbsoma_stats_dump() produces empty ouput
**To Reproduce**
```
def test_stats(tmp_path, capsys: pytest.CaptureFixture[str]):
    """Make sure these exist, don't throw, and write correctly."""
    soma.tiledbsoma_stats_enable()
    soma.tiledbsoma_stats_reset()

    schema = pa.schema([("soma_joinid", pa.int64())])
    with soma.DataFrame.create(
        tmp_path.as_posix(),
        schema=schema,
        index_column_names=["soma_joinid"],
    ) as sidf:
        data = {
            "soma_joinid": [0],
        }
        sidf.write(pa.Table.from_pydict(data))

    with soma.DataFrame.open(tmp_path.as_posix()) as sidf:
        sidf.read().concat()

    **soma.tiledbsoma_stats_dump()**
    soma.tiledbsoma_stats_disable()
    stdout, stderr = capsys.readouterr()
    assert stdout != ""
    assert stderr == ""
    print(f"tiledbsoma_stats_dump() = {stdout}")
```
**This code produces:**
```
tiledbsoma_stats_dump() = libtiledb=2.15.2
[

]
```
Where as this code produces expected output:
```
   tmp = sys.stdout
   my_result = StringIO()
   sys.stdout = my_result
   **sidf._handle.context.tiledb_ctx.get_stats()**
   sys.stdout = tmp
   print(f"tiledb_ctx.get_stats() = {my_result.getvalue()}")
```
**Output:**
```
tiledbsoma_stats_dump() = None
tiledb_ctx.get_stats() = {
  "timers": {
    "Context.StorageManager.write_store_frag_meta.sum": 0.00225229,
    "Context.StorageManager.write_store_frag_meta.avg": 0.00225229,
...
```
**Versions (please complete the following information):**
Language and language version: Python 3.9
OS: MacOS
tiledbsoma.__version__        1.2.1.post11.dev179155028
TileDB-Py tiledb.version()    (0, 21, 1)
TileDB core version           2.15.0
libtiledbsoma version()       libtiledb=2.15.2
python version                3.9.16.final.0
OS version                    Darwin 22.4.0

**Comment by johnkerl** [comment]
@beroy please retry with a current `tiledbsoma` version (currently 1.2.4 is available via `pip install tiledbsoma`).

Using a current version, I get non-empty stats output (from the read): see for example
https://gist.github.com/johnkerl/eb72e61b697dc69c7f8f46ce717e8e5f

**Comment by johnkerl** [comment]
Also note that at this transitional point in time (see also #1240, which is an area of active development) we do creates and writes through `tiledb-py` whereas `libtiledbsoma` handles bulk reads but not all metadata reads etc.

This means that we get the read stats from the path tiledbsoma-py -> libtiledbsoma -> core, but the stats for the create and write from the path tiledbsoma-py -> tiledb-py -> core. In happiest dynamic-loader situations those two are the same copies of core, but, we found out some time ago that there are situations in which the two can be distinct. This is one of several reasons for #1240.

**Comment by beroy** [comment]
I checked one more time my setup and looks like I have the right version:
```
(venv-m1) brobatmili in ~/projects/TileDB-SOMA on main% pip list | grep tiledb
tiledb                   0.21.3
tiledbsoma               1.2.4
```

**Comment by johnkerl** [comment]
@beroy please try again `tiledbsoma.show_package_versions()` as in your original bug report.

**Comment by johnkerl** [comment]
For the record: we are 1-1'ing in Slack (quicker that way) and will update with information

**Comment by beroy** [comment]
Switching from 
```
oma.tiledbsoma_stats_enable()
soma.tiledbsoma_stats_dump()
```
to
```
tiledb.stats_enable()
tiledb.stats_dump()
```
Resolved the issue for me.
Quoting @johnkerl:
* soma.tiledbsoma_stats_dump()gets the tiledbsoma-py (Python) -> libtiledbsoma (C++) -> libtiledb/core (C++)
* tiledb.stats_dump() gets the tiledbsoma-py (Python) -> tiledb-py (Python) -> libtiledb/core (C++)
* Normally only a single copy of libtiledb gets loaded into memory by the dynamic loader, but, there are situations where there can be two (loooong saga -- I'm omitting details)
* By querying both you get both

Closing this issue

**Comment by johnkerl** [comment]
Reminder work here is tracked on #1240 

Another issue (for posterity):

* @beroy was seeing 1.2.1 from his `pytest`
* `pip install -U tiledbsoma` gave 1.2.4
* He kept seeing 1.2.1 from his `pytest`

Issue we debugged down to:

```
$ which python
/Users/brobatmili/projects/venv-m1/bin/python

$ which pip
/Users/brobatmili/projects/venv-m1/bin/pip

$ which pytest
/opt/homebrew/bin/pytest
```

Solution: invoke `python -m pytest` in place of `pytest` when working within `virtualenv`
