### ISSUE TITLE
[Bug] [r] Rccp's sr_setup/sr_next give segfault when qc/value_filter have no matches

### ISSUE THREAD

**Issue by pablo-gar** [single-cell-data/TileDB-SOMA#1420]
**Describe the bug**
When there is value filter that provides 0 matches, the sr_setup/sr_next workflow lead to seqfault

**To Reproduce**

```
devtools::load_all("./apis/r")
library(tiledbsoma)

ctx <- tiledbsoma::SOMATileDBContext$new(
   config = c("soma.init_buffer_bytes" = "300")
)
config <- as.character(tiledb::config(ctx$context()))

human_experiment = load_dataset("soma-exp-pbmc-small", tiledbsoma_ctx = ctx)

obs <- human_experiment$obs

# HERE IS THE VALUE FILTER THAT PROVIDES ZERO MATCHES
value_filter <-  "groups == 'does_not_exist'"

parsed <- do.call(what = tiledb::parse_query_condition,
                  args = list(expr = str2lang(value_filter), ta = obs))

value_filter <- parsed@ptr

sr <- sr_setup(uri = obs$uri, config = config, qc = value_filter)

sr_complete(sr)
# [1] FALSE

sr_next(sr)
# $array_data
# <pointer: 0x600001295770>
# 
# $schema
# <pointer: 0x600001296350>

sr_complete(sr)
# [1] FALSE

sr_next(sr)
#  *** caught segfault ***
# address 0x0, cause 'unknown'
```

**Comment by eddelbuettel** [comment]
Thanks -- I will take a closer look tomorrow at this query filter and reader interaction.

**Comment by pablo-gar** [comment]
@eddelbuettel Please make sure to bring back these tests:

https://github.com/single-cell-data/TileDB-SOMA/blob/ebce684b27eb1090d9fa63e742305d1518194256/apis/r/tests/testthat/test-SOMAExperiment-query.R#L231

**Comment by eddelbuettel** [comment]
The bug is / was simple to fix:  I hitherto had no ability to inquire (from `libtiledbsoma`'s `SOMA_Array` class) if we had the case where 'query status is incomplete BUT it is not the first query' yet internally that class has such a `bool`.  So I now export a check for that predicate and then all is well.   Quick run of (a slightly condensed version of) your example (or rather the key part of querying) :

```r
> sr <- sr_setup(uri = obs$uri, config = config, qc = parsed@ptr)
> sr_complete(sr)
[1] FALSE
> sr_next(sr)
$array_data
<pointer: 0x555ad85ead00>

$schema
<pointer: 0x555ad85edbd0>

> sr_complete(sr)
[1] FALSE
> sr_next(sr)
[[1]]
NULL

[[2]]
NULL

> sr_next(sr)
[[1]]
NULL

[[2]]
NULL

> 
```

So no more crash.  I wiill need a little more digging to see if I can get to the arrow schema when I don't have a query.  I am not yet sure if that works but the bug here is going to be addressed in a PR in a few mins.

**Comment by johnkerl** [comment]
> I wiill need a little more digging to see if I can get to the arrow schema when I don't have a query.

FWIW @nguyenv and I discussed this a few months ago on the Python side, and our conclusion at the time was that given API at the time, we could not, but more could (in principle) be plumbed through from core.

**Comment by eddelbuettel** [comment]
Well the predicate is there and I just enabled it.

**Comment by eddelbuettel** [comment]
> @eddelbuettel Please make sure to bring back these tests:

That is more work because we need to make sure the higher level functions deal with the current result.  I'll look into that next but one step at a time.

**Comment by eddelbuettel** [comment]
> @eddelbuettel Please make sure to bring back these tests:

#1426 does that using what #1422 changed
