### ISSUE TITLE
[Bug] ImportError: cannot import name 'LiteralString' from 'typing_extensions'

### ISSUE THREAD

**Issue by ccnawrocki** [single-cell-data/TileDB-SOMA#1436]
Hi, 
I am trying to install the package, yet I am running into problems. When I run: 
`import tiledbsoma as soma` in jupyter notebook in anaconda navigator, I get this error: 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-444e2341c2c8> in <module>
      5 import scipy as sp
      6 import tiledb
----> 7 import tiledbsoma as soma
      8 import tiledbsoma.io
      9 

/opt/anaconda3/lib/python3.8/site-packages/tiledbsoma/__init__.py in <module>
     97 # readthedocs table of contents.
     98 
---> 99 from somacore import AxisColumnNames, AxisQuery, ExperimentAxisQuery
    100 from somacore.options import ResultOrder
    101 

/opt/anaconda3/lib/python3.8/site-packages/somacore/__init__.py in <module>
     10 from typing import Tuple, Union
     11 
---> 12 from .base import SOMAObject
     13 from .collection import Collection
     14 from .data import DataFrame

/opt/anaconda3/lib/python3.8/site-packages/somacore/base.py in <module>
      8 from typing import Any, ClassVar, MutableMapping, Optional
      9 
---> 10 from typing_extensions import LiteralString, Self
     11 
     12 from . import options

ImportError: cannot import name 'LiteralString' from 'typing_extensions' (/opt/anaconda3/lib/python3.8/site-packages/typing_extensions.py)
```

What is going on?

I am using MacOS on an M1 mac.

**Comment by johnkerl** [comment]
@ccnawrocki sounds like you may have Python 3.7 -- ?

Can you please confirm by showing the output of `tiledbsoma.show_package_versions()`?

**Comment by johnkerl** [comment]
@ccnawrocki -- update -- I see `python3.8` in your `ipython` output above

**Comment by johnkerl** [comment]
@ccnawrocki while I'd still like to see the output of your `tiledbsoma.show_package_versions()` (at the Python prompt), can you also please send the output of `python -m pip show typing_extensions` (at the shell prompt)?

**Comment by ccnawrocki** [comment]
Running `tiledbsoma.show_package_versions()` gives me:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-b3501af4d33d> in <module>
----> 1 tiledbsoma.show_package_versions()

NameError: name 'tiledbsoma' is not defined

**Comment by ccnawrocki** [comment]
I'm sorry, but I do not really know what you mean by shell prompt vs python prompt

**Comment by ccnawrocki** [comment]
<img width="1119" alt="Screenshot 2023-05-31 at 5 26 37 PM" src="https://github.com/single-cell-data/TileDB-SOMA/assets/68296470/11c0b933-09c2-44d0-9c6d-b16f433c084c">

**Comment by johnkerl** [comment]
Sorry I wasn't more clear @ccnawrocki .

```
import tiledbsoma
tiledbsoma.show_package_versions()
```

and

```
! python3 -m pip show typing_extensions
```

**Comment by ccnawrocki** [comment]
If I run 
`import tiledbsoma`
`tiledbsoma.show_package_versions()`

I just get the same thing that I got in my first comment at the top of this thread. 

Next, 
<img width="1108" alt="Screenshot 2023-05-31 at 5 45 02 PM" src="https://github.com/single-cell-data/TileDB-SOMA/assets/68296470/6611441b-70d7-4786-bf0c-2ce59a40c149">

**Comment by ccnawrocki** [comment]
<img width="1106" alt="Screenshot 2023-05-31 at 5 47 17 PM" src="https://github.com/single-cell-data/TileDB-SOMA/assets/68296470/ee17524a-475a-42af-ae33-caf6c7afdc53">

**Comment by johnkerl** [comment]
@ccnawrocki when you wrote

> I am trying to install the package

-- how did you install the package? Using a Conda installer, a Mamba installer, a notebook command (if so, what?), or something else (if so, what?)?

**Comment by ccnawrocki** [comment]
Did the following: 

`conda install tiledbsoma'

**Comment by johnkerl** [comment]
@ccnawrocki where did you type that -- in a terminal window / shell prompt / iTerm / something similar? Or via `! conda install tiledbsoma` within your notebook? Or something else?

**Comment by ccnawrocki** [comment]
In my notebook

**Comment by johnkerl** [comment]
Thanks @ccnawrocki ! Let me circle back with the team and get back to you with a plan to unblock the conflicting versions.

**Comment by johnkerl** [comment]
@ccnawrocki our plan is to suggest that you do

```
conda install "typing_extensions>=4.1" 
```

Can you try this and let me know how it works for you?

**Comment by ccnawrocki** [comment]
<img width="1114" alt="Screenshot 2023-06-01 at 3 29 06 PM" src="https://github.com/single-cell-data/TileDB-SOMA/assets/68296470/c6ff1089-13f0-418f-b5a7-a7c205412609">

I got this. I restarted the kernel and tried again, but it did not change anything.

**Comment by ccnawrocki** [comment]
Sounds good. I am in the slack. What now?

**Comment by johnkerl** [comment]
(Following up in Slack)

**Comment by johnkerl** [comment]
Moving forward the install command is `conda install tiledbsoma-py`

**Comment by johnkerl** [comment]
Resolved in https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/25
