### ISSUE TITLE
[Bug] [r] `SOMASparseNDArray$read()$sparse_matrix()$concat()` error on empty array

### ISSUE THREAD

**Issue by mlin** [single-cell-data/TileDB-SOMA#1441]
While working #1429 we wrote a test case involving reading a newly-created, *empty* 2x2 SOMASparseNDArray. Using `read()$sparse_matrix()$concat()` on it produced this error:

```
  ── Error ('test-SOMACollection.R:99:3'): SOMACollection timestamped ops ────────
  Error in `Matrix::sparseMatrix(i = soma_dim_0_one_based, j = soma_dim_1_one_based, 
      x = soma_data, dims = shape, repr = repr)`: all(dims >= dims.min) is not TRUE
  Backtrace:
      ▆
   1. └─collection$get("A")$read()$sparse_matrix()$concat() at test-SOMACollection.R:99:2
   2.   └─self$read_next()
   3.     └─private$soma_reader_transform(rl)
   4.       └─tiledbsoma:::arrow_table_to_sparse(...)
   5.         └─Matrix::sparseMatrix(...)
   6.           └─base::stopifnot(all(dims >= dims.min))
```

Strangely, this error arose only in GHA CI, not on our local machines.

The test setup involved timestamped operations, but I *suspect* it's probably an edge-case bug with empty result sets or empty arrays, not specific to time travel.

**Comment by johnkerl** [comment]
@pablo-gar including in this sprint, but as lower-pri

**Comment by pablo-gar** [comment]
A reproducible example would help here. I've tried unsuccessfully to reproduce.

@mlin
