### ISSUE TITLE
[r] Update `SOMAReader` to support passing Arrow arrays to `coords`

### ISSUE THREAD

**Issue by aaronwolen** [single-cell-data/TileDB-SOMA#1479]
```r
library(tiledbsoma)
library(arrow)    # missing r added
uri <- extract_dataset("soma-dataframe-pbmc3k-processed-obs")

coords <- arrow::as_arrow_array(c(1000L, 1004L), type = arrow::int64())
soma_array_reader(
  uri = uri,
  dim_points = list(
    soma_joinid = coords
  )
)

## Error: Not compatible with requested type: [type=environment; target=double].
## Execution halted
```

Follow-up from https://github.com/single-cell-data/TileDB-SOMA/pull/1478#discussion_r1232534976

**Comment by eddelbuettel** [comment]
`coords` expects a `List` and is a compiled function so it doesn't have that much flexibility.  A simple approach would be to access the columns matching the dims and placing the into a list.  Good enough?

**Comment by johnkerl** [comment]
@eddelbuettel (and cc @nguyenv) just on the `pybind11` side over from `libtiledbsoma` we do accept `coords` as Arrow from Python:
https://github.com/single-cell-data/TileDB-SOMA/blob/1.2.5/apis/python/src/tiledbsoma/pytiledbsoma.cc#L277

So Arrow in Python -> Arrow in `pybind11` -> C++ templated buffer-pointers to `libtiledbsoma`

Not sure at what level we can do that conversion in R -> Rcpp -> `libtiledbsoma`

**Comment by eddelbuettel** [comment]
> A simple approach would be to access the columns matching the dims and placing the into a list.

If you can factor out better automagic logic from pybind11 I would be all ears.

**Comment by eddelbuettel** [comment]
I missed that Arrow object is a simple vector.  I think a simple 'if arrow use as_vector' inside the function will do:

```r
soma_array_reader(uri=uri, dim_points=list(soma_joinid=coords$as_vector()))   
```

works.  While at we probably also want to ensure the `list` is named because this is ugly too:

```
> soma_array_reader(uri=uri, dim_points=list(1:10))
Error: Expecting a string vector: [type=NULL; required=STRSXP].
> 
```

**Comment by eddelbuettel** [comment]
Ok, I have a minimal changeset that does just that: move the access point to R, do a few tests on parameters and if `dim_points` has an Arrow Table object, convert it.

```r
> library(tiledbsoma)
> library(arrow)    # missing r added

Attaching package: ‘arrow’

The following object is masked from ‘package:utils’:

    timestamp

> uri <- extract_dataset("soma-dataframe-pbmc3k-processed-obs")
> coords <- arrow::as_arrow_array(c(1000L, 1004L), type = arrow::int64())
> sar <- soma_array_reader(uri, dim_points=list(soma_joinid=coords))
> str(sar)
List of 2
 $ array_data:<externalptr> 
 $ schema    :<externalptr> 
> 
```

That would keep all other interfaces 'as is' and of course passes tests.  We could of course do more here (_e.g_ not return a bare list as we did from the underlying C++ function, maybe switch to passing a `query_condition` object in rather than a pointer, ...) but as a first pass it felt more prudent to minimize change.
