### ISSUE TITLE
[r] Publish tiledbsoma on CRAN

### ISSUE THREAD

**Issue by mlin** [single-cell-data/TileDB-SOMA#1515]
Follow-up from #1427

All agree we should publish tiledbsoma on CRAN to make installation as simple as possible for users and dependent packages. There were some differing opinions on *when* we should begin publishing on CRAN (how mature we should be) given that the CRAN maintainers may frown on updating packages there too frequently. In the meantime we're publishing through r-universe (configured to track GitHub Releases).

This ticket is to decide when it's the appropriate time for CRAN, write down the "procedure" in doing so, and update the readme to point users there instead of r-universe.

**Comment by mojaveazure** [comment]
One thing to note about CRAN: packages are required to be [cross-platform](https://cran.r-project.org/web/packages/policies.html)

> Package authors should make all reasonable efforts to provide cross-platform portable code

Exceptions can be made (à la [{unix}](https://cran.r-project.org/package=unix)), but I believe CRAN's preference is for all packages to work on Windows, macOS, and a few flavors of Linux (Debian and Fedora)

@eddelbuettel please correct me if I'm wrong

**Comment by eddelbuettel** [comment]
Like many things that is a _preference_ and a desire.  We do build on two common platforms, that should be good enough.  DESCRIPTION has a field OS_type with value 'unix' for a few packages.  So that is not a blocker.

**Comment by johnkerl** [comment]
@eddelbuettel should this now be closed in favor of #1582?

**Comment by eddelbuettel** [comment]
@johnkerl I will leave the juggling of overlapping / partily redundant issue tickets in your capable hands.  Works for me either way, you may want to consult with @mlin too before closing / merging / extending.

**Comment by mlin** [comment]
@johnkerl @eddelbuettel No objection to merging. Comparing the tickets, it looks to me like the only extra items noted in this one are (1) update our written release procedures to reflect publishing to CRAN and (2) update the user-facing readme/docs to refer to CRAN instead of r-universe. Perhaps obvious but certainly part of the scope.
