### ISSUE TITLE
[r] Slow export of obsm/varm arrays to Seurat

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1518]
As discussed 1-1 with @aaronwolen in Slack today -- @aaronwolen please fill out details

**Comment by aaronwolen** [comment]
As part of #1504 `SOMAExperimentAxisQuery$to_seurat_graph()` was updated to leverage the newer `to_sparse_matrix()` method and avoid creating CsparseMatrix objects with large dimensions, which is computationally expensive.

These changed need to be carried through to `to_seurat_reduction()` to avoid the same problem, which @johnkerl encountered in CI [here](https://github.com/single-cell-data/TileDB-SOMA/pull/1440#issuecomment-1614953938).

**Comment by aaronwolen** [comment]
Fixed in #1521
