### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mtmorgan** [single-cell-data/TileDB-SOMA#1520]
**Describe the bug**

this https://github.com/single-cell-data/TileDB-SOMA/blob/7ef6948af340c72fb85a2bb0b103389edfbb7ebd/apis/r/R/SOMAExperimentAxisQuery.R#L208 endpoint on **GitHub Actions** leads to an error
```
to_sparse_matrix(collection, layer): attempt to apply non-function
```
but succeeds in my local session. It seems like `read()`, e.g., here? https://github.com/single-cell-data/TileDB-SOMA/blob/7ef6948af340c72fb85a2bb0b103389edfbb7ebd/apis/r/R/SOMAExperimentAxisQuery.R#L281 sometimes lead to an iterator, and sometimes to a realized object where invoking a function (`$tables()$concat()`) makes no sense.

This is similar to other scenarios in code that I have more control over where a `read()` command on GitHub Actions returns the fully realized object, whereas locally produces an object that needs to be, e.g., `concat()`enated. This lead me to write code like
```
    tbl <- census$get("census_info")$get("datasets")$read()
    if (inherits(tbl, "ReadIter"))
        tbl <- tbl$concat()
```

This might be relaed to
https://github.com/single-cell-data/TileDB-SOMA/issues/1441

**To Reproduce**
Unfortunately I do not have an easily reproducible example. The actual test case is from the help page https://github.com/mtmorgan/CxGcensus/blob/main/man/census_info.Rd with the behavior seen in GitHub Action / pkgdown rendered help page https://mtmorgan.github.io/CxGcensus/reference/census_info.html, specifically
```
counts <- assay_data(features, observations, organism = "mus_musculus")
#> creating axis and experiment queries
#> retrieving assay_data measurement 'RNA' collection 'X' layer 'raw' as a
#> sparse matrix with 2 x 2 distinct features x observations
#> Error in experiment_query$to_sparse_matrix(collection, layer): attempt to apply non-function
```

**Versions (please complete the following information):**

My local machine has
```
> tiledbsoma::show_package_versions()
tiledbsoma:    0.0.0.9030
tiledb-r:      0.19.1.8
tiledb core:   2.15.2
libtiledbsoma: libtiledb=2.15.2
R:             R version 4.3.0 Patched (2023-05-01 r84362)
OS:            macOS Monterey 12.6.7
```
The GitHub action reports:
```
tiledbsoma::[show_package_versions](https://rdrr.io/pkg/tiledbsoma/man/show_package_versions.html)()
#> tiledbsoma:    0.0.0.9024
#> tiledb-r:      0.19.1
#> tiledb core:   2.15.2
#> libtiledbsoma: libtiledb=2.15.2
#> R:             R version 4.3.1 (2023-06-16)
#> OS:            Ubuntu 22.04.2 LTS
```

**Comment by eddelbuettel** [comment]
Here tiledbsoma 0.0.0.9024 is solidly behind.  You need to check the repo out, build the C++ library (the R package falls back for you on that).  Or just take 0.0.0.9030 from r-universe repo [that has it](https://eddelbuettel.r-universe.dev/tiledbsoma).

You are caught a little between us trying to standardize release processes ... before we have a 1.0 release.

**Comment by johnkerl** [comment]
@mtmorgan thanks for reporting! I do indeed suspect that 0.0.0.9030 is the answer, as we're approaching, but not yet arrived at, an R release, and the R package is in some last flux.

@mlin can you take a look as well please?

**Comment by mlin** [comment]
@mtmorgan While (as @eddelbuettel alluded above) we're still finalizing the R tiledbsoma release versioning, the following example may be useful:

https://github.com/chanzuckerberg/cellxgene-census/blob/33084b8f1ed98b9f8504dee2b23b52e82aa8f6cf/.github/workflows/r-check.yml#L19-L28

The idea is to use the setup-r-dependencies GHA as usual, then circle back to explicitly install the very latest version directly from github. This is considered a temporary workaround, hopefully for just a few weeks until we have a release [candidate] package.

**Comment by mtmorgan** [comment]
Thanks everyone, once I saw the version mismatch (when creating the issue, of course!) I should have been able to figure this out myself.

The 0.0.0.9024 is coming from https://tiledb-inc.r-universe.dev/tiledbsoma ; I had added
```
Additional_repositories: https://tiledb-inc.r-universe.dev
```
to the DESCRIPTION file.
