### ISSUE TITLE
[Feature request] ExperimentAxisQuery read methods should expose batch_size and result_order params

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#1527]
The current read methods (`X()`, etc) on `ExperimentAxisQuery` do not accept the common `read()` arguments which control ordering, etc. This reduces their utility when the user wants (for example) query results on X array to be returned in row-order.

Asks for ExperimentAxisQuery.X, .var and .obs:  add at least add `result_order` and `batch_size` arguments, but ideally also `partitions` and `platform_config`

This is a low-effort change that would greatly increase the query utility.

Edit by @pablo-gar 

- [x] Python API exposes `result_order` and `batch_size`
- [ ] R API exposes `result_order`

**Comment by pablo-gar** [comment]
@johnkerl let's consider this for our next sprint.

**Comment by ayushnoori** [comment]
Thanks for the feature request, @bkmartinjr!

**Comment by pablo-gar** [comment]
Re opening because we still need an R implementation
