### ISSUE TITLE
[Bug][r] SOMAExperimentAxisQuery drops numeric query coordinates

### ISSUE THREAD

**Issue by mtmorgan** [single-cell-data/TileDB-SOMA#1537]
**Describe the bug**
In R, numeric soma joinids are (mostly) silently dropped when creating a SOMAExperimentAxisQuery. Numeric joinids should either be coerced to an appropriate type, or generate an error.

**To Reproduce**
Create a `SOMAAxisQuery` with integer or numeric coordinates
```{r}
expt <- tiledbsoma::load_dataset("soma-exp-pbmc-small")
integer_query <- tiledbsoma::SOMAAxisQuery$new(coords = 1:2)
numeric_query <- tiledbsoma::SOMAAxisQuery$new(coords = c(1, 2))
expt_query <- tiledbsoma::SOMAExperimentAxisQuery$
    new(expt, "RNA", var_query = integer_query, obs_query = numeric_query)
```
The `var_joinids()` (integer values) are as expected
```{r}
> expt_query$var_joinids() # expected -- [1, 2]
Array
<int64>
[
  1,
  2
]
```
but the `obs_joinids()` (numeric values) are not -- only the numeric value `0` maps correctly
```{r}
> expt_query$obs_joinids() # unexpected -- []
Array
<int64>
[]
```
**Versions (please complete the following information):**

```{r}
> tiledbsoma::show_package_versions()
tiledbsoma:    0.99.0
tiledb-r:      0.20.0
tiledb core:   2.16.0
libtiledbsoma: libtiledb=2.16.0
R:             R version 4.3.0 Patched (2023-05-01 r84362)
OS:            macOS Monterey 12.6.7
```
**Additional context**
None

**Comment by eddelbuettel** [comment]
Thanks for report, Martin. (And do feel free to more expressive in your Subject: or Issue: title than the minimalistic `[Bug]`).

We do indeed fail to cover and convert from `numeric` aka double.  If you are explicit all is well:

```r
> numeric_query <- tiledbsoma::SOMAAxisQuery$new(coords = bit64::as.integer64(c(1, 2)))
> expt_query <- tiledbsoma::SOMAExperimentAxisQuery$new(expt, "RNA", var_query = integer_query, obs_query = numeric_query)
> expt_query$obs_joinids()
Array
<int64>
[
  1,
  2
]
> 
```

**Comment by aaronwolen** [comment]
Thanks for the helpful reprex!

I'm thinking we should throw a warning if the user passes a double to `coords` and then coerce it to an integer. We could also use `rlang::is_integerish()` to verify the input is integer-like but that seems like overkill.

We could also take this opportunity to update our [internal function](https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/r/R/utils-assertions.R#L91) for validating coordinates to support non-numeric coordinates _and_ verify the type of each coordinate vector is compatible with the corresponding dimension's type.

Currently it only performs some basic sanity checks and assumes the underlying tiledb array is indexed by ints, which is the default but [not necessarily the case](https://github.com/single-cell-data/SOMA/blob/063aef6a32530c2f2730c73942490d3fc55916d3/abstract_specification.md?plain=1#L621).
