### ISSUE TITLE
[r] Support enumerations

### ISSUE THREAD

**Issue by eddelbuettel** [single-cell-data/TileDB-SOMA#1558]
**Is your feature request related to a problem? Please describe.**

TileDB 2.17 will bring enumerations support.  The SOMA project is eager to take advantage of this. Parent issue: #866

**Describe the solution you'd like**

A branch contains development, conditional on 2.17, to read enumerations and return them.  Preliminary write support (going via tiledb-r) is also implemented.

**Describe alternatives you've considered**

N/A

**Additional context**

#866

**Comment by johnkerl** [comment]
Closing in favor of #866
