### ISSUE TITLE
[r] Look into recent pkgdown CI failures

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1598]
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/5869924262

Needs triage.

**Comment by eddelbuettel** [comment]
Line 41:
> Error: Error in loadNamespace(x) : there is no package called ‘httr’

Aren't you installing packages from a fixed list?  Looks like httr needs to be added.

**Comment by johnkerl** [comment]
@eddelbuettel not "I" but "we"

I'll look, thanks

And if you see the fix (you know R packaging better than I) please feel free to propose a concrete fix

**Comment by eddelbuettel** [comment]
> not "I" but "we"

Not exactly we as "we" do this differently in eg tiledb-r.  I find actions difficulet to debug and try my best to minimize their complexity. Running pkgdown locally and pushing the files as needed works for me, but it is clearly less 'street-cred cool'.

> would this be as simple as adding an httr line to Suggests in apis/r/DESCRIPTION?

I do not think so as it would affect standard CI too.  But you could try tossing it into the script you appear to have written for this: https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/r/tools/install-pkgdown-dependencies.sh

As for debugging, I usually start with a quick Docker container locally and usually get to the bottom.  There are newer tools like https://github.com/nektos/act (in `go`) to run actions locally but I have not used or tried it.

**Comment by eddelbuettel** [comment]
Had another look, it is something else. (CRAN package) `curl` now fails, I think `httr` depends on.  So you need to look into why this fails (this uses PPM/RSPM which I am less familiar with so cannot help much -- an additional `sudo apt` may help, you could also considers binaries etc)

![image](https://github.com/single-cell-data/TileDB-SOMA/assets/673121/d9ff36c7-d36f-4d3f-96aa-b933b1f8f283)

It could also be temporary if the installer saw a newer curl _source_ package than a binary and attempted (and then failed) to install from source.  In that case it would magically go away once the binary has been made.  This seems likely, I just checked https://cloud.r-project.org/web/packages/curl/index.html and a new one came out yesterday.

The bigger meta question is how to tell the installer to not try a source installation.  For the way you have chose (via RSPM/PPM I do not know the answer) I sadly do not know the answer.
![image](https://github.com/single-cell-data/TileDB-SOMA/assets/673121/2ebee3d0-3517-4709-923a-08cba6c1bacb)

![image](https://github.com/single-cell-data/TileDB-SOMA/assets/673121/abf51cf1-c317-4637-b19d-53690b60295d)

**Comment by eddelbuettel** [comment]
Had one more idea and checked the 'action' (that I don't really use myself) and it would appear it does not have a variable to prefer binary (even if older) over source.

https://github.com/r-lib/actions/tree/v2-branch/setup-r

Not sure what to suggest here.  You got bitten by CI flakyness.

**Comment by johnkerl** [comment]
Thanks @eddelbuettel !

**Comment by eddelbuettel** [comment]
As suspected [in this comment above](https://github.com/single-cell-data/TileDB-SOMA/issues/1598#issuecomment-1679482767) this was actually spurious as seen in this most recent run of the action:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/5869924262

So closing this. Feel free to reopen if it dies another times, and we can always consider a possibly more robust setup.
