### ISSUE TITLE
R - Cannot compile [Bug]

### ISSUE THREAD

**Issue by alwhiteh** [single-cell-data/TileDB-SOMA#1599]
Hello,

I'm trying to install TileDB-SOMA in R 4.1 (non-ARM version) on my M1 Mac. I have tried installing the package using both: 
`install.packages('tiledbsoma', repos = c('https://tiledb-inc.r-universe.dev',
                                         'https://cloud.r-project.org'))`
and 
`remotes::install_github("https://github.com/single-cell-data/TileDB-SOMA", 
                        subdir = "apis/r", dependencies = T)`
but I keep encountering the following compilation error:

```
`* installing *source* package ‘tiledbsoma’ ...
** using staged installation
Error: No 'cmake' binary found
Execution halted
./configure: line 47: tools/build_libtiledbsoma.sh: No such file or directory
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I. -I../inst/include/ -I../inst/tiledb/include -I../inst/tiledbsoma/include  -mmacosx-version-min=10.14 -I'/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.1/x86_64-apple-darwin17.0/Rcpp/include' -I'/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.1/x86_64-apple-darwin17.0/RcppSpdlog/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
./../inst/include/tiledbsoma_types.h:21:10: fatal error: 'tiledbsoma/tiledbsoma' file not found
#include <tiledbsoma/tiledbsoma>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘tiledbsoma’
* removing ‘/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.1/x86_64-apple-darwin17.0/tiledbsoma’

The downloaded source packages are in
	‘/private/var/folders/_m/v1nsm3ws5fnbp4jb9wc69p5w0000gn/T/Rtmpf9Dy2K/downloaded_packages’
Warning messages:
1: In readRDS(dest) : lzma decoder corrupt data
2: In utils::install.packages("tiledbsoma", repos = c("https://tiledb-inc.r-universe.dev",  :
  installation of package ‘tiledbsoma’ had non-zero exit status`
```

I tried installing cmake with homebrew, but R doesn't seem to recognize it. Is this the issue? 

Any help would be greatly appreciated!

My session info:

```
`R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 13.4.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1] SingleCellExperiment_1.16.0 SummarizedExperiment_1.24.0 Biobase_2.54.0              GenomicRanges_1.46.1        GenomeInfoDb_1.30.1        
 [6] IRanges_2.28.0              S4Vectors_0.32.4            BiocGenerics_0.40.0         MatrixGenerics_1.6.0        matrixStats_1.0.0          

loaded via a namespace (and not attached):
 [1] lattice_0.21-8         bitops_1.0-7           grid_4.1.2             zlibbioc_1.40.0        XVector_0.34.0         renv_1.0.2            
 [7] curl_5.0.0             remotes_2.4.2.1        Matrix_1.5-1           tools_4.1.2            RCurl_1.98-1.12        DelayedArray_0.20.0   
[13] compiler_4.1.2         BiocManager_1.30.22    GenomeInfoDbData_1.2.7`

```

**Comment by eddelbuettel** [comment]
The `Error: No 'cmake' binary found` comes from R running `Sys.which("cmake")`.  I am not a macOS user so I am not really sure of homebrew puts this in a different path from the one you use with R.  But I am fairly certain that among the developers we also have folks with non-Intel macs who have built this.  Let me see if I can get someone for you.

**Comment by johnkerl** [comment]
@alwhiteh I would suggest `brew install cmake`

**Comment by johnkerl** [comment]
@alwhiteh I would suggest `brew install cmake`

**Comment by alwhiteh** [comment]
Hi @johnkerl and @eddelbuettel ,

Thanks for the quick replies! 

I had already installed cmake via homebrew - When I run the install command, R doesn't seem to be able to call cmake. 

When I tried:

```
# Install tiledbsoma in R:
install.packages('tiledbsoma', repos = c('https://chanzuckerberg.r-universe.dev', 'https://cloud.r-project.org'))
```

I got the same cmake error:

```
* installing *source* package ‘tiledbsoma’ ...
** using staged installation
Error: No 'cmake' binary found
Execution halted
./configure: line 47: tools/build_libtiledbsoma.sh: No such file or directory
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I. -I../inst/include/ -I../inst/tiledb/include -I../inst/tiledbsoma/include  -mmacosx-version-min=10.14 -I'/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.1/x86_64-apple-darwin17.0/Rcpp/include' -I'/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.1/x86_64-apple-darwin17.0/RcppSpdlog/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
./../inst/include/tiledbsoma_types.h:21:10: fatal error: 'tiledbsoma/tiledbsoma' file not found
#include <tiledbsoma/tiledbsoma>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘tiledbsoma’
```

I then tried the command with the type = "binary", but was told that a binary didn't exist for my version of R:
```

> # Install tiledbsoma in R:
> install.packages('tiledbsoma', 
+                  repos = c('https://chanzuckerberg.r-universe.dev', 
+                            'https://cloud.r-project.org'),
+                  type = "binary")
Installing package into ‘/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.1/x86_64-apple-darwin17.0’
(as ‘lib’ is unspecified)

   package ‘tiledbsoma’ is available as a source package but not as a binary

Warning messages:
1: In readRDS(dest) : lzma decoder corrupt data
2: package ‘tiledbsoma’ is not available as a binary package for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```

**Comment by johnkerl** [comment]
@alwhiteh my apologies! I see you had already tried to brew-install cmake.

This sounds like a path issue. A few things to suggest:

* Are you running the above `install.packages` in a command-line invocation launched from the shell, or RStudio, or elsewhere?
* Can you please run `which cmake` at your shell and send us the output?
* Can you please run `Sys.which("cmake")` at your R prompt and send us the output?

Context: older `brew` installed to `/usr/local/bin/cmake` and that is commonly in people's `$PATH`. Newer `brew` installs to `/opt/homebrew/bin/cmake` and this may be less likely to be in your `$PATH`.

**Comment by johnkerl** [comment]
(Also helpful may be `Sys.getenv('PATH')` in an R session.)

**Comment by alwhiteh** [comment]
@johnkerl,

I checked my $PATH variable in terminal and my homebrew path `(/opt/homebrew/bin)` is listed. The same output was echoed when I ran `Sys.getenv('PATH')` from Rstudio.

I'm running install.packages from Rstudio.

My cmake path is listed as: `/opt/homebrew/bin/cmake`

And when I run Sys.which("cmake") in Rstudio, I get: 
```
cmake 
   "" 
```

**Comment by johnkerl** [comment]
@alwhiteh OK I see:

```
> Sys.which('cmake')
                 cmake
"/usr/local/bin/cmake"
```

at my R prompt so I think we just need to get `/opt/homebrew/bin` into your RStudio's `PATH`.

**Comment by alwhiteh** [comment]
@johnkerl For whatever reason, none of my homebrew packages are showing up through `sys.which`. I'm going to try installing cmake with conda ( just as soon as my environment gets solved...)

**Comment by eddelbuettel** [comment]
@alwhiteh Stepping back a little, the existence of binaries should free you from having to worry about `cmake` (and `git` after that).  You should be able to go the r-universe site (link is above) and (manually) download `tiledbsoma_1.4.2.tgz` to, say, `/tmp` and then install it _by setting the repos= argument to NULL_ ie in

```r
install.package("/tmp/tiledbsoma_1.4.2.tgz", repos=NULL)
```

**Comment by alwhiteh** [comment]
@eddelbuettel I realized that there wasn't a package on the r-universe site for R 4.1, so I installed 4.3 using rig and re-initialized the project. When I try to run the command you listed, I get the following error:

```
Error: file ‘/tmp/tiledbsoma_1.4.2.tgz’ is not a macOS binary package
In addition: Warning message:
'tar' returned non-zero exit code 1 
```
I wasn't sure if the package needed to be uncompressed, so I tried re-running the code with a path to the  expanded folder:

`install.packages("/tmp/tiledbsoma/", repos=NULL)`

but this didn't work either:

```
Error in utils::install.packages("/tmp/tiledbsoma/", repos = NULL) : 
  type == "both" cannot be used with 'repos = NULL'

```
I have never installed packages this way, so I apologize if I'm missing something obvious. 

Thanks for the help!

-Alex

**Comment by eddelbuettel** [comment]
@alwhiteh My apologies -- as my collegue Seth by now pointed out to me, you are on R 4.1.* which is by now a little dated. Consequently r-universe provides binaries only for both R 4.2.* and R 4.3.*.  You cannot force-install those.

So you would have to update your installation to a more current R, which may or may not be to your liking, or compile completely from source (or rely completely on Conda).  How to do this is documented on our project site, but it is a little bit involved as you will need a few components.  That said, `cmake` and `git` will take care of that once you add them to your $PATH.  I would recommend doing so at your shell level and not just within RStudio.  

Now, if I may, I would also caution you about not mixing Conda and standard R binaries and tools. I have seen that lead to tears in the context of other projects.  (You could however also install your R from Conda and trust it fully, or use Docker.)   Lastly, when compiling from source for R on macOS, the macOS maintainer for R recommends the toolchain provided by R, see [the macOS page for R devs](https://mac.r-project.org/) for more.  I am sorry I cannot offer more direct or simpler instruction but r-universe is a third-party best-efforts project too and we understand why I cannot offer R 4.1.* when it already covers R 4.2.* and R 4.3.*.

**Comment by alwhiteh** [comment]
Hi @eddelbuettel,

I tried your suggestion with an install of R 4.3, but was unsuccessful. Please see above.

**Comment by alwhiteh** [comment]
Hi @eddelbuettel,

No problem, I totally understand that not every version, especially older versions will be supported. 

I installed R 4.3 (the x86-64 version, the ARM version wouldn't install either). The good news is that I'm able to install the package either through the r-universe repo or by directly installing the package. 

The bad news is that whenever I try to load the package with `library(tiledbsoma)`, R crashes. Do you have any idea why this might be?

**Comment by eddelbuettel** [comment]
Hi @alwhiteh -- I can only guess but it may be that one of components we compile to build the C++ library powering `tiledbsoma` may be built in a way that is not compatible with your use of x86_64-when-it-really-is-arm64.  From a distance I was under the understanding that the 'Rosetta2' layer covered everything, maybe this is an exception. 

My colleagues may have to speak to this but I do believe buiding form arm64 on arm64 works.

**Comment by johnkerl** [comment]
Thanks @eddelbuettel ! @alwhiteh indeed there are many users on Mac x86 as well as ARM (I use both). However I'm not familiar with the details of non-ARM software on ARM hardware.

> I installed R 4.3 (the x86-64 version, the ARM version wouldn't install either)

@alwhiteh can you share the error messages you encountered?

> The bad news is that whenever I try to load the package with library(tiledbsoma), R crashes. Do you have any idea why this might be?

Here too can you please share a copy/paste (or screenshot) of the crash information?

**Comment by alwhiteh** [comment]
@johnkerl 

When I try to install the package using the R 4.3.1 ARM on my ARM machine using:
`install.packages('tiledbsoma', repos = c('https://chanzuckerberg.r-universe.dev', 'https://cloud.r-project.org'), binary = T)
`
I get the following error:
```
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[6]: *** [src/libtiledbsoma.dylib] Error 1
make[5]: *** [src/CMakeFiles/tiledbsoma.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [CMakeFiles/install-libtiledbsoma] Error 2
make[2]: *** [CMakeFiles/install-libtiledbsoma.dir/all] Error 2
make[1]: *** [CMakeFiles/install-libtiledbsoma.dir/rule] Error 2
make: *** [install-libtiledbsoma] Error 2
** libs
using C compiler: ‘Apple clang version 14.0.3 (clang-1403.0.22.14.1)’
using C++ compiler: ‘Apple clang version 14.0.3 (clang-1403.0.22.14.1)’
using C++17
using SDK: ‘MacOSX13.3.sdk’
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/include" -DNDEBUG -I. -I../inst/include/ -I../inst/tiledb/include -I../inst/tiledbsoma/include   -I'/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.3/aarch64-apple-darwin20/Rcpp/include' -I'/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.3/aarch64-apple-darwin20/RcppSpdlog/include' -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
./../inst/include/tiledbsoma_types.h:21:10: fatal error: 'tiledbsoma/tiledbsoma' file not found
#include <tiledbsoma/tiledbsoma>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘tiledbsoma’
* removing ‘/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.3/aarch64-apple-darwin20/tiledbsoma’

The downloaded source packages are in
	‘/private/var/folders/_m/v1nsm3ws5fnbp4jb9wc69p5w0000gn/T/RtmpnNVp4f/downloaded_packages’
Warning message:
In utils::install.packages("tiledbsoma", repos = c("https://chanzuckerberg.r-universe.dev",  :
  installation of package ‘tiledbsoma’ had non-zero exit status
```
If I install it using the downloaded package from r-universe, it seems to install ok, but when I run library(tiledbsoma) , 

I get this error pops up twice:

<img width="236" alt="image" src="https://github.com/single-cell-data/TileDB-SOMA/assets/56940915/3f8dce86-5487-4b7f-9085-d2e480f8fd77">

Once I go into system preferences and click "Allow Anyway", this error is left in the Rstudio terminal:

```
Error: package or namespace load failed for ‘tiledbsoma’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.3/x86_64-apple-darwin20/tiledbsoma/libs/tiledbsoma.so':
  dlopen(/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.3/x86_64-apple-darwin20/tiledbsoma/libs/tiledbsoma.so, 0x0006): tried: '/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.3/x86_64-apple-darwin20/tiledbsoma/libs/tiledbsoma.so' (code signature in <9FE89899-42A3-3F6D-A90F-8966F931A3AE> '/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.3/x86_64-apple-darwin20/tiledbsoma/libs/tiledbsoma.so' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.3/x86_64-apple-darwin20/tiledbsoma/libs/tiledbsoma.so' (no such file), '/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/libra
```
Then I tried running `library(tiledbsoma)` again, but encountered this error:
<img width="227" alt="image" src="https://github.com/single-cell-data/TileDB-SOMA/assets/56940915/e1f85435-cb0f-44c3-9fbe-9a8bbcea389d">

```
Error: package or namespace load failed for ‘tiledbsoma’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.3/x86_64-apple-darwin20/tiledbsoma/libs/tiledbsoma.so':
  dlopen(/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.3/x86_64-apple-darwin20/tiledbsoma/libs/tiledbsoma.so, 0x0006): Library not loaded: @rpath/libtiledb.dylib
  Referenced from: <9FE89899-42A3-3F6D-A90F-8966F931A3AE> /Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.3/x86_64-apple-darwin20/tiledbsoma/libs/tiledbsoma.so
  Reason: tried: '$ORIGIN/../tiledb/lib/libtiledb.dylib' (no such file), '$ORIGIN/../tiledbsoma/lib/libtiledb.dylib' (no such file), '/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R-4.3/x86_64-apple-darwin20/tiledbsoma/libs/../tiledb/lib/libtiledb.dylib' (code signature in <52CFB3AF-1D0C-3B74-A140-C15979B66761> '/Users/alexwhitehead/Documents/Postdoc/CZI_DLs/renv/library/R
```
I repeated the "Allow Anyway" process and tried the `library` command again, this time getting:
<img width="248" alt="image" src="https://github.com/single-cell-data/TileDB-SOMA/assets/56940915/a1869d91-886c-4a7d-9bf8-9c0908a33b36">

I rinsed and repeated, and this time when I ran the library command, Rstudio crashed:

<img width="409" alt="image" src="https://github.com/single-cell-data/TileDB-SOMA/assets/56940915/d07c798b-d15c-43bf-8682-ec5c5929b40b">


Since the error messages seemed to be trying to call x86_64 versions of the dependencies, I tried again using the x86_64 version of R, but ran into the same unidentified developer problems and Rstudio crashes when installing the package directly on the ARM build. Does that make sense?

**Comment by alwhiteh** [comment]
Hi @johnkerl and @eddelbuettel,

I revisited installing the binaries from https://chanzuckerberg.r-universe.dev/tiledbsoma , but I noticed the files aren't labelled as x86_64 or ARM. It seems like the files are all based on x86_64 architecture. Would it be possible to generate one for ARM64?

**Comment by eddelbuettel** [comment]
@alwhiteh We do not currently have easily available access to such hardware. It has been promised for GitHub Actions, as I recall, but it just isn't there.  That ties our hands a little.

**Comment by alwhiteh** [comment]
@eddelbuettel I was able to get my hands on an Intel Mac to test this out again. I was able to install the packages fine, but found that tiledb wasn't able to load inside an renv environment. Just installing into the base environment works, and will be enough for now. Thanks!

**Comment by eddelbuettel** [comment]
Good to hear you were able to sort yourself out.  We also plan to submit the package to CRAN where, once accepted, binaries for both macOS hardware variants will be generated [just as is being done for package tiledb](https://cloud.r-project.org/web/packages/tiledb/index.html).

**Comment by johnkerl** [comment]
https://github.com/single-cell-data/TileDB-SOMA/tree/1.5.0 is released -- please let us know of any further issues 🙏
