### ISSUE TITLE
pybind11 support to Khash re-indexer

### ISSUE THREAD

**Issue by beroy** [single-cell-data/TileDB-SOMA#1609]
[parent #1614]
Add `pybind11` to re-indexer and repeat existing reindex benchmarks

**Comment by beroy** [comment]
[parent #1614]

**Comment by beroy** [comment]
https://github.com/single-cell-data/TileDB-SOMA/commit/5a6c8a7a9645db82698a6a6b1ceb278a0ec9b862

**Comment by beroy** [comment]
https://github.com/single-cell-data/TileDB-SOMA/commit/5a6c8a7a9645db82698a6a6b1ceb278a0ec9b862

**Comment by johnkerl** [comment]
@beroy I'm confused -- https://github.com/single-cell-data/TileDB-SOMA/commit/5a6c8a7a9645db82698a6a6b1ceb278a0ec9b862 seems to be a still-unmerged commit, on a not-yet-PR'ed branch -- ?
