### ISSUE TITLE
[python] Refactoring `ExperimentAxisQuery` to use the C++ CSR and re-indexer

### ISSUE THREAD

**Issue by beroy** [single-cell-data/TileDB-SOMA#1611]
Currently ExperimentAxisQuery is the only class in SOMA that does provide its own implementation. We need to refactor the functionality between SOMA and TileDB-SOMA such that we can use C++ re-indexer and CSR for `by_vars` and `by_obs` and `csr_iter` functions of that class.

Context: #1614

**Comment by johnkerl** [comment]
@beroy is this completed?
