### ISSUE TITLE
[python] Use new C++ API bindings in Python API (parent task)

### ISSUE THREAD

**Issue by nguyenv** [single-cell-data/TileDB-SOMA#1632]
Split-off from https://github.com/single-cell-data/TileDB-SOMA/issues/1240
- [x] #1714
- Pybind11 bindings
    - [x] #1715
    - [x] #2077
    - [x] #2078
    - [x] #2674
- [x] #2228 
- [x] #2240 
- [x] #2241

**Comment by johnkerl** [comment]
I think the @eddelbuettel assign was spurious -- unassigning -- @eddelbuettel if you're truly doing Python work, please let me know.

**Comment by johnkerl** [comment]
All that remains on the Python side is the final deprecation (with phase-out in TileDB-SOMA 1.14) wherein users will need to pass tiledb config via hashmap only, no longer via `tiledb.Ctx`.

So this is blocked until TileDB-SOMA 1.14.
