### ISSUE TITLE
[r] Investigate R CI failures

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1651]
This started on a Python-only commit (#1645), so, it may have to do with a dependency update or some such:

https://github.com/single-cell-data/TileDB-SOMA/actions/workflows/r-ci.yml?query=branch%3Amain

**Comment by eddelbuettel** [comment]
I think the earliest was in #1643 with runs [3094](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/6028844675) which wasn't Python but I could be wrong.

**Comment by johnkerl** [comment]
Adding @eddelbuettel as he's been peeking as well

cc @aaronwolen

**Comment by johnkerl** [comment]
* Branch `kerl/debug-ci` #1653 is branched off recent `main`: #1652's merge to `main` -- red
* Branch `kerl/debug-ci-2` #1654 is branched of #1627 's merge to `main` -- red
* Branch `kerl/debug-ci-3` #1655 is branched of #1644 's merge to `main`, which was _before_ #1643 that we are squinting at -- red
* Also I tried simply re-running CI for https://github.com/single-cell-data/TileDB-SOMA/actions/runs/6030724339/job/16401321592?pr=1641 #1641 -- green

Also I can repro from tip of `main` on my x86 Mac if I first `export CI=true` then `testthat::test_local("tests/testthat")`. Since that's fsater than CI, I'll bisect that way for a while.

**Comment by eddelbuettel** [comment]
Comment out this line

https://github.com/single-cell-data/TileDB-SOMA/blob/d07accb69c04f688426d586c13034eef8489e4ea/apis/r/src/riterator.cpp#L252

It worked on my branch

![image](https://github.com/single-cell-data/TileDB-SOMA/assets/673121/909ea37f-44d2-4326-8354-f38e4468241e)

My explicit resource manager is not working well enough it seems; @ihnorton and I discussed an alternative last week (when I was mostly done with this and had convinced myself it worked) which I will resurrect.

**Comment by johnkerl** [comment]
> Comment out this line

@eddelbuettel confirmed, thank you!

**Comment by johnkerl** [comment]
@eddelbuettel should we close this now?

**Comment by johnkerl** [comment]
Thanks!
