### ISSUE TITLE
[python] Sync TileDB-Py and TileDB-SOMA Python query-condition code

### ISSUE THREAD

**Issue by nguyenv** [single-cell-data/TileDB-SOMA#1667]
There have been several indepedent updates to the query condition code in TileDB-Py and TileDB-SOMA Python APIs that should be synced. Divergence has been introduced by both repos. For example, although the TileDB-Py code has support for query conditions on  dimensions and Boolean types, these are still missing in TileDB-SOMA. On the other end, TileDB-SOMA has been updated to use `attrs` but TileDB-Py still uses `dataclasses`.

**Comment by johnkerl** [comment]
@nguyenv did #1756 achieve this goal, as a side effect?

**Comment by nguyenv** [comment]
No, and in fact both #1756 and #1793 have introduced more divergences from the TileDB-Py code. For example, `init_query_condition` take in completely different arguments, and the TileDB-SOMA code retrieves info from a passed in `ArrowSchema` instead of TileDB `ArraySchema` (good because this means we getting rid of TileDB-Py dependencies in the SOMA code). This issue should probably be closed since the query condition codes are too different at this point.
