### ISSUE TITLE
[c++] Replace SOMA C++ API TileDB args with `ArrowSchema` or `ArrowArray`

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1713]
* [x] Get domain argument passed as `vector<ArrowArray*>`
* [ ] Set domains in `tiledb::ArraySchema`
* [ ] Move convertor functions to `arrow_adapter.h`
* [ ] Add create methods with updated function signatures that use Arrow structures (into `SOMADataFrame`, `SOMADenseNDArray`, `SOMASparseNDArraySparse)
* [ ] Add unit tests

Mirrors [sc-34647]

**Comment by johnkerl** [comment]
@nguyenv is this complete?

**Comment by nguyenv** [comment]
Yes
