### ISSUE TITLE
[Bug] `tiledbsoma.io.from_anndata` fails if `ad.var.index.name` is `None` or is in `ad.var.columns`

### ISSUE THREAD

**Issue by royassis** [single-cell-data/TileDB-SOMA#1722]
**Describe the bug**
`tiledbsoma.io.from_anndata` fails if anndata object (ad) ad.var.index.name is **None** or is in **ad.var.columns**

**Versions (please complete the following information):**
tiledbsoma.__version__        1.4.0
TileDB-Py tiledb.version()    (0, 22, 2)
TileDB core version           2.16.2
libtiledbsoma version()       libtiledb=2.16.2
python version                3.10.12.final.0
OS version                    Linux 5.15.90.1-microsoft-standard-WSL2

**Comment by johnkerl** [comment]
@royassis thank you! 

This has been identified and will be included in the TileDB-SOMA 1.5.0 release. (The PR is #1718.)
