### ISSUE TITLE
[python] Revisit `numba` 0.58 dependency

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1733]
This was updated in #1723 (and `release-1.5` branch #1726).

Meanwhile I ran a condability check -- which in hindsight I should have run _before_ accepting #1723 -- at https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/48.

This failed as noted by @jdblischak at https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/48#issuecomment-1739947985 since numba 0.58.0 is not yet available on conda-forge

numba 0.58.0 isn't available on conda-forge yet

* https://anaconda.org/conda-forge/numba/files
* https://github.com/conda-forge/numba-feedstock/pull/126 open, blocked by
* https://github.com/conda-forge/llvmlite-feedstock/pull/74, which has all-red CI

We may need to revert our dependency back to numba 0.57 until numba 0.58.0 is available at conda-forge.

cc @thetorpedodog @mlin @jdblischak

**Comment by jdblischak** [comment]
Numba 0.58.1 was merged this morning for conda-forge (https://github.com/conda-forge/numba-feedstock/pull/128, https://github.com/conda-forge/numba-feedstock/commit/172c489224b795438fdbf289d04cbc188ddb480a)

**Comment by johnkerl** [comment]
https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/48 resolves this issue -- the moment we drop support for Python 3.7 (#1790), which is imminent. Leaving this open until then.

**Comment by bkmartinjr** [comment]
@johnkerl - what (if any) is the action to be taken? Or is this resolved?  My understanding is that with the new `>=0.58` pin, both conda and pypi backed installs should be fine, as 0.58 is available (in both locations). Closing, but please re-open if I misunderstand the issue.

**Comment by johnkerl** [comment]
Sorry @bkmartinjr I forgot to signal my intent -- yes, #2122 resolves this, and I wanted to honor/acknowledge your contribution on that front. Thank you!
