### ISSUE TITLE
[r/ci] Look at recent R CI failures

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1774]
* https://github.com/single-cell-data/TileDB-SOMA/actions/runs/6461133284
* https://github.com/single-cell-data/TileDB-SOMA/actions/runs/6437511194

**Comment by eddelbuettel** [comment]
From probing is various CI builds this is almost surely a build issue with one or more dependent packages as it consistently and immediately fails.  But I have not (physical) access to the type hardware it fails on so there is _very_ little I can do here.

**Comment by eddelbuettel** [comment]
It also passes on macOS-arm64 (where I took care to ensure all tests are running too):
https://mac.r-project.org/macbuilder/results/1696951297-2b9f9d9907445530/
