### ISSUE TITLE
[R] get_seurat crash

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#1789]
See chanzuckerberg/cellxgene-census#809

**Comment by johnkerl** [comment]
@mojaveazure I'm not sure what we can do until 1.5.0 and/or @eddelbuettel 's return from PTO, but, leaving this with you, and you & I can peek a bit once you're back next week.

**Comment by johnkerl** [comment]
Significant conversation is at https://github.com/chanzuckerberg/cellxgene-census/issues/809
