### ISSUE TITLE
[python] Type signature for `SparseNDArray.read coord` is overly restrictive

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#1791]
SparseNDArray.read accepts a Arrow chunked array of integers as an acceptable coordinate.  However, the SparseNDCoord type signature does not accept ChunkedArray, creating false errors with mypy, etc.

The current definition uses pa.IntegerArray, which is a sub-class of pa.Array.  Also needed is a pa.ChunkedArray (AFAIK, there is no way to express a more specialized sub-class of ChunkedArray in the current pyarrow).

```
SparseNDCoord = Union[
    None,
    ValSliceOrSequence[int],
    npt.NDArray[np.integer],
    pa.IntegerArray,
]
"""A single coordinate range for one dimension of a sparse nd-array."""
SparseNDCoords = Sequence[SparseNDCoord]
"""A sequence of coordinate ranges for reading sparse ndarrays."""
```

**Comment by johnkerl** [comment]
To be assigned to @ryan-williams

**Comment by johnkerl** [comment]
[sc-41751]

**Comment by johnkerl** [comment]
@ryan-williams please put up a PR on `TileDB-SOMA` bumping to `somacore` 1.0.9 here:

```
.pre-commit-config.yaml
18:        - "somacore==1.0.8"

apis/python/setup.py
332:        "somacore==1.0.8",
```

**Comment by ryan-williams** [comment]
@johnkerl #2251 is merged, lmk if anything else should happen here
