### ISSUE TITLE
[python/r] Enforce identical core library version

### ISSUE THREAD

**Issue by eddelbuettel** [single-cell-data/TileDB-SOMA#1837]
**Is your feature request related to a problem? Please describe.**

We have by now learned that TileDB Core version differences between the API package (tiledb-py, tiledb-r) and the tiledbsoma package can lead to undesirable outcomes.   We actually have the versions as the debug helpers (ie in R `show_package_version()`) display them.

**Describe the solution you'd like**

We should consider aborting with error when the versions differ.  Possibly to be overriden by an enviroment variable.

**Describe alternatives you've considered**

If and when all read and writes are done directly by tiledbsoma this will no longer be an issue.  So we _could_ just wait...

**Additional context**

From discussion on Slack with @johnkerl

**Comment by eddelbuettel** [comment]
Well the funny bit is ... that we pointed at this as a cause of segfaults but now we also have counter examples where it didn't.  So should we?  Should we not?  Wiring it up from the R package startup is easy-ish and can be done quickly.  But will it help, or hurt?  Maybe message() as a start?

**Comment by johnkerl** [comment]
@eddelbuettel if we have mismatched core versions and we _don't_ have segfaults, we are simply lucky.

The requested task for this sprint is to please implement a runtime version check, in Python and R, that fatals if the two core versions do not match.
