### ISSUE TITLE
[r] Fix query conditions on enumerated columns

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1867]
Works in Python: https://gist.github.com/johnkerl/3d1279b0e3bd9e599d541774419faa54
Not in R: https://gist.github.com/johnkerl/d22373ff55cca23cd23672dae547b3de

Note `s3://tiledb-johnkerl/s/v/pbmc3k` in the above gists is nothing other than `tiledbsoma.io.from_h5ad` of
https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/python/testdata/pbmc3k.h5ad

Needs:

* Bugfix
* Unit-test coverage

See also #1862

**Comment by johnkerl** [comment]
[sc-34800]

**Comment by eddelbuettel** [comment]
Fixed by https://github.com/TileDB-Inc/TileDB-R/pull/614 as the actual parsing is done in the `tiledb` package.

**Comment by johnkerl** [comment]
@eddelbuettel thanks! Looking forward to closing this PR once this functionality is rolled into TileDB-SOMA. (Remaining PRs mine, after you've got `TileDB-R` tagged & in [Conda](https://github.com/conda-forge/r-tiledb-feedstock).)
