### ISSUE TITLE
[c++] `cmake` version requirement

### ISSUE THREAD

**Issue by dingying85** [single-cell-data/TileDB-SOMA#1888]
The current R installation of TileDB-SOMA require cmake version >=3.2, is that possible to relax that? the current backend we have is 3.19. 

Thanks.

**Comment by eddelbuettel** [comment]
Hi @dingying85 and thanks for taking the time to raise an issue.  The requirement comes from the underlying 'libtiledbsoma/' C++ library that is part of the package:

https://github.com/single-cell-data/TileDB-SOMA/blob/ad48fadd76226f8574c8a7a3663e71fc251cbd4b/libtiledbsoma/CMakeLists.txt#L32

This cannot be relaxed easily.  However, you can get binaries of `cmake` for many systems from kitware, see [their download page](https://cmake.org/download/).

**Comment by johnkerl** [comment]
@dingying85 thank you for writing! As I understand this issue is resolved -- please let me know if I'm mistaken and I'll be happy to re-open.
