### ISSUE TITLE
X-data transpose/consistency question

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#19]
# Overview

The `X` data in `tiledbsc-r` and `tiledbsc-py` are, at present, transposes of one another. This is because the rows/columns are transposed in R (Seurat/Bioconductor) vs. Python (anndata).  In R the data matrices are genes by samples (or cells), whereas in Python/anndata they are samples by genes.

At present, `tiledbsc-py`'s transposition is consistent with other Python tools (including anndata), not consistent with `tiledbsc-r`.

This is open for discussion.

# tiledbsc-r details

In [`tiledbsc-r`](https://github.com/TileDB-Inc/tiledbsc) we have

```
ArraySchema(
  domain=Domain(*[
    Dim(name='var_id', domain=(None, None), tile=None, dtype='|S0', var=True),
    Dim(name='obs_id', domain=(None, None), tile=None, dtype='|S0', var=True),
  ]),
  attrs=[
    Attr(name='value', dtype='float64', var=False, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
  ],
  cell_order='row-major',
  tile_order='row-major',
  capacity=10000,
  sparse=True,
  allows_duplicates=True,
)
```

```
> arr <- tiledb_array('pbmc-small-tiledbsc-r/scgroup_RNA/X/data', return_as='data.frame')
> df <- arr[]
> head(df$value)
[1] 4.615121 4.208048 3.976987 3.997759 3.485709 4.753095
> head(df$obs_id)
[1] "AATGTTGACAGTCA" "ACAGGTACTGGTGT" "AGAGATGATCTCGC" "AGATATACCCGTAA"
[5] "CATTACACCAACTG" "GAACCTGATGAACC"
> head(df$var_id)
[1] "ACAP1" "ACAP1" "ACAP1" "ACAP1" "ACAP1" "ACAP1"
```

# tiledbsc-py details

In this package (`tiledbsc-py`) we have -- at present

```
ArraySchema(
  domain=Domain(*[
    Dim(name='obs_id', domain=(None, None), tile=None, dtype='|S0', var=True),
    Dim(name='var_id', domain=(None, None), tile=None, dtype='|S0', var=True),
  ]),
  attrs=[
    Attr(name='data', dtype='float64', var=False, nullable=False),
  ],
  cell_order='row-major',
  tile_order='row-major',
  capacity=10000,
  sparse=True,
  allows_duplicates=True,
)
```

```
>>> import tiledb
>>> arr = tiledb.open('pbmc-small-tiledbsc-py/X/data')
>>> df = arr[:]
>>> df.keys()
odict_keys(['data', 'obs_id', 'var_id'])
>>> df['data']
array([-0.37303159,  2.52006507, -0.37303159, ...,  0.45850021, -1.039994  , -1.039994  ])
>>> df['obs_id']
array([b'AAATTCGAATCACG', b'AAATTCGAATCACG', b'AAATTCGAATCACG', ..., b'TTTAGCTGTACTCT', b'TTTAGCTGTACTCT', b'TTTAGCTGTACTCT'], dtype=object)
>>> df['var_id']
array([b'AKR1C3', b'CA2', b'CD1C', ..., b'TREML1', b'TUBB1', b'VDAC3'], dtype=object)
```

**Comment by bkmartinjr** [comment]
Apologies for being somewhat pedantic: should this be a question for the platform independent SOMA API spec, rather than a TileDB implementation-specific decision?

Personally, I can live with either as long as it is well defined/consistent.

CC @brianraymor @ambrosejcarr

**Comment by johnkerl** [comment]
@bkmartinjr agreed! :D

**Comment by brianraymor** [comment]
This is a requirement that must be clarified in the _platform independent SOMA API spec_.

**Comment by johnkerl** [comment]
Decided on today's call:

* We preserve consistency with other Python tools by storing `obs_id` as `dim0` and `var_id` as `dim1`
* Subsequent API-call layering may provide access methods with `var,obs` signatures as a syntactic convenience

cc @ambrosejcarr @bkmartinjr @brianraymor

**Comment by johnkerl** [comment]
No action required at present as we are already storing the `X` data this way.

**Comment by bkmartinjr** [comment]
@johnkerl - I believe this was resolved a long time ago.  Closing.
