### ISSUE TITLE
[python/r] Run `cellxgene-census` acceptance tests pre 1.6.0

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1931]
Needs:

* Core 2.18.0 available
* TileDB-Py 0.24
* TileDB-R
* A commit hash of `main` of this repo

to @bkmartinjr run acceptance tests before we tag 1.6.0

**Comment by johnkerl** [comment]
@pablo-gar to run R acceptances IIUC

**Comment by bkmartinjr** [comment]
Our python tests ran and all looks good

**Comment by johnkerl** [comment]
@bkmartinjr great news! Hoping the R tests do the same

**Comment by johnkerl** [comment]
Verified by @ebezzi and @pablo-gar
