### ISSUE TITLE
"-" character not accepted when querying based on a var_id

### ISSUE THREAD

**Issue by ccnawrocki** [single-cell-data/TileDB-SOMA#1984]
I have an older scRNA-seq dataset that has some odd gene names in it, including some with hyphens. I am querying individual genes' expressions. Whenever I try to do so for a gene that has a "-" in the name, it fails to work. 

```
> query <- st14$axis_query(
+     measurement_name = "RNA",
+     var_query = SOMAAxisQuery$new(
+       value_filter = "var_id == loc100124848-like"
+     )
+   )
>   mat <- query$to_sparse_matrix(
+     collection = "X",
+     layer_name = "data",
+     obs_index = "obs_id",
+     var_index = "var_id"
+   )
Error: Unsuitable dim points on dimension 'soma_dim_1' with domain [0,24869]
> 
```

Is there an easier way to do this? Is the "-" being interpreted as a minus sign in the querying syntax? 

 - TileDB-SOMA: 0.99.2
 - R: 4.3.1
 - MacOS on M1 MacBook Air

Thanks.

**Comment by eddelbuettel** [comment]
Just a guess here:  R may get in the way for an _unquoted_ expression with a hyphen thinking it asked to subtract.

Can you try   `value_filter = "var_id == 'loc100124848-like'"`    i.e. protect the 'word' containing the hyphen with single quotes inside the double-quoted string you submit?

**Comment by ccnawrocki** [comment]
That seemed to fix it. Thanks a bunch. I probably should have tried some simple things like that before making that post LOL

**Comment by eddelbuettel** [comment]
That's the thing with computers. They try a (fixed) number of tricks to fool us, and _eventually_ we catch on!
