### ISSUE TITLE
[r/ci] Debug intermittent R CI segfaults

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2020]
These are currently happening, only R CI, AFAICT only with coverage enabled.

**Comment by johnkerl** [comment]
[sc-39284]

**Comment by eddelbuettel** [comment]
It's anecdata but I believe @mojaveazure and I different permutation with / without coverage fail via segfault. No pattern as best as I can tell, and no smoking gun.  :face_with_head_bandage:

**Comment by johnkerl** [comment]
@eddelbuettel thanks.

Whatever it is, this task is for fixing it. Any/all help is welcome.

**Comment by eddelbuettel** [comment]
@johnkerl It is kind that you assign me here but there is nothing I can. @mojaveazure and I have been at this and have spent _entire days_ on it already.

**Comment by johnkerl** [comment]
@eddelbuettel thanks. I'm trying to honor and acknowledge the work you're already doing. I've three names on this, including my own, and am trying to contribute as well.

**Comment by johnkerl** [comment]
Some info:

* https://github.com/single-cell-data/TileDB-SOMA/pull/2013 a fail and a pass
* Pass https://github.com/single-cell-data/TileDB-SOMA/actions/runs/7562292090/job/20592459529
* Fail https://github.com/single-cell-data/TileDB-SOMA/actions/runs/7562177209/job/20592076386
* I pulled raw logs for both
* Sedded out the leader regex `^20..-..-..T..:..:..........Z `
* Sedded raw pass log here: https://gist.github.com/johnkerl/86ce5e389a27c23fc6b76795dc9f402c
* Sedded raw fail log here: https://gist.github.com/johnkerl/79e47812cd5f7a29f51e7b45325b516c
* Sdiff: https://gist.githubusercontent.com/johnkerl/a82b72b634e9015fe630676b918537a4/raw/f5fb80c8265f299858565cae107aff0606fa5588/gistfile1.txt

I'm still 👀 and 🤔 but the first thing that pops out is

```diff
5c5
< Job is about to start running on the hosted runner: GitHub Actions 3 (hosted)
---
> Job is about to start running on the hosted runner: GitHub Actions 5 (hosted)
14,16c14,16
< Version: 20240116.3.0
< Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240116.3/images/ubuntu/Ubuntu2204-Readme.md
< Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240116.3
---
> Version: 20240107.1.0
> Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240107.1/images/ubuntu/Ubuntu2204-Readme.md
> Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240107.1
```

...

**Comment by johnkerl** [comment]
Pulling more logs:

* `hosted runner: GitHub Actions ` may be followed by a 2, 3, 4, 5, 6, 8, 11, ... this is maybe a slot number and does not seem to correlate or signify
* There are green and red instances both on `Version: 20240107.1.0`

🤔

**Comment by johnkerl** [comment]
I looked at several other diff-lines in a bunch of green and red raw logs and could find no correlation ...

**Comment by johnkerl** [comment]
These are not presently happening; #2027 is in place for when/if they begin to. Closing for now.
