### ISSUE TITLE
[Feature request] Update documentation on the version of C++ compiler to install `tiledbsoma` R package

### ISSUE THREAD

**Issue by CharlesBordet** [single-cell-data/TileDB-SOMA#2029]
### Is your feature request related to a problem? Please describe.

Edit: I forgot to mention that this is related on the R package. The documentation I mention is `apis/r/README.md`

I ran into issues installing `tiledbsoma` on Amazon Linux 2. The documentation mentions requirements such as `cmake` and `git`, and I found that a recent enough version of a C++ compiler is also necessary.

Amazon Linux 2 comes with `gcc` version 7.3.1.

Installing `tiledbsoma` fails at the step `Building CXX object src/CMakeFiles/TILEDB_SOMA_OBJECTS.dir/soma/soma_dataframe.cc.o` with the following error message:

```
/tmp/Rtmp1MSC8v/R.INSTALL375e29e92bdb/tiledbsoma/src/libtiledbsoma/src/soma/soma_dataframe.cc:33:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
```

I found that using `#include <filesystem>` is not possible with `gcc` version 7. I upgraded it to version 8, which resolved this issue, but met another one later during the installation:

```
g++ -std=gnu++17 -I"/opt/R/4.1.3/lib64/R/include" -DNDEBUG -I. -I../inst/include/ -I../inst/tiledb/include -I../inst/tiledbsoma/include   -I'/home/user/project/renv/library/R-4.1/x86_64-pc-linux-gnu/Rcpp/include' -I'/home/user/project/renv/library/R-4.1/x86_64-pc-linux-gnu/RcppSpdlog/include' -I'/home/user/project/renv/library/R-4.1/x86_64-pc-linux-gnu/RcppInt64/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:0:
../inst/include/tiledbsoma_types.h:21:10: fatal error: tiledbsoma/tiledbsoma: No such file or directory
 #include <tiledbsoma/tiledbsoma>
          ^~~~~~~~~~~~~~~~~~~~~~~
```

This time I upgraded to `gcc` version 10.5.0, and it finally worked.

It took me quite some time to figure out what the issue was and how to resolve it. It would be great if the documentation states the version of `gcc` that is required.

### Describe the solution you'd like

The documentation (`README.md`) currently mentions: "Installing from source on Unix-like platforms requires `cmake` and `git`."

It could state, for example: "Installing from source on Unix-like platforms requires `cmake`,  `git`, and a recent version of a C++ compiler (it was tested on version 10.5.0)"

It could also be added in the list of Requirements which is further down on the same page.

### Describe alternatives you've considered

I had `cmake` on version 3.21.3, which I upgraded to the latest version 3.28.1, but this didn't resolve anything.

**Comment by eddelbuettel** [comment]
Thanks -- As mentioned in your PR #2031 (thanks for that by the way) `g++-10` is known good.  We likely also have a known-good `clang++` but I am currently unsure which version is the effective minimal version.

**Comment by CharlesBordet** [comment]
Moving my PR comment here:

Thanks for the suggestion, I have committed your rewriting.

About clang++: I don't know what version is required, I didn't have to install it specifically, nor can I actually find it (clang or clang++ is not found).

**Comment by eddelbuettel** [comment]
I am on Linux so I have several `clang++`  versions (currently: clang++-4.0, clang++-8, and then -10 to -17; Ubuntu 23.10 as a rolling installation) but I don't regularly pivot back and forth.  

So being empirically minded I just tried.  `CC=clang-10 CXX=clang++-10` worked, but switching to 8 failed.  We know from related work on TileDB Core that Ubuntu 20.04 LTS is also no longer good enough (and use 22.04 LTS as a fallback, and in all CI).  And [packages.ubuntu.com shows](https://packages.ubuntu.com/search?keywords=clang&searchon=names&suite=jammy&section=all) it spans 11 to 15.   I will leave the PR and issue open for a bit to let my colleagues chime in but can otherwise merge this as it is a clear improvement, and we can always clarify the `clang++` situation later.

**Comment by eddelbuettel** [comment]
Now taken care of via #2031 thanks to your PR -- thanks again.
