### ISSUE TITLE
[r/ci] Debug pkgdown CI fail at release-tag time

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2052]
# Problem

Tagging
https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.7.0rc0
triggered
https://github.com/single-cell-data/TileDB-SOMA/blob/5cc41b323d02dc7015e95f4e07d24742b6c14dd3/.github/workflows/pkgdown.yaml
which only runs on releases.

There, we got the compile error
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/7618476508/job/20749733125#step:5:916
namely
```
using C compiler: 'gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'
using C++ compiler: 'g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'
using C++17
g++ -std=gnu++17 -I"/opt/R/4.3.2/lib/R/include" -DNDEBUG -I. -I../inst/include/ -I../inst/tiledb/include -I../inst/tiledbsoma/include   -I'/home/runner/work/_temp/Library/Rcpp/include' -I'/home/runner/work/_temp/Library/RcppSpdlog/include' -I'/home/runner/work/_temp/Library/RcppInt64/include' -I/usr/local/include    -fpic  -g -O2  -Wall -pedantic -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
../inst/include/tiledbsoma_types.h:21:10: fatal error: tiledbsoma/tiledbsoma: No such file or directory
   21 | #include <tiledbsoma/tiledbsoma>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/opt/R/4.3.2/lib/R/etc/Makeconf:200: RcppExports.o] Error 1
ERROR: compilation failed for package 'tiledbsoma'
* removing '/tmp/RtmpU14Loy/Rinst1b795ff84a8f/tiledbsoma'
      -----------------------------------
ERROR: package installation failed
```

This is odd for several reasons:

* We build from source in our other CIs all the time
* It's not at all clear why this path is using `-Werror=pedantic`:
  * `.github/workflows/pkgdown.yaml`
  * `./apis/r/tools/install-pkgdown-dependencies.sh`
  * `Rscript -e 'remotes::install_local()'`
* Nowhere in any of that do I see `-Werror=pedantic` spelled out anywhere at all.

# Repros

I've tried repros as follows:

* `remotes::install_local()` on my MacOS laptop -- no repro
* `remotes::install_local()` on my MacOS laptop with https://gist.github.com/johnkerl/d556a6d1f86591ed0ba66adee62ab0ab -- no repro
* `remotes::install_local()` on an EC2 Ubuntu instance with https://gist.github.com/johnkerl/d556a6d1f86591ed0ba66adee62ab0ab -- no repro
* Run in CI with #2050 -- repro
* Run with `docker run --rm -it --entrypoint=/bin/bash` -- repro

Repro details with Docker:

```
alias dreb='docker run --rm -it --entrypoint=/bin/bash'
dreb eddelbuettel/r2u:jammy
# I have also heard about `docker run --rm -it rocker/r2u`
apt-get update
apt-get install -y cmake git

cd /tmp
git clone https://github.com/single-cell-data/TileDB-SOMA
cd TileDB-SOMA

git checkout release-1.7
git log -n 1

apis/r/tools/install-pkgdown-dependencies.sh
```

Note: this repro failed as described above without #2051 and succeeded with #2051.

# Next steps

Also to do: Run the installer bit, at least, in a nightly job so we can surface these errors sooner than at release-tag time.

**Comment by eddelbuettel** [comment]
I did some testing in a shadow repo and have seen no issues in a standard Ubuntu setup as already used in other CI setups.  `pkgdown` installs, and runs.

**Comment by johnkerl** [comment]
This is not failing
