### ISSUE TITLE
[Bug] Weird error when ingesting Seurat object

### ISSUE THREAD

**Issue by ccnawrocki** [single-cell-data/TileDB-SOMA#2090]
While trying to ingest a Seurat v3 object into a soma, it kept failing due to a dependency function, from what I can tell. 

Example: 
```
> write_soma(briggs, "/home/cnawrocki/Documents/grainger-data/briggs_unintegrated_soma")
Error: ArraySchema: Error extending enumeration. Provided enumeration is not an extension of the current state of 'orig.ident'
> 
```
`briggs` is the Seurat object after the standard workflow.

Versions:
 - TileDB-SOMA 1.6.2
 - R 4.3.2
 - Linux Ubuntu
 - Intel Core i9

What is interesting is that I have not encountered this issue on my M1 mac. I just got a PC and am running Ubuntu on it, so I am now encountering the issue. 

Any help would be much appreciated.

**Comment by eddelbuettel** [comment]
Hi @ccnawrocki -- this is a something we addressed in mid-December after version 1.6.0 came out (and versions 1.6.1 and 1.6.2 contained only Python changes).  

How are you installing the TileDB-SOMA package?  Could you try the 1.7.0 release candidates listed [at the Releases page](https://github.com/single-cell-data/TileDB-SOMA/releases)  ?
