### ISSUE TITLE
[python] indexer creation performance is slow for Pandas Series vs numpy ndarray

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#2099]
if you build an indexer with a Pandas Series, it is 25X slower than if you build it with a Numpy NDArray.  Example which uses the exact same object, but does a cast before calling the index creator.

Expected result: these should be identical

This is on the (pre-release) `release-1.7` branch as of 8d858e6

```
In [36]: import pandas as pd, tiledbsoma as soma

In [37]: type(obs.soma_joinid)
Out[37]: pandas.core.series.Series

In [38]: type(obs.soma_joinid.to_numpy())
Out[38]: numpy.ndarray

In [39]: obs.soma_joinid.shape
Out[39]: (41939851,)

In [40]: %time soma.tiledbsoma_build_index(obs.soma_joinid)
CPU times: user 50.8 s, sys: 405 ms, total: 51.2 s
Wall time: 51.2 s
Out[40]: <tiledbsoma.pytiledbsoma.IntIndexer at 0x7fa0daa04530>

In [41]: %time soma.tiledbsoma_build_index(obs.soma_joinid.to_numpy())
CPU times: user 1.29 s, sys: 285 ms, total: 1.58 s
Wall time: 1.58 s
Out[41]: <tiledbsoma.pytiledbsoma.IntIndexer at 0x7f9e32a2fb70>
```

**Comment by bkmartinjr** [comment]
We should also ensure that we correctly (performantly) handle:
* Arrow Array (contiguous)
* Arrow ChunkedArray (non-contiguous)
* pandas.Series (original bug)
* numpy.ndarray (which already works)

**Comment by beroy** [comment]
I tried multiple scenarios and used the np.array as my base line (keys and lookups are equal and I perform one map_location (setup) and one lookup):
**Baseline:**
    `keys = np.array(range(1, 100000000))`
Setup time: 1.7088468329966418
Lookup time: 0.49534945800405694    
**pyarrow array:**
   `keys = pa.array(list(range(1, 100000000)))`
Setup time: 1.7942252089997055
Lookup time: 0.5838396660037688
**pyarrow Chunked Array:** 
    `keys = pa.chunked_array([list(range(1, 100000000)), list(range(100000000, 200000000)), list(range(300000000, 400000000))])`
**3x size the baseline data.**
Setup time: 10.952384541000356
Lookup time: 6.603933874997892    
    
**Pandas series:** 
        keys = pd.Series(list(range(1, 100000000)), copy=False)
Setup time: 93.01347337499465
Lookup time: 0.49027750000095693        
**Pandas arrays:** 
        keys = pd.array(list(range(1, 100000000)))
Setup time: 76.63969441700465
Lookup time: 0.5059003329952247

As can be seen panda's array and series lead to major slowdown in the setup phase while the rest are relative close to the baseline. Looking at map_locations I noted that (different from `lookup`) there are two hooks, one for py::array_t and one for std::vector<int64_t> input types.
```
        .def(
            "map_locations",
            [](IntIndexer& indexer,
                py::array_t<int64_t> keys,
                int num_threads) {
...
        .def(
            "map_locations",
            [](IntIndexer& indexer,
                std::vector<int64_t> keys,
                int num_threads) {

```
Investigating more, I found out that the calls ending up to `std::vector<int64_t>` version are the slow ones. It appeared that in case of pandas somehow the pybind runtime chooses to make the slow vector calls. Removing that version of map_locations, the observed overhead totally disapeared!

**Comment by beroy** [comment]
After the change:
**Pandas arrays:**
`keys = pd.array(list(range(1, 100000000)))
`
Setup time: 1.712055790994782
Lookup time: 0.5056431670018355

**Pandas series:**
`keys = pd.Series(list(range(1, 100000000)), copy=False)`

Setup time: 1.6870728750000126
Lookup time: 0.4930597909988137

**Comment by beroy** [comment]
Panda runs:

**numpy array:**
`keys = np.array(range(1, 100000000))`
Setup time: 7.595900387968868e-05
Lookup time: 2.611686832999112

**pyarrow array:**
`keys = pa.array(list(range(1, 100000000)))`
Setup time: 0.00011958299728576094
Lookup time: 2.5583114580076654

**pyarrow Chunked Array:**
`keys = pa.chunked_array([list(range(1, 100000000)), list(range(100000000, 200000000)), list(range(300000000, 400000000))])`
Setup time: 0.5131658750033239
Lookup time: 29.461485624997295

**Pandas series:**
`keys = pd.Series(list(range(1, 100000000)), copy=False)`
Setup time: 0.00014925000141374767
Lookup time: 2.2870173749979585

**Pandas arrays:**
`keys = pd.array(list(range(1, 100000000)))`
Setup time: 8.699999307282269e-05
Lookup time: 2.6260701669962145

**Python list:**
`keys = list(range(1, 100000000))`
Setup time: 10.015719040995464
Lookup time: 12.734747709007934

**Comment by beroy** [comment]
https://github.com/single-cell-data/TileDB-SOMA/pull/2159
