### ISSUE TITLE
[Bug] Installation issue on windows with pip

### ISSUE THREAD

**Issue by royassis** [single-cell-data/TileDB-SOMA#2109]
**Describe the bug**

As I saw "Microsoft::Windows" was added as a valid Operating System on pypi tiledbsoma page, I tried to install it on windows.

I got an error:
tiledbsoma build fails on windows. 

**To Reproduce**
Run 
`pip install tiledbsoma`
 On a windows environment.

**Versions (please complete the following information):**
 - OS windows 10

**Additional context**
Trying to install in a conda environment.   
File with pip output is attached.

[pip_output.txt](https://github.com/single-cell-data/TileDB-SOMA/files/14180311/pip_output.txt)

**Comment by eddelbuettel** [comment]
Hi @royassis that may be an inadvertent bug over at PyPi.  We have providing Windows builds on the roadmap, but we are not there yet.
