### ISSUE TITLE
[python] Files re-work on `io/ingest.py`

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2121]
The file `apis/python/src/tiledbsoma/io/ingest.py` is quite large.

* At very least split it up into `io/ngest.py` and `io/outgest.py`
* This may entail some common symbols moved to a new `io/_common.py`

Possible follow-on (I prefer as a separate PR from the above):

* `io/ingest.py` -> `io/ingest_anndata.py` (for `from_anndata` and `from_h5ad`)
* `io/outgest.py` -> `io/outgest_anndata.py` (for `to_anndata` and `to_h5ad`)
* `io/ingest_whatevs.py` and `io/outgest_whatevs.py` for new spatial file-format experiments

This is intended to be a warm-up issue for a new team member to be selected by @jp-dark.

Please also see
https://github.com/single-cell-data/TileDB-SOMA/wiki/Information-for-developers
and don't hesitate to contact me with any questions about TIleDB-SOMA development. :)

**Comment by johnkerl** [comment]
@ryan-williams I believe this is complete (unless you had a 2nd PR in mind) -- if I'm mistaken we can re-open -- thank you!

**Comment by ryan-williams** [comment]
Sounds good, I was thinking we can revisit the 2nd part (format-specific {ingest,outgest} files) later, if/when we support more formats…

**Comment by johnkerl** [comment]
Thanks -- I'll make a separate issue
