### ISSUE TITLE
[python] Refactor binding code to inherit from `SOMAArray` and `SOMAObject`

### ISSUE THREAD

**Issue by nguyenv** [single-cell-data/TileDB-SOMA#2125]

**Comment by nguyenv** [comment]
Completed by https://github.com/single-cell-data/TileDB-SOMA/pull/2124

**Comment by johnkerl** [comment]
@nguyenv what else remains to be done here?

**Comment by nguyenv** [comment]
Nothing but the PR still needs to be merged. I'm just waiting for CI to finish. I accidentally closed the wrong issue.
