### ISSUE TITLE
[python][c++] C++ reindexer must use a single thread pool shared across all indexer objects

### ISSUE THREAD

**Issue by beroy** [single-cell-data/TileDB-SOMA#2146]
**Is your feature request related to a problem? Please describe.**
Currently the C++ Reindexer creates one threadpool per reindxer objects which can lead to further explosion of threads. 

**Describe the solution you'd like**
An alternative solution is to use a single threadpool for all the reindexer objects.
To do this, the following need to done:

- Allocate a single process level threadpool
- Placing the indexer object pointer in the threadpool lookup lambda 
- Few small fixes

The API changes:

- Thread pool should be part of the soma context, which already has a lifecycle.
- Config and setup can be part of the soma context setup/init. For example, it can be `soma.indexer.concurrency`

**Comment by beroy** [comment]
CC @bkmartinjr @johnkerl

**Comment by bkmartinjr** [comment]
Fully agree with this.  A common case is two indexers used at the same time (obs & var), and it would be much nicer to have a single, shared thread pool for the entire SOMATileDBContext so that we can amortize the cost,  have fewer threads, etc.

CC: @thetorpedodog

**Comment by beroy** [comment]
[2148](https://github.com/single-cell-data/TileDB-SOMA/pull/2148)
