### ISSUE TITLE
[python] Remove special type handling in `QueryCondition` parser required for Python 3.7

### ISSUE THREAD

**Issue by nguyenv** [single-cell-data/TileDB-SOMA#2185]
https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/python/src/tiledbsoma/_query_condition.py#L374-L379

The Python AST module had a significant refactoring between 3.7 and 3.8 which in our code required special handling like in the example above. In 3.7, `ast.Num`, `ast.Str`, and `ast.Bytes` nodes needed to be handled separately. As of 3.8, that was deprecated and are now handled as `ast.Constant` or `ast.NameConstant`.

**Comment by johnkerl** [comment]
Related to #2181
