### ISSUE TITLE
[python] Implement `IntIndexer` as class that wraps around `clib.IntIndexer`

### ISSUE THREAD

**Issue by nguyenv** [single-cell-data/TileDB-SOMA#2187]
This is not high priority, but I would like to see a pure Python `IntIndexer` class as a wrapper around `clib.IntIndexer`. This will make handling different types easier. As opposed to doing the type checking in the Pybind11 function, we can just use `isinstance` on the Python side to check the type of the object and hand it to the correct function. We should also rename the file from `_index_util.py` to `_indexer.py`.

Crude example:
```
class IntIndexer:
   def __init__(self):
       _native_indexer = clib.IntIndexer()

   def get_indexer(self, lookups):
       if(lookups is pyarrow object):
           return self._native_indexer.get_indexer_pyarrow()
       return self._native_indexer.get_indexer_generic()
```

What is already in `_index_util.py` right now is already a good base. Instead of a `tiledbsoma_build_index` function, it would be implemented as the constructor for `IntIndexer`. Then within that class, implement a function `get_indexer` which would call either `self._native_indexer.get_indexer_py_arrow` or `self._native_indexer.get_indexer_general`.

**Comment by jp-dark** [comment]
I have a design question for this. I'm assuming we want the class to satisfy the `IndexLike` protocol [defined in SOMA](https://github.com/single-cell-data/SOMA/blob/main/python-spec/src/somacore/query/types.py#L10). There are two options:

1. Add `method`, `limit`, and `tolerance` to the `IntIndexer` class and either ignore the arguments or throw an error if not `None`.
2. Update the `IndexLike.get_indexer` method to only include `target` parameter. (I checked and mypy seems to still accept `pd.Index` as being a valid `IndexLike` object without the optional keyword arguments.)

I prefer (2). We only use this parameter in somacore, so it is a more accurate protocol, but I wanted to check here before expanding the scope of this task beyond TileDB-SOMA.

**Comment by thetorpedodog** [comment]
yeah, my putting the other parameters in the IndexLike protocol was probably not a good idea; i think i was kind of blindly following [what appears in the Pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.Index.get_indexer.html). we should just make it take only the one parameter, since that is all we use.
