### ISSUE TITLE
[c++] Create ArrowSchema from TileDB Array Schema (keep-open)

### ISSUE THREAD

**Issue by nguyenv** [single-cell-data/TileDB-SOMA#2228]
- [x] Pass in `ColumnIndexInfo` that contains domain and tile extents for each index column
- [x] Set attributes
- [x] Set dimensions
- [x] Handle nullables
- [x] Handle enumerations
- [ ] Set filters
- [ ] Set duplicates

See also #2406

**Comment by johnkerl** [comment]
This issue exists as a coat-hanger for any schema-releated issues that may (or may not) arise while @eddelbuettel is porting @nguyenv 's C++ and Python/pybind11 work to R/Rcpp.
