### ISSUE TITLE
[ci] Refine CI-trigger paths

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2230]
See for example https://github.com/single-cell-data/TileDB-SOMA/pull/2229#issuecomment-1983648145

**Comment by ryan-williams** [comment]
TODO: figure out why https://github.com/single-cell-data/TileDB-SOMA/pull/1960/commits/804c58de0f87483d496a76f0ff615fd4f693f891 triggered CI jobs (random commit to a WIP branch, didn't expect any GHAs)

**Comment by johnkerl** [comment]
@ryan-williams is this task complete?

**Comment by ryan-williams** [comment]
I think so, can re-open if anyone has ideas for further trigger refinements, but I believe I added the ones we discussed (and a few others that seemed sensible).
