### ISSUE TITLE
[python/c++] Correctly write and read back arrays using C++ bindings (parent)

### ISSUE THREAD

**Issue by nguyenv** [single-cell-data/TileDB-SOMA#2241]
Parent: #1632

- [x] #2426
- [x] #2427
- [x] #2428
- [x] #2429

**Comment by johnkerl** [comment]
This will be subtasked per @nguyenv , per class (`DataFrame`, `SparseNDArray`, `DenseNDArray`).

**Comment by johnkerl** [comment]
This can be closed when the four PRs here are merged
