### ISSUE TITLE
[r] Refactor to make use of `nanoarrow`

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2249]
- Updates vendored `nanoarrow` files to the recent release 0.4.0
- Refactors internals to rely more on `nanarrow` facilitating conversion to Arrow object without build-time dependencies on Arrow itself

**Comment by johnkerl** [comment]
[sc-42316]

**Comment by eddelbuettel** [comment]
Done via #2188
