### ISSUE TITLE
[python] Importing `tiledb` before `tiledbsoma` leads to segfault in `clib.SOMAObject.open` on MacOS

### ISSUE THREAD

**Issue by ryan-williams** [single-cell-data/TileDB-SOMA#2293]
Repro at [ryan-williams/tiledb-repros@import-segfault](https://github.com/ryan-williams/tiledb-scratch/tree/import-segfault):

Importing `tiledb` before `tiledbsoma` causes `open` to segfault on macOS:

```python
import tiledb  # ❌ This unused import causes a segfault in `open` below
import tiledbsoma
tiledbsoma.Experiment.open("pbmc-small")  # ❌ segfaults
```

Click each ✅/❌ to see a full log in Github Actions:
<table>
  <tr>
    <th></th>
    <th colspan="2">
      <code>tiledb</code>,
      <code>tiledbsoma</code>
      versions
    </th>
  </tr>
  <tr>
    <th>Arch/OS</th>
    <th>2.20.1, 1.8.1</th>
    <th>2.21.1, <a href="https://github.com/single-cell-data/TileDB-SOMA/tree/e6822fb4f0a02256ceb487448bd0d13b073946c8"><code>e6822fb</code></a></th>
  </tr>
    <tr>
        <th>Ubuntu</th>
        <td>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457612701/job/23169976714">✅</a>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457612701/job/23170035198">✅</a>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457612701/job/23170201677">✅</a>
        </td>
        <td>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457048651/job/23168150126#step:9:20">✅</a>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457048651/job/23169324907">✅</a>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457048651/job/23170218569">✅</a>
        </td>
    </tr>
    <tr>
        <th>Intel Mac</th>
        <td>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457636565/job/23170045934#step:10:20">✅</a>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457636565/job/23170117058#step:10:15">✅</a>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457636565/job/23170199274#step:10:21">❌</a>
        </td>
        <td>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8455805326/job/23164146330#step:9:23">❌</a>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8455805326/job/23168162572#step:9:23">❌</a>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8455805326/job/23170224565#step:9:21">❌</a>
        </td>
    </tr>
    <tr>
        <th>M1 Mac</th>
        <td>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457661549/job/23170125204#step:10:21">❌</a>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457661549/job/23170153485#step:10:21">❌</a>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457661549/job/23170208212#step:10:21">❌</a>
        </td>
        <td>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8455811514/job/23164166618#step:9:23">❌</a>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8455811514/job/23168981363#step:9:23">❌</a>
          <a href="https://github.com/ryan-williams/tiledb-scratch/actions/runs/8455811514/job/23170229995#step:9:21">❌</a>
        </td>
    </tr>
</table>

## Notes
- M1 macs always fail
- Intel macs sometimes fail
  - ≈100% of runs fail on 2.21.1 / `main` ([`e6822fb`])
  - ≈50% of runs fail on 2.20.1 / 1.8.1:
    - The successful runs log this error:
      ```
      Error: 3-27 14:51:23.364] [Process: 2862] [error] [1711551083364855000-Global] TileDB internal: mutex lock failed: Invalid argument
      ```
      but nevertheless exit 0 ([example][intel mac ok error msg 1], [example][intel mac ok error msg 2])
    - I've also seen that error message on failing M1 mac runs; not sure if it's related to the segfault.

[Example versions](https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457661549/job/23170208212#step:8:12) from a failing 2.20.1 ARM Mac run:
```
tiledbsoma.__version__        1.8.1
TileDB-Py tiledb.version()    (0, 26, 4)
TileDB core version           2.20.1
libtiledbsoma version()       libtiledb=2.20.1
python version                3.11.8.final.0
OS version                    Darwin 22.6.0
Darwin Mac-1711560806153.local 22.6.0 Darwin Kernel Version 22.6.0: Sun Dec 17 22:[13](https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457661549/job/23170208212#step:8:14):13 PST 2023; root:xnu-8796.[14](https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457661549/job/23170208212#step:8:15)1.3.703.2~2/RELEASE_ARM64_VMAPPLE arm64
```

[Example versions](https://github.com/ryan-williams/tiledb-scratch/actions/runs/8455811514/job/23170229995#step:7:12) from a failing 2.21.1 ARM Mac run:
```
tiledbsoma.__version__        1.9.0rc0
TileDB-Py tiledb.version()    (0, 27, 1)
TileDB core version           2.21.1
libtiledbsoma version()       libtiledb=2.21.1
python version                3.11.8.final.0
OS version                    Darwin 22.6.0
Darwin Mac-17115604467[13](https://github.com/ryan-williams/tiledb-scratch/actions/runs/8455811514/job/23170229995#step:7:14).local 22.6.0 Darwin Kernel Version 22.6.0: Sun Dec 17 22:13:13 PST 2023; root:xnu-8796.[14](https://github.com/ryan-williams/tiledb-scratch/actions/runs/8455811514/job/23170229995#step:7:15)1.3.703.2~2/RELEASE_ARM64_VMAPPLE arm64
```

Previously discussed at https://github.com/single-cell-data/TileDB-SOMA/pull/1960#discussion_r1528881351 / #2286.

[`e6822fb`]: https://github.com/single-cell-data/TileDB-SOMA/tree/e6822fb4f0a02256ceb487448bd0d13b073946c8
[intel mac ok error msg 1]: https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457636565/job/23170045934#step:10:15
[intel mac ok error msg 2]: https://github.com/ryan-williams/tiledb-scratch/actions/runs/8457636565/job/23170117058#step:10:15

**Comment by ryan-williams** [comment]
(Overhauled title and description with deeper repro / analysis)

**Comment by ryan-williams** [comment]
Discussing with @johnkerl, most likely this issue will go away as libtiledbsoma replaces TileDB-Py use, so unlikely we'll try to root-cause it further.

**Comment by ryan-williams** [comment]
I'm seeing a similar segfault again ([example GHA](https://github.com/ryan-williams/tiledb-scratch/actions/runs/11563588765/job/32187180592#step:10:17)):
- macOS 14 (ARM)
- tiledbsoma==1.14.5
- `import tiledb` before `import tiledbsoma`
- Attempt to open Census

It doesn't seem to repro on `main` or `release-1.15`, which have removed `tiledb` as a `tiledbsoma` dependency, so hopefully this class of issue is fixed for good, though it's possible it will still crop up for folks using <1.15.

**Comment by johnkerl** [comment]
Agreed -- 1.15, which will have #2752, is precisely the fix for this issue.

**Comment by johnkerl** [comment]
Given that 1.15 is the fix for this, we will re-open if there are any reoccurrences at >= 1.15.
