### ISSUE TITLE
TileDB-SOMA 1.9 release

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2311]
Tracks things needing to be done to get there.

* Blockers: https://github.com/single-cell-data/TileDB-SOMA/issues?q=is%3Aissue+is%3Aopen+label%3Ablocks-1.9
* This will cause the [Conda pre-check PR](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases) to fail: https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/108#issuecomment-2018088174

[[sc-43172]](https://app.shortcut.com/tiledb-inc/story/43172)
[[sc-43511]](https://app.shortcut.com/tiledb-inc/story/43511)
[[sc-43673]](https://app.shortcut.com/tiledb-inc/story/43673)

**Comment by jdblischak** [comment]
> This will cause the [Conda pre-check PR](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases) to fail: https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/108#issuecomment-2018088174

This conda solver error was specific to tiledb 2.20. The recently successful https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/110 confirmed that it did not affect tiledb 2.21

Also, I fixed the issue with tiledb 2.20, so the nightlies are working again (https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/108#issuecomment-2020565393)
