### ISSUE TITLE
[python/ci] Issues with typeguard 4.2

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2312]
We've been at 4.1.5 since last week. Meanwhile typeguard 4.2 was just released and we are seeing in CI

```
TypeError: issubclass() argument 2 cannot be a parameterized generic
```

@ryan-williams will either fix for typeguard 4.2, or, pin our repo to typeguard 4.1.5.

**Comment by ryan-williams** [comment]
#2313 pinned 4.1.5

Looking into getting 4.2.x working
