### ISSUE TITLE
[c++] Create a `cmake` rule for `nanoarrow`

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2408]
Following on from #2362:

* `nanoarrow.c` and `nanoarrow.h` are vendored
* They contain a bit of `sprintf` with destination named `out` which is, from the compiler's point of view, possibly null
* Different compilers handle this differently:
  * No problem in our main CI
  * Error in our wheels-build CI, fixed on #2398 
  * Another build failure on Centos 8 with GCC 8.5: 2402
    * As found on #2402, adding `-D TILEDBSOMA_ENABLE_WERROR=OFF` at `scripts/bld` did not result in `-Werror` being avoided at `nanoarrow.c`
* The bigger issue:
  * `nanoarrow.c` -- and _only_ `nanoarrow.c` -- needs to be compiled without `-Werror`, and _by default_
  * This will take some `cmake` work

**Comment by johnkerl** [comment]
@nguyenv is our TileDB-SOMA `cmake` expert: yet I want to free up as much of her time as possible toward closing out #1632, upon which much depends.

I'm not a `cmake` expert by any means but am willing to attempt to factor out a `cmake` file for `nanoarrow.c`, and will ask for help as needed.

**Comment by eddelbuettel** [comment]
Note that there already is _some_ support upstream:

- https://github.com/apache/arrow-nanoarrow/tree/main/examples/cmake-scenarios (more featureful)
- https://github.com/apache/arrow-nanoarrow/tree/main/examples/cmake-minimal (more minimal)

and there is some 'moar' cmake support by other projects in a recent PR / like to be in 0.5.0

- https://github.com/apache/arrow-nanoarrow/issues/350

What may be the real desired outcome here is a solid `FindNanoarrow_EP.cmake` in `libtiledbsoma/cmake/Modules/` where we could also pin the release we want (we are currently at 0.4.0).
