### ISSUE TITLE
[python] `UnboundLocalError`: local variable `soma_df` referenced before assignment

### ISSUE THREAD

**Issue by jggatter** [single-cell-data/TileDB-SOMA#2499]
Hi guys,

I just encountered this error when trying to re-ingest a SOMA that I had just deleted recursively:
`UnboundLocalError: local variable 'soma_df' referenced before assignment`

https://github.com/single-cell-data/TileDB-SOMA/blob/65e6bafa808d06ebdb5aa79d7f5dc83e8af422a8/apis/python/src/tiledbsoma/io/ingest.py#L1206

I imagine the intention is to use `df_uri` here.

We're just about up-to-date on our TileDB stack! We'll be deploying the new set up to users soon.

Best,
James

**Comment by johnkerl** [comment]
Thanks @jggatter -- on it! :)

**Comment by johnkerl** [comment]
[sc-46790]
