### ISSUE TITLE
[python] Docs for `SparseNDArrayRead` class missing on ReadTheDocs

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2502]
https://tiledbsoma.readthedocs.io/en/latest/python-api.html

**Comment by johnkerl** [comment]
This will be a nice quick one for @ryan-williams for next sprint

**Comment by ryan-williams** [comment]
I see `SparseNDArrayRead` listed under "Classes" at https://tiledbsoma.readthedocs.io/en/latest/python-tiledbsoma.html#classes, as I'd expect.

SparseNDArray [class doc](https://tiledbsoma.readthedocs.io/en/latest/_autosummary/tiledbsoma.SparseNDArray.html#tiledbsoma.SparseNDArray) also looks normal / analogous to [DenseNDArray](https://tiledbsoma.readthedocs.io/en/latest/_autosummary/tiledbsoma.DenseNDArray.html#tiledbsoma.DenseNDArray).

Can you be more specific about what's missing? Or perhaps something was fixed?

**Comment by johnkerl** [comment]
@aaronwolen can you help? I believe you reported the problem (IIRC)

**Comment by ryan-williams** [comment]
Thanks @nguyenv for pointing out: I was mixing up [`SparseNDArray`](https://github.com/single-cell-data/TileDB-SOMA/blob/1.10.2/apis/python/src/tiledbsoma/_sparse_nd_array.py#L49) (which [is in the docs](https://tiledbsoma.readthedocs.io/en/latest/_autosummary/tiledbsoma.SparseNDArray.html#tiledbsoma.SparseNDArray)) and [`SparseNDArrayRead`](https://github.com/single-cell-data/TileDB-SOMA/blob/1.10.2/apis/python/src/tiledbsoma/_sparse_nd_array.py#L431) (which is indeed missing). Looking into it…
