### ISSUE TITLE
Ingesting Multiple H5ad Projects into a single SOMA Object

### ISSUE THREAD

**Issue by danishzmalik** [single-cell-data/TileDB-SOMA#2569]
This is regarding a query we have related to the ingestion of h5ad files to SOMA experiments. 
We have data from around 400 in-house Single Cell Studies in h5ad format, stored in an s3 bucket.
Our end goal is to create an application where a user can select a study from a list of of our own studies and have its visualization rendered. 

For this we have been trying to use tiledb.soma python package on databricks. 
We have been successful in converting individual h5ads to the SOMA format, however in an attempt to ingest 2 h5ad files to the same SOMA experiment, we faced an issue where  
`experiment.obs.read().concat().to_pandas()` returned data from only the first file that was ingested. 
                                                                                                                                                              
The following function was used for the ingestion:

```
tiledbsoma.io.from_h5ad(
experiment_uri="/tmp/soma_object",
measurement_name="RNA",
input_path = H5AD_URI,
ingest_mode= “resume”

)
```
Where the ingest mode was set to ‘resume’.

Is there a way to achieve this? And are there any pre-reqs that we need to consider? E.g. Same columns (obs) in every file

**Comment by johnkerl** [comment]
Hi @danishzmalik ! Indeed, we have an "append mode" designed and well-suited for this very purpose. @ryan-williams is taking some notebook example material and formatting it for more broad use -- we'll be in touch soon!

**Comment by johnkerl** [comment]
Related: https://github.com/chanzuckerberg/cellxgene-census/issues/1132

**Comment by johnkerl** [comment]
Note for @ryan-williams: 
https://github.com/single-cell-data/TileDB-SOMA/pull/2571#pullrequestreview-2061916226

**Comment by ryan-williams** [comment]
Hi @danishzmalik, [looks like](https://github.com/single-cell-data/TileDB-SOMA/issues/2619) you found the tutorial notebook added above, just wanted to make sure you caught "part 2" ("[Ingesting multiple datasets to a SOMA Experiment](https://tiledbsoma.readthedocs.io/en/stable/notebooks/tutorial_soma_append_mode.html#Ingesting-multiple-datasets-to-a-SOMA-Experiment)", #2582), which demonstrates ingesting multiple h5ads from scratch (as opposed to adding single h5ads onto an existing SOMA).

I believe this is done, but feel free to comment/reopen if you have further q's/issues.
