### ISSUE TITLE
Develop guidance for support for older `linux-x86` processor variants

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2580]
From time to time we have questions like this:
https://github.com/chanzuckerberg/cellxgene-census/issues/1121

Issues involved:

* TileDB Core, TileDB-Py, TileDB-R, and TileDB-SOMA (Python and R) have precompiled binaries for OS the major architecture:
  * `linux-x86` fully supported
  * `macos-x86` fully supported
  * `macos-arm64` fully supported
  * `linux-aarch64` support is forthcoming: #2482 
* Issue here is support for processor _variants_ within `linux-x86`
  * Symptom is `Illegal instruction (core dumped)` ([see here for example](2482))
  * The binaries we have pre-compiled for include certain instruction sets
  * Sometimes users run in environments not containing support for some newer instructions
 
Work to do:

* We need to decide, and document, which processor variants we support -- and "support" means:
  * Necessarily people will need to build from source -- since our precompiled binaries aren't right for older variants
  * People will need clear build-from-source instructions
* We need to decide, and document, which processor variants we don't support -- and that means:
  * Listing out processor variants for which we don't have a suggested recipe, and for which we don't intend to develop one

[[sc-47640]](https://app.shortcut.com/tiledb-inc/story/47640/develop-guidance-for-support-for-older-linux-x86-processor-variants)

**Comment by eddelbuettel** [comment]
One small addition: The TileDB-R package has long used dual binary artifacts for x86_64 Linux provided by TileDB Embedded at each release. These artifacts differentiate between default and 'no AVX2' (same as the issue that spawned this) so on builds from R where artifacts are pulled in, the non-AVX2 machines are accomodated.

**Comment by eddelbuettel** [comment]
@rcurrie Awesome.  If it is still fresh in your mind please do feel free to drop us a few bullet points about possible plusses or minusses of our docs with respect to building from source.

**Comment by rcurrie** [comment]
@eddelbuettel Docs work as advertised! Maybe add something like this (which I've added to the repo I'm working on using cellxgene-census):

TileDB-SOMA python wheels assume AVX2 generating an ```illegal hardware instruction (core dumped)``` on CPUs without AVX2 (```cat /proc/cpuinfo | grep avx2 } head -1```). To run on non-AVX2 cpus, build from source and install into your existing python environment or active virtualenv via:
```
git clone https://github.com/single-cell-data/TileDB-SOMA.git
pip install -v -e TileDB-SOMA/apis/python
```
