### ISSUE TITLE
[python] RTD version issues

### ISSUE THREAD

**Issue by ryan-williams** [single-cell-data/TileDB-SOMA#2603]
[RTD builds](https://readthedocs.org/projects/tiledbsoma/builds/) were broken from 1.7.0 until 1.11.0. They're fixed as of #2560/#2563, but some cleanup/mitigation is warranted:

1. Many old versions in the RTD version picker (1.0.x through 1.6.x)
2. Missing recent versions in the RTD version picker (1.7.x through 1.10.x)
3. "Stable" still resolves to 1.6.2

## GC'ing old versions?

RTD version picker currently looks like:

![image](https://github.com/single-cell-data/TileDB-SOMA/assets/465045/d8d7a0d0-9109-41ad-ab8b-b6de268b096c)

I'm guessing most of those older versions should be hidden… everything prior to 1.11.x? Unfortunately, we don't have an easy way of creating doc-builds for 1.7.x 1.10.x…

## Building recent versions
Ideally, we might just show the most recent versions from the last 3 minor-version branches (currently 1.11.1, 1.10.2, 1.9.5), along with "latest" (`main`) and "stable" (alias for "most recent version").

However, RTD build was still broken as of 1.10.2 and 1.9.5. I'm not sure of a way to get 1.{9,10}.x represented, other than cutting a 1.10.3 and 1.9.6.

Maybe there's a way to cherrypick #2560/#2563 onto the `release-1.{9,10}` branches, and tell RTD to build from them, and label them as 1.10.2/1.9.5 (despite those Git tags already existing and pointing elsewhere)?

## Fixing "stable"

The "stable" build (latest release tag) was still broken ca. 1.11.1. #2563 fixes it, but landed after 1.11.1, so [tiledbsoma.readthedocs.io/en/stable](https://tiledbsoma.readthedocs.io/en/stable) is still showing docs from 1.6.2.

"stable" will be fixed as of the next release; @johnkerl and I were debating a 1.11.2 release to trigger this, vs. waiting for the next organic release.

Same q applies as above re: whether we can trick RTD into displaying a "1.11.1" that's not actually built from that Git tag (but rather a branch that includes some cherrypicks on top of the 1.11.1 tag).

I tried triggering a new "stable" build yesterday, but [it failed](https://readthedocs.org/projects/tiledbsoma/builds/24435539/), because it's still checking out a pre-#2563 SHA.

**Comment by ryan-williams** [comment]
I think I'll start by hiding all versions from the picker except 1.11.0, 1.11.1, and "latest." 
 That seems to be the shortest path to mitigating obvious/user-facing brokenness.

As we cut further `1.{11,12,13}.x` releases, we'll start to have some reasonable history and a working "stable" alias.

I'll leave the older versions "active" but "hidden," so if people really want them, they can URL-munge.

**Comment by johnkerl** [comment]
As in part discussed yesterday:

* Very most we need visible is current and two back (1.11, 1.10 and 1.9 if they existed), and all micros for them
  * I'm not deeply motivated to tag 1.10.next or 1.9.next solely to make docs appear there
  * Let's just have this unbroken and move forward
  * Later today we'll have 1.11.2 docs
  * In a couple weeks we'll have 1.11.2 and 1.12.0 docs
  * Later we'll have 1.11.2, 1.12.0, and 1.13.0 docs
  * Once 1.14 comes out we can hide 1.11
  * Steady state from thenon
* Hide everything older
* I'll tag a 1.11.2 today to make new docs appear

**Comment by ryan-williams** [comment]
I've cleaned up the available versions in the picker:

![image](https://github.com/single-cell-data/TileDB-SOMA/assets/465045/da3f5142-e0e9-4747-9965-29ca5ef622e2)

(using [rtd-cli](https://pypi.org/project/rtd-cli/) 😎).

Older versions are still available, at URLs like [tiledbsoma.readthedocs.io/en/1.6.2](https://tiledbsoma.readthedocs.io/en/1.6.2/).

Closing this, we should start getting new versions and re-filling the RTD version picker automatically, as new releases happen.

**Comment by ryan-williams** [comment]
With the 1.11.2 release yesterday, "stable" [built successfully](https://readthedocs.org/projects/tiledbsoma/builds/24449698/), so I've restored it as the default version at [tiledbsoma.readthedocs.io](https://tiledbsoma.readthedocs.io/).

Current version picker status:
![image](https://github.com/single-cell-data/TileDB-SOMA/assets/465045/0316f22c-9b8f-43fb-96f6-cd17965cdf19)
