### ISSUE TITLE
H5ad to Soma Ingestion on Databricks (POSIX Error)

### ISSUE THREAD

**Issue by danishzmalik** [single-cell-data/TileDB-SOMA#2619]
Im trying to ingest multiple h5ad files to a single SOMA object. Using the following link:
https://tiledbsoma.readthedocs.io/en/latest/notebooks/tutorial_soma_append_mode.html

Im doing this on databricks. Things are working fine when I set the SOMA experiment path to the cluster driver storage. 
But my goal is to create the experiment on an s3 bucket which is mounted on dbfs. 

While doing so im getting the following error:
![image](https://github.com/single-cell-data/TileDB-SOMA/assets/8587744/0b5a54d9-ff50-4676-95e2-6f91b59a186a)

Config:

```
cfg = tiledb.Config({"vfs.s3.no_sign_request": True, "vfs.file.posix_file_permissions":644})
vfs = tiledb.VFS(config=cfg)
```

Ingestion function:
```
#intial load
tiledbsoma.io.from_anndata(
experiment_uri = "/dbfs/mnt/s3_bucket_alias/soma_object/",
anndata=  adata,
measurement_name="RNA",

)
```

Require some guidance regarding this.

**Comment by eddelbuettel** [comment]
Hi @danishzmalik -- Thanks for filing an issue.   As you may know, we build, test and run rather extensively on AWS S3, GCS and Azure FS.  We test the S3 behavior via the Minio driver.  I do not think we have any access to the databricks emulation of S3 so this may be difficult for us to replicate and debug.  We will discuss and may come back asking you to run with specific debug flags.

**Comment by danishzmalik** [comment]
HI @eddelbuettel , the issue was indeed with the url string. I tried giving the full s3 path i.e. s3:// , instead of the dbfs mount location, and it worked. Thank you

**Comment by eddelbuettel** [comment]
@danishzmalik -- thanks for reporting back, confirming and closing the circle.  The issue will provide a useful documentation snippet until we get around to including platforms such as databricks in our regular tests.
