### ISSUE TITLE
[c++] `IntIndexer` causes a memory leak 

### ISSUE THREAD

**Issue by ebezzi** [single-cell-data/TileDB-SOMA#2653]
**Describe the bug**
Using the SOMA `IntIndexer` is causing a memory leak which isn't present when using the regular Pandas indexer.

**To Reproduce**
```
import gc

import numpy as np

import cellxgene_census
from cellxgene_census.experimental.pp._highly_variable_genes import _get_batch_index
import tiledbsoma as soma

experiment_name = "homo_sapiens"
batch_key = ["suspension_type", "assay"]

census = cellxgene_census.open_soma(census_version="2023-12-15")
query = census["census_data"][experiment_name].axis_query(measurement_name="RNA")

batch_index = _get_batch_index(query, batch_key=batch_key)
batch_indexer = soma.IntIndexer(batch_index.index.to_numpy(), context=query.experiment.context).get_indexer
for i, arrow_tbl in enumerate(query.X("raw").tables()):
    print(i)
    _batch_take = batch_indexer(arrow_tbl["soma_dim_0"])
    gc.collect()
```

**Versions (please complete the following information):**
The bug is present on the most recent tiledbsoma version.

**Comment by ivirshup** [comment]
I managed to cut down the reproducer a little further, and think I've identified where the leak lives.

Starting with a similar setup:

```python
import numpy as np
import pyarrow as pa

import cellxgene_census
from cellxgene_census.experimental.pp._highly_variable_genes import _get_batch_index
import tiledbsoma as soma

rng = np.random.default_rng()

experiment_name = "homo_sapiens"
batch_key = ["suspension_type", "assay"]

census = cellxgene_census.open_soma(census_version="2023-12-15")
query = census["census_data"][experiment_name].axis_query(measurement_name="RNA")

batch_index = _get_batch_index(query, batch_key=batch_key)
batch_indexer = soma.IntIndexer(batch_index.index.to_numpy(), context=query.experiment.context).get_indexer
```

This does not cause memory to grow:

```python
%load_ext memory_profiler
%memit
# peak memory: 3287.59 MiB, increment: 0.00 MiB
```

```python
for i in range(10_000):
    x = rng.choice(len(batch_index), 100_000, replace=False)
    _ = batch_indexer(x)
```

```python
%load_ext memory_profiler
%memit
# peak memory: 3288.59 MiB, increment: 0.00 MiB
```

But if we instead pass the array as a pyarrow array, we see memory usage increase:

```python
for i in range(10_000):
    x = pa.array(rng.choice(len(batch_index), 100_000, replace=False))
    _ = batch_indexer(x)
```

```python
%load_ext memory_profiler
%memit
# peak memory: 10932.71 MiB, increment: 0.00 MiB
```

We can see that there is a branch for this here: https://github.com/single-cell-data/TileDB-SOMA/blob/765a12c4eaecb232f5af13c839f7a7194d9b3a01/apis/python/src/tiledbsoma/_indexer.py#L82-L86

Which ends up calling the c++ code here: https://github.com/single-cell-data/TileDB-SOMA/blob/765a12c4eaecb232f5af13c839f7a7194d9b3a01/apis/python/src/tiledbsoma/reindexer.cc#L86

Which is probably where the leak is.

**Comment by johnkerl** [comment]
Repro: https://gist.github.com/johnkerl/120a2ffa329726a963d8a6bbc7dfa161

[[sc-48535]](https://app.shortcut.com/tiledb-inc/story/48535/c-memory-leak-in-reindexer-when-presented-with-array-array)
