### ISSUE TITLE
[r] Replace `vfs.is_dir` with `SOMADataFrame::exists` et al.

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2714]
Follow-up from merged PR #2704.

As discussed in detail here: https://github.com/single-cell-data/TileDB-SOMA/pull/2704#discussion_r1635386307

* A VFS is-dir check -- in R, Python, or C++ -- will work for local-disk and S3 URIs but not `tiledb://...` URIs
* `exists` -- in R, Python, or C++ -- is the method within the SOMA API that works regardless of storage backend. It does not assume VFS.
  * In `libtiledbsoma`, these are `SOMADataFrame::exists`, `SOMASparseNDArray::exists`, `SOMADenseNDArray::exists`
  * As noted at https://github.com/single-cell-data/TileDB-SOMA/pull/2704#discussion_r1635386307 we intentionally do not unit-test `tiledb://...` URIs within this open-source repository.

cc @eddelbuettel @nguyenv

**Comment by eddelbuettel** [comment]
Done in #2803
