### ISSUE TITLE
[c++] `libtiledbsoma`'s `SOMADataFrame.exists()` needs to accept a context

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2793]
Mirrors [sc-49546](https://app.shortcut.com/tiledb-inc/story/49546/libtiledbsoma-clib-somadataframe-exists-needs-to-accept-a-context)

Needs Python and R bindings affected as well.

**Comment by nguyenv** [comment]
https://github.com/single-cell-data/TileDB-SOMA/pull/2794
