### ISSUE TITLE
SOMAError: SOMAError: Incorrect type for attribute name: Constant(value='<column value>') - While Converting SOMA query to Anndata

### ISSUE THREAD

**Issue by danishzmalik** [single-cell-data/TileDB-SOMA#2832]
**Describe the bug**

I have been following tiledb_soma's append mode tutorial and want to 
- read in a SOMA object
- create a query 
- convert the query to anndata
- visualize it using scanpy.

I am getting an error while running the following query:
**query.to_anndata(X_name="data")**

Error: SOMAError: SOMAError: Incorrect type for attribute name: Constant(value='GSM4601695')

This is what my soma obs schema looks like (In order to get rid of data type conflicts while using append mode, I converted all columns to string)

```
soma_joinid                             int64
obs_id                                 object
orig.ident                             object
nFeature_RNA                           object
nCount_RNA                             object
percent.mt                             object
high_mt                                object
high_ct                                object
basic_qc                               object
sample_id                              object
author_cell_type                       object
author_cell_type_cell_ontology_id      object
author_cell_type_cell_ontology_name    object
study_id                               object
sample_name                            object
donor_id                               object
sample_type                            object
dtype: object
```

Would I have to convert certain columns back to particular data types? Or could this be due to something else?

**Code**
```
%pip install scanpy tiledbsoma anndata
dbutils.library.restartPython()

import tiledbsoma
import tiledbsoma.io
import tiledb
import anndata as ad
import scanpy as sc

cfg = tiledb.Config({"vfs.s3.no_sign_request": True})
vfs = tiledb.VFS(config=cfg)

experiment = tiledbsoma.Experiment.open("/dbfs/mnt/soma_object/")

query = experiment.axis_query(
    measurement_name="RNA",
    obs_query=tiledbsoma.AxisQuery(
        value_filter="orig.ident == 'GSM4601695'",
    ),
    var_query=tiledbsoma.AxisQuery(
        value_filter="basic_qc == 'PASS'",
    ),
)

pbmc3k = query.to_anndata(X_name="data")

```

**Versions (please complete the following information):**
 - TileDB-SOMA version:1.12.3
 - Databricks Runtime 15

**Additional context**
**Error Trace**

```
SOMAError: SOMAError: Incorrect type for attribute name: Constant(value='GSM4601695')

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-1d74558f-7d1c-4375-ac89-6a65366146d0/lib/python3.11/site-packages/somacore/query/query.py:299, in ExperimentAxisQuery.to_anndata(self, X_name, column_names, X_layers, obsm_layers, obsp_layers, varm_layers, varp_layers)
    268 def to_anndata(
    269     self,
    270     X_name: str,
   (...)
    277     varp_layers: Sequence[str] = (),
    278 ) -> anndata.AnnData:
    279     """
    280     Executes the query and return result as an ``AnnData`` in-memory object.
    281 
   (...)
    297     Lifecycle: maturing
    298     """
--> 299     return self._read(
    300         X_name,
    301         column_names=column_names or AxisColumnNames(obs=None, var=None),
    302         X_layers=X_layers,
    303         obsm_layers=obsm_layers,
    304         obsp_layers=obsp_layers,
    305         varm_layers=varm_layers,
    306         varp_layers=varp_layers,
    307     ).to_anndata()
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-1d74558f-7d1c-4375-ac89-6a65366146d0/lib/python3.11/site-packages/somacore/query/query.py:404, in ExperimentAxisQuery._read(self, X_name, column_names, X_layers, obsm_layers, obsp_layers, varm_layers, varp_layers)
    397 varm_ft = self._threadpool.submit(
    398     _read_axis_mappings, self._axism_inner_ndarray, _Axis.VAR, varm_layers
    399 )
    400 varp_ft = self._threadpool.submit(
    401     _read_axis_mappings, self._axisp_inner_ndarray, _Axis.VAR, varp_layers
    402 )
--> 404 obs_table, var_table = self._read_both_axes(column_names)
    406 x_matrices = {
    407     _xname: _fast_csr.read_csr(
    408         all_x_arrays[_xname],
   (...)
    413     for _xname in all_x_arrays
    414 }
    416 x = x_matrices.pop(X_name)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-1d74558f-7d1c-4375-ac89-6a65366146d0/lib/python3.11/site-packages/somacore/query/query.py:450, in ExperimentAxisQuery._read_both_axes(self, column_names)
    440 obs_ft = self._threadpool.submit(
    441     self._read_axis_dataframe,
    442     _Axis.OBS,
    443     column_names,
    444 )
    445 var_ft = self._threadpool.submit(
    446     self._read_axis_dataframe,
    447     _Axis.VAR,
    448     column_names,
    449 )
--> 450 return obs_ft.result(), var_ft.result()
File /usr/lib/python3.11/concurrent/futures/_base.py:456, in Future.result(self, timeout)
    454     raise CancelledError()
    455 elif self._state == FINISHED:
--> 456     return self.__get_result()
    457 else:
    458     raise TimeoutError()
File /usr/lib/python3.11/concurrent/futures/_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None
File /usr/lib/python3.11/concurrent/futures/thread.py:58, in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-1d74558f-7d1c-4375-ac89-6a65366146d0/lib/python3.11/site-packages/somacore/query/query.py:480, in ExperimentAxisQuery._read_axis_dataframe(self, axis, axis_column_names)
    477     added_soma_joinid_to_columns = True
    479 # Do the actual query.
--> 480 arrow_table = axis_df.read(
    481     axis_query.coords,
    482     value_filter=axis_query.value_filter,
    483     column_names=query_columns,
    484 ).concat()
    486 # Update the cache if needed. We can do this because no matter what
    487 # other columns are queried for, the contents of the ``soma_joinid``
    488 # column will be the same and can be safely stored.
    489 if not joinids_cached:
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-1d74558f-7d1c-4375-ac89-6a65366146d0/lib/python3.11/site-packages/tiledbsoma/_dataframe.py:412, in DataFrame.read(***failed resolving arguments***)
    402 sr = clib.SOMADataFrame.open(
    403     uri=handle.uri,
    404     mode=clib.OpenMode.read,
   (...)
    408     timestamp=handle.timestamp and (0, handle.timestamp),
    409 )
    411 if value_filter is not None:
--> 412     sr.set_condition(QueryCondition(value_filter), handle.schema)
    414 self._set_reader_coords(sr, coords)
    416 # # TODO: batch_size
```

**Comment by johnkerl** [comment]
Fixedin #2831 -- thank you @danishzmalik !

**Comment by danishzmalik** [comment]
Hi @johnkerl,
Thank you

I installed tiledbsoma==1.12.3 again, and tried the above approach.
Im still getting the same error.

**Comment by johnkerl** [comment]
Hi @danishzmalik -- these will go out with the upcoming 1.13.0 (1.12.3 was tagged before this PR was merged).

**Comment by danishzmalik** [comment]
@johnkerl Got it , Thank you 
Would you be able to give an expected date for the new release?

**Comment by danishzmalik** [comment]
Hi @johnkerl 
I upgradeed the tiledb_soma version to 1.13.0 but getting the same error still.
![image](https://github.com/user-attachments/assets/bd0eba17-e3da-4a38-aa6e-179963c87386)

**Full Error Trace:**

> SOMAError: SOMAError: Incorrect type for attribute name: Constant(value='GSM4601695')
> 
> At:
>   /local_disk0/.ephemeral_nfs/envs/pythonEnv-a5261e30-dcce-4ebf-b01e-0f9bcd174ce1/lib/python3.11/site-packages/tiledbsoma/_query_condition.py(137): init_query_condition
>   /local_disk0/.ephemeral_nfs/envs/pythonEnv-a5261e30-dcce-4ebf-b01e-0f9bcd174ce1/lib/python3.11/site-packages/tiledbsoma/_dataframe.py(409): read
>   /local_disk0/.ephemeral_nfs/envs/pythonEnv-a5261e30-dcce-4ebf-b01e-0f9bcd174ce1/lib/python3.11/site-packages/somacore/query/query.py(499): _read_axis_dataframe
>   /usr/lib/python3.11/concurrent/futures/thread.py(58): run
>   /usr/lib/python3.11/concurrent/futures/thread.py(83): _worker
>   /usr/lib/python3.11/threading.py(975): run
>   /usr/lib/python3.11/threading.py(1038): _bootstrap_inner
>   /usr/lib/python3.11/threading.py(995): _bootstrap
> File <command-3618037477376817>, line 1
> ----> 1 pbmc3k = query.to_anndata(X_name="data")
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-a5261e30-dcce-4ebf-b01e-0f9bcd174ce1/lib/python3.11/site-packages/somacore/query/query.py:307, in ExperimentAxisQuery.to_anndata(self, X_name, column_names, X_layers, obsm_layers, obsp_layers, varm_layers, varp_layers, drop_levels)
>     270 def to_anndata(
>     271     self,
>     272     X_name: str,
>    (...)
>     280     drop_levels: bool = False,
>     281 ) -> anndata.AnnData:
>     282     """
>     283     Executes the query and return result as an ``AnnData`` in-memory object.
>     284 
>    (...)
>     305     Lifecycle: maturing
>     306     """
> --> 307     ad = self._read(
>     308         X_name,
>     309         column_names=column_names or AxisColumnNames(obs=None, var=None),
>     310         X_layers=X_layers,
>     311         obsm_layers=obsm_layers,
>     312         obsp_layers=obsp_layers,
>     313         varm_layers=varm_layers,
>     314         varp_layers=varp_layers,
>     315     ).to_anndata()
>     317     # Drop unused categories on axis dataframes if requested
>     318     if drop_levels:
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-a5261e30-dcce-4ebf-b01e-0f9bcd174ce1/lib/python3.11/site-packages/somacore/query/query.py:423, in ExperimentAxisQuery._read(self, X_name, column_names, X_layers, obsm_layers, obsp_layers, varm_layers, varp_layers)
>     416 varm_ft = self._threadpool.submit(
>     417     _read_axis_mappings, self._axism_inner_ndarray, _Axis.VAR, varm_layers
>     418 )
>     419 varp_ft = self._threadpool.submit(
>     420     _read_axis_mappings, self._axisp_inner_ndarray, _Axis.VAR, varp_layers
>     421 )
> --> 423 obs_table, var_table = self._read_both_axes(column_names)
>     425 x_matrices = {
>     426     _xname: _fast_csr.read_csr(
>     427         all_x_arrays[_xname],
>    (...)
>     432     for _xname in all_x_arrays
>     433 }
>     435 x = x_matrices.pop(X_name)
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-a5261e30-dcce-4ebf-b01e-0f9bcd174ce1/lib/python3.11/site-packages/somacore/query/query.py:469, in ExperimentAxisQuery._read_both_axes(self, column_names)
>     459 obs_ft = self._threadpool.submit(
>     460     self._read_axis_dataframe,
>     461     _Axis.OBS,
>     462     column_names,
>     463 )
>     464 var_ft = self._threadpool.submit(
>     465     self._read_axis_dataframe,
>     466     _Axis.VAR,
>     467     column_names,
>     468 )
> --> 469 return obs_ft.result(), var_ft.result()
> File /usr/lib/python3.11/concurrent/futures/_base.py:456, in Future.result(self, timeout)
>     454     raise CancelledError()
>     455 elif self._state == FINISHED:
> --> 456     return self.__get_result()
>     457 else:
>     458     raise TimeoutError()
> File /usr/lib/python3.11/concurrent/futures/_base.py:401, in Future.__get_result(self)
>     399 if self._exception:
>     400     try:
> --> 401         raise self._exception
>     402     finally:
>     403         # Break a reference cycle with the exception in self._exception
>     404         self = None
> File /usr/lib/python3.11/concurrent/futures/thread.py:58, in _WorkItem.run(self)
>      55     return
>      57 try:
> ---> 58     result = self.fn(*self.args, **self.kwargs)
>      59 except BaseException as exc:
>      60     self.future.set_exception(exc)
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-a5261e30-dcce-4ebf-b01e-0f9bcd174ce1/lib/python3.11/site-packages/somacore/query/query.py:499, in ExperimentAxisQuery._read_axis_dataframe(self, axis, axis_column_names)
>     496     added_soma_joinid_to_columns = True
>     498 # Do the actual query.
> --> 499 arrow_table = axis_df.read(
>     500     axis_query.coords,
>     501     value_filter=axis_query.value_filter,
>     502     column_names=query_columns,
>     503 ).concat()
>     505 # Update the cache if needed. We can do this because no matter what
>     506 # other columns are queried for, the contents of the ``soma_joinid``
>     507 # column will be the same and can be safely stored.
>     508 if not joinids_cached:
> File /local_disk0/.ephemeral_nfs/envs/pythonEnv-a5261e30-dcce-4ebf-b01e-0f9bcd174ce1/lib/python3.11/site-packages/tiledbsoma/_dataframe.py:409, in DataFrame.read(***failed resolving arguments***)
>     399 sr = clib.SOMADataFrame.open(
>     400     uri=handle.uri,
>     401     mode=clib.OpenMode.read,
>    (...)
>     405     timestamp=handle.timestamp and (0, handle.timestamp),
>     406 )
>     408 if value_filter is not None:
> --> 409     sr.set_condition(QueryCondition(value_filter), handle.schema)
>     411 self._set_reader_coords(sr, coords)
>     413 # # TODO: batch_size

**Comment by johnkerl** [comment]
Sorry @danishzmalik -- my apologies -- I hadn't sufficiently read your original post.

In your query:
```
        value_filter="orig.ident == 'GSM4601695'",
```

the name `orig.ident` is not a syntactically valid Python name. (It's a fine name in R.)

What you need to do: 
```
        value_filter="attr("orig.ident") == 'GSM4601695'",
```

What we can do is try to generate a better error message in these cases, leading you directly to the `attr("orig.ident")` syntax.

I'll open a tracking issue for this -- previous attempts in this area (#2830, #2831) have been improvements,but not always resulting in total clarity. Since the query language is necessary language-specific -- TileDBSOMA-Py uses Python-like query syntax, and TileDB-SOMA-R uses R-like query syntax -- the query parsers are necessarily language-specific. In particular, we leverage the Python `ast` package, using the Visitor pattern they provide, and we try (e.g. #2830, #2831) to improve the message when our visitor is called.

Anyway, my apologies for the confusion -- the above advice should unblock you -- please let me know if not.

**Comment by danishzmalik** [comment]
@johnkerl  Thanks for the suggestion. Let me try this and get back to you

**Comment by johnkerl** [comment]
@danishzmalik #2864 will go out with our next TileDB-SOMA release, which will either be 1.13.1 or 1.14.0.

**Comment by johnkerl** [comment]
@danishzmalik I believe this is resolved -- if I'm at all mistaken please let me know & I'll reopen -- thank you!
