### ISSUE TITLE
[python] CI `mypy` issue as of 2024-08-05

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2839]
To be investigated:

* Example CI fail https://github.com/single-cell-data/TileDB-SOMA/pull/2834/checks (not just that PR)
  * Lint ok on python 3.11 + ubuntu
  * Lint not ok on python 3.11 + macos
  * Maybe related to mypy 1.11.1 [just dropped a few days ago](https://pypi.org/project/mypy/1.11.1/) -- ? :thinking_face:
* Large-scale post-tag CI fail on [1.13.0rc0](https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.13.0rc0): https://github.com/single-cell-data/TileDB-SOMA/actions/runs/10257321585/job/28378154410

On the one hand this might seem to be a minor annoyance; on the other, it's clouding CI just when we're trying to make the TileDB-SOMA 1.13.0 release. Thus we should solve this sooner than later.

See also #2838 (just created) which has significant narrative by @ryan-williams on it.

Some background info (something that's been in place for a year now, I am reading up on now):

* https://github.com/single-cell-data/TileDB-SOMA/blame/1.13.0rc0/.github/workflows/python-ci-single.yml#L45-L49
* https://github.com/single-cell-data/TileDB-SOMA/pull/756

[[sc-52471]](https://app.shortcut.com/tiledb-inc/story/52471)

**Comment by johnkerl** [comment]
Re-assigning to @ryan-williams

**Comment by ryan-williams** [comment]
At a minimum, actions/setup-python is doing something buggy, I filed https://github.com/actions/setup-python/issues/919.

This issue is live on #2853, until we find a work-around, so I'm reopening it.

**Comment by ryan-williams** [comment]
Issue [persists](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/10292424521/job/28486804717) with `setup-python` cache disabled (and no pre-commit cache found/restored), on both macos and ubuntu. Very strange.

**Comment by ryan-williams** [comment]
I believe I've root-caused this:
- Our pandas dep ([in `setup.py`][pandas]) is unpinned, as is our `pandas-stub` ([in `.pre-commit-config.yaml`][pandas-stub]), meaning we can end up with Pandas 1.x or 2.x (and likewise for the "stub" types in mypy).
- When type-checking, some types must receive a type-arg in Pandas 2.x (`pd.Series[Any]`, `pd.Index[Any]`), but must not in Pandas 1.x (`pd.Series`, `pd.Index`).
- Newly-created environments would pick up `pandas{,-stub}>=2`, and type-checking would pass, as `HEAD` is compatible with Pandas 2.x types.
- However, `setup-python` is (incorrectly, afaict, per [setup-python#919](https://github.com/actions/setup-python/issues/919)) loading old cached environments containing Pandas 1.x, causing the 2.x-compatible types in the codebase to error, failing some GHAs (as well as local environments using.

I believe #2854 actually fixes it; we can keep an eye on `setup-python` caching behavior as well.

[Here][hash-files.py] is a little script I wrote that mimics the GHA `hashFiles` helper ([used in setup-python][setup-python PipCache hashFiles] and in [some of our actions/cache invocations][actions/cache hashFiles]):

```python
#!/usr/bin/env python
import hashlib
import sys


sha256 = hashlib.sha256()

for path in sys.argv[1:]:
    file_sha256 = hashlib.sha256()
    with open(path, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            file_sha256.update(byte_block)
    sha256.update(file_sha256.digest())

print(sha256.hexdigest())
```

[pandas]: https://github.com/single-cell-data/TileDB-SOMA/blob/274c6f49766e19fa645d93cc99e213d0dcca372f/apis/python/setup.py#L334

[pandas-stub]: https://github.com/single-cell-data/TileDB-SOMA/blob/274c6f49766e19fa645d93cc99e213d0dcca372f/.pre-commit-config.yaml#L17

[hash-files.py]: https://gist.github.com/ryan-williams/2e616363c68072bf67cad675fcb18f3b

[setup-python PipCache hashFiles]: https://github.com/actions/setup-python/blob/39cd14951b08e74b54015e9e001cdefcf80e669f/src/cache-distributions/pip-cache.ts#L62-L64

[actions/cache hashFiles]: https://github.com/single-cell-data/TileDB-SOMA/blob/274c6f49766e19fa645d93cc99e213d0dcca372f/.github/workflows/python-ci-single.yml#L49
