### ISSUE TITLE
[python] Add `pytest`  cases for spatial

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#3047]
[[sc-55762]](https://app.shortcut.com/tiledb-inc/story/55762/add-c-catch2-unit-tests-for-spatial)

**Comment by johnkerl** [comment]
@jp-dark do you have anything more needing to be done here? Or can we close this?

**Comment by jp-dark** [comment]
> @jp-dark do you have anything more needing to be done here? Or can we close this?

We should add a test for the Visium ingestor, but I think that deserves a separate task. We can call this one closed.
