### ISSUE TITLE
Python tiledbsoma: SOMACollection set/add issue

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#305]
The collection is intended to be a thin wrapper on top of a map of a name (string) to SOMA object, separate from the underlying storage system namespace.  But the current Python API does not allow "adding" an object to the collection with an arbitrary string name.  Instead, it pulls the collection name from the object itself.  This has several side-effects:
* you can only add an object to a collection once
* you can't alias an object
etc.

I believe the intent of the abstract API is to allow:
* add an object to multiple collections
* add an object to a single collection multiple times
* add an object to a collection with any key name

---

A related issue (likely entangled): why do all SOMA Python objects have a name?  This is not in the data model, and may be contributing to the confusion with collections.  As I understand it, they should have a URI, and are only named in the context of a SOMACollection (and they may have multiple names if placed into multiple collections, and/or into a single collection multiple times).

**Comment by johnkerl** [comment]
> why do all SOMA Python objects have a name? 

@bkmartinjr this is due to the TileDB implementation of SOMA where we use TileDB groups -- every group member has a name and a URI.

To be implemented in TileDB they need to have a name at some level but perhaps we don't need to push the naming decision all the way up to the user -- perhaps we can default it reasonably much of the time.

**Comment by bkmartinjr** [comment]
This was fixed in #343, as part of making the SOMACollection a property subclass of MutableMapping ABC
