### ISSUE TITLE
Python API style - chaining

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#308]
In using the nascent tiledbsoma API, one pattern that I would find useful is if the `create` and related methods returned `self`, allowing chained code like the second line:

> an_arrow_tbl  = pa.Table.from_pandas(pd.DataFrame(...))
>  soma_df = soma.SOMADataFrame(uri).create(an_arrow_tbl.schema).write(an_arrow_table)

Methods that would benefit from this:
* create
* write
* write_from_pandas
* write_all_from_pandas
etc.

This deserves some discussion with Pythonic style experts, of which I am not one....

**Comment by johnkerl** [comment]
Fluent syntax is awesome, and super-easy to code up! I think we should do it (my $0.02) ...

**Comment by johnkerl** [comment]
cc @thetorpedodog

**Comment by thetorpedodog** [comment]
I'm not personally the biggest fan of fluent APIs but I am not morally opposed to them (it's very much a personal thing). The thing I would want to make sure of is that the methods where you get a `self` back make sense. For instance, assuming `some_data_frame.write(...)` writes something *into* the dataframe, getting the dataframe back would certainly make sense, but a method that was like `something_else.write(some_sink)` (where `something_else` is being written to `some_sink`) could sensibly return some information about the write result and might not be as good a candidate for chaining. Based on my (still fairly new) understanding, all the methods you've listed seem like they are reasonable methods to chain.

If only we could jump to Python 3.11 which has the [`Self` annotation](https://docs.python.org/3.11/library/typing.html#typing.Self)!

**Comment by bkmartinjr** [comment]
> make sense

fully agree. There are many methods where it does _not_ make sense (eg, delete).  I am supportive of doing this selectively and iteratively.

**Comment by bkmartinjr** [comment]
This change has been applied to `create()` with good effect.  We should decide if we want to retain that, and if other functions would benefit.  Should be resolved alongside single-cell-data/SOMA#41

**Comment by johnkerl** [comment]
@bkmartinjr @thetorpedodog anything else to cover here, given #663? Otherwise I could close this task.

**Comment by thetorpedodog** [comment]
I don’t think there’s anything else that needs to be done on this at the moment.

**Comment by johnkerl** [comment]
OK -- @bkmartinjr (or anyone else) -- if you think of something we can re-open this.
