### ISSUE TITLE
[python] Upgrade Typeguard to `>4.3.0` (once it is available)

### ISSUE THREAD

**Issue by ryan-williams** [single-cell-data/TileDB-SOMA#3216]
#3001 moves us to installing Typeguard@HEAD, because we need https://github.com/agronholm/typeguard/pull/490 in order for tests/type-checking to pass in Python 3.12):

https://github.com/single-cell-data/TileDB-SOMA/blob/b7db9ed413acc9d43651f1d0148666d09fc50c37/apis/python/requirements_dev.txt#L6-L9

Once a new release of Typeguard is available, we should move to that: [pypi.org/project/typeguard](https://pypi.org/project/typeguard/)

cc @johnkerl

**Comment by johnkerl** [comment]
Thanks @ryan-williams !

**Comment by johnkerl** [comment]
https://github.com/agronholm/typeguard/releases/tag/4.4.0

**Comment by johnkerl** [comment]
Additional follow-up needed as flagged here:
https://github.com/single-cell-data/TileDB-SOMA/issues/3246#issuecomment-2441956639
