### ISSUE TITLE
[Bug] Class methods do not have all desired material in rendered doc pages

### ISSUE THREAD

**Issue by ivirshup** [single-cell-data/TileDB-SOMA#3227]
None of the class methods have rendered documentation pages. You can see this by going to a doc page for any of the classes, like [`Measurement`](https://tiledbsoma.readthedocs.io/en/latest/_autosummary/tiledbsoma.Measurement.html#tiledbsoma.Measurement) and trying to navigate documentation for any of its methods.

This means that there is no documentation for the arguments for any of these methods.

**Comment by johnkerl** [comment]
@ivirshup can you please share an example of a class method name for `Measurement` you expect to see at
https://tiledbsoma.readthedocs.io/en/latest/_autosummary/tiledbsoma.Measurement.html#tiledbsoma.Measurement
but you are not seeing?

Comparing the following at my terminal
```
import tiledbsoma
tiledbsoma.Measurement. <----- hit TAB here
```
with
https://tiledbsoma.readthedocs.io/en/latest/_autosummary/tiledbsoma.Measurement.html#tiledbsoma.Measurement
I'm somehow not able to determine what it is that you're not seeing.

**Comment by ivirshup** [comment]
I'm looking for something like this for each method:

https://anndata.readthedocs.io/en/latest/generated/anndata.AnnData.write_h5ad.html#anndata.AnnData.write_h5ad

The methods are present, but I want to see documentation for the method and its arguments.
