### ISSUE TITLE
[python] Some outgest-related performance improvements

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#3345]
The Python `IntIndexer` bindings fail to release the GIL. These are long-running entry points and should release it.

@bkmartinjr has benchmarked on some threaded code, and has found that this change improves concurrency.

[[sc-59595]](https://app.shortcut.com/tiledb-inc/story/59595/python-release-gil-in-intindexer-c-code-3345)

See also #3345.

**Comment by johnkerl** [comment]
@bkmartinjr can we close this one, given other open issues such as #3293 and #3353?

**Comment by bkmartinjr** [comment]
@johnkerl  - fixed by #3344
