### ISSUE TITLE
[python] Inconsistency in `to_anndata` density/sparsity of `obsp`/`varp`

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#3360]
While `tiledbsoma.io.to_anndata()` exports `obsp`/`varp` as a `scipy.sparse` matrix, `ExperimentAxisQuery.to_anndata()` exports it as a dense ndarray.

The [AnnData API suggests](https://anndata.readthedocs.io/en/stable/generated/anndata.AnnData.obsp.html) the dense ndarray.

Update on #3362: @ivirshup points out that the AnnData docs are wrong and these should be _sparse_ in all cases.

[[sc-59632]](https://app.shortcut.com/tiledb-inc/story/59632)

**Comment by ivirshup** [comment]
Oh let me clarify, it's not that it should be sparse in all cases. It's just that in the majority of cases it should be sparse. If the user really needs a dense array (maybe for a correlation matrix), they can do that.

Ideally you support both. I think the user would decide which they want by what format they stored it in.
