### ISSUE TITLE
[Bug] Breaking change in AnnData dependency in Python API

### ISSUE THREAD

**Issue by biostu24** [single-cell-data/TileDB-SOMA#3391]
The release of the anndata 0.11 package includes breaking changes that affect tiledbsoma 1.14.5. `anndata._core.sparse_dataset.SparseDataset` is not longer exported from anndata but is used by tiledbsoma. 

The `setup.py` file for tileddsoma specifies "anndata>=0.10.1", this could be updated to ""anndata>=0.10.1,<11.0" to fix the issue.

**To Reproduce**

Install tiledbsoma, it is likely to install anndata >=11.0.  In python run `import tiledbsoma.io`. The following error is displayed:

```
Traceback (most recent call last):
  File "/Users/***/repos/sandbox/TileDB/src/build_soma.py", line 17, in <module>
    from anndata._core.sparse_dataset import SparseDataset
ImportError: cannot import name 'SparseDataset' from 'anndata._core.sparse_dataset' (/Users/***/repos/sandbox/TileDB/.venv/lib/python3.11/site-packages/anndata/_core/sparse_dataset.py)
```
 
**Versions :**
 - TileDB-SOMA version: 1.14.5
 - anndata version: 0.11.1
 - Language and language version: python 3.11.10
 - OS : MacOS

**Comment by biostu24** [comment]
A work around for this issue to downgrade anndata to version 0.10.x

**Comment by johnkerl** [comment]
@biostu24 thank you for your report! Our 1.15.0 release, which we expect in the next few weeks, will accommodate AnnData 0.11. (Meanwhile, if you like, you may `pip install --pre tiledbsoma==1.15.0rc4.)
