### ISSUE TITLE
[Bug] importing `tiledbsoma.io` fails for TileDB-SOMA 1.12, now that AnnData 0.11 exists

### ISSUE THREAD

**Issue by royassis** [single-cell-data/TileDB-SOMA#3406]
**Describe the bug**
```python
import tiledbsoma.io
```
Fails

tiledbsoma version: 1.12.3
anndata - not spesificed in requirements.txt but 0.11.1 is installed

Fixed when 0.10.9 is installed

Seems like a dependency issue.

**Comment by johnkerl** [comment]
@royassis here's what's going on:

* AnnData 0.11 was released after we released TileDB-SOMA 1.12.3
* As of 1.12.3 we didn't do a pin like `anndata < 0.11` or `anndata ~= 0.10` -- in hindsight, perhaps we would have
* As you've noticed, AnnData 0.11 is backward incompatible
* Our upcoming 1.15.0 will support AnnData 0.11
