### ISSUE TITLE
Py tiledbsoma: Move debugging code into separate sub-package

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#361]
There is a variety of debugging/introspection printf code in the classes.  Assuming we want to retain it, it should be in a separate sub-package/sub-module, and not in the core src/* files.

Examples:
* util_ann.describe_ann_file
* util_tiledb.list_fragments
* SOMAcollection._show_metadata

etc (there is more - search for `print`)

**Comment by johnkerl** [comment]
These have been done -- see also #778
