### ISSUE TITLE
IO-related support code should be in IO package

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#363]
SOMA*NdMatrix has code which only exists to support the `io` package, eg, `from_matrix` and its sub-functions.  These should be moved to a sub-package (or into soma.io) and the core classes kept focused & well separated from soma.io.

Example from soma_sparse_nd_array.py:
```
    # ---------------
    # TODO: most of this code should be moved into a helper package (eg, soma.io), as
    # is it not part of the core API, and could be built on top of the core API.
    # ---------------
    def from_matrix(self, matrix: Matrix) -> None:
...
```

**Comment by johnkerl** [comment]
@bkmartinjr is there more you want to do here?

**Comment by bkmartinjr** [comment]
Nope - good to go!
