### ISSUE TITLE
Multi-lingual API synchronization work

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#385]
To keep R & Python in sync (both API & implementation interoperability), propose several workstreams:
1. Multi-lingual/implementation unit tests
    * 4 steps in R/Python unit-test code: R tests itself; Python tests itself; Python writes data then R reads and asserts; vice versa
2. ABC for both, and do multilingual code review on ABCs
3. Round-tripping data between the different implementations

**Comment by johnkerl** [comment]
Perhaps superseded by #643

**Comment by maniarathi** [comment]
Dupe of #839
