### ISSUE TITLE
Refine soma_joinid/soma_rowid handling

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#386]
Affects both R & Python

Related to #324 and #325

Current thinking is that we want the handling of soma_joinid/soma_rowid to be explicit, eg,
* soma_joinid/int64 - (materialized column) explicit in read, get schema, writes, etc.  create op will enforce existence and type. No magic population of the column, user must explicitly specify values.
* soma_rowid/int64 - (pseudo-column only in SOMADataFrame), explicit in schema (create, get schema ops), explicit in read (always present unless user overrides with subset of column names), explicit in writes (it is the coordinate into the dense array)

- [x] Python implementation
- [x] R implementation

**Comment by bkmartinjr** [comment]
@aaronwolen - any chance this is fixed?  It is done in Python, and I suspect it is done in R at this point.

**Comment by bkmartinjr** [comment]
@aaronwolen @eddelbuettel  -  I believe the R work for this is complete.  Can you close it if you agree?  Python side has been complete for a long while.  Note that with the removal of the "dense" DataFrame, much of this issue is obsolete.

**Comment by aaronwolen** [comment]
This isn't done but I'll be sure to get it added to our next sprint.

**Comment by aaronwolen** [comment]
With #642 in the books I think we can close. @bkmartinjr?

**Comment by bkmartinjr** [comment]
> With #642 in the books I think we can close. @bkmartinjr?

OK w/ me!  Thanks for doing the lift on this...
