### ISSUE TITLE
tiledb:// tuning

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#392]
There are several places where we need to benchmark & tune tiledb:// (TileDB Cloud) performance and behavior in the Python package.  This issue tracks known issues:
- [ ] the SOMAColleciton __repr__ implementation, by default, walks the entire tree of sub-objects.  This makes it very sensitive to latency (e.g., on s3:// or tiledb:// URIs).  Possible fixes:  async or concurrent requests, or don't walk the entire tree.

**Comment by johnkerl** [comment]
This will be tracked within TileDB's tracking system, as it's implementation-specific
