### ISSUE TITLE
python tiledbsoma:  schema attribute returns incorrect type on SOMADataFrame

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#405]
when a data frame is created with a given schema, the spec says that the create should create a dataframe with the precise types specified, or generate an error if types are not supported.  The only exception is the allowed promotion of binary to large_binary and string to large_string.

Currently, all `string` and `large_string` are silently converted to `large_binary`.

test case:
```
import pyarrow as pa
import tiledbsoma as soma

sdf = soma.SOMADataFrame("./test")
sdf.create(pa.schema([
  ('string', pa.string()),
  ('binary', pa.binary()),
  ('large_binary', pa.large_binary()),
  ('large_string', pa.large_string()),
  ('int64', pa.int64())
]))

print(sdf.schema)
```

When I run it on the latest `main` branch, it prints:
```
soma_rowid: int64
soma_joinid: int64
string: large_binary
binary: large_binary
large_binary: large_binary
large_string: large_binary
int64: int64
```

**Comment by johnkerl** [comment]
#406 is merged to `main`
