### ISSUE TITLE
Add fast nnz to R & Python packages

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#410]
We need to pull the C++ fast nnz (#404) into the Python and R packages.

- [x] Python accessing C++
- [x] R accessing C++

**Comment by eddelbuettel** [comment]
Sorry, I did not catch that earlier as I was not tagged.  Given what @gspowley added this is (essentially) a one-liner:

```r
> library(tiledbsoma)
> uri <- "pre-made-test-data/soco/pbmc3k_processed/obs/"
> nnz(uri)
[1] 2638
> nnz("pre-made-test-data/soco/pbmc3k_processed/ms/mRNA/var")
[1] 1838
> nnz("pre-made-test-data/soco/pbmc3k_processed/ms/mRNA/varm/PCs/")
[1] 91900
> 
```

This (quick draft) returns the (current `uint64_t` in the `nnz()` signature in C++) as a double; we could use `int64` as well.

**Comment by johnkerl** [comment]
@eddelbuettel thanks!

I think we need a little more at the Python/R level -- the C++ code throws in the case of overlapping fragments in the no-duplicates case -- what I _think_ we need in Python/R is some kind of try/catch where the try part calls the C++ code and returns it, while the catch part does what the Python/R code are currently doing.

**Comment by eddelbuettel** [comment]
Cannot speak for Python but R does nothing besides taking a URI, passing it to your function and returning the result.  If the C++ code throws, we show an error.  So there is no added processing currently done.

My understanding was that `nnz()` aims to be _fast_ hence all operations are at the C++ layer.

**Comment by johnkerl** [comment]
@eddelbuettel I'll think it through, doing Python first to get my bearings straight.

At
https://github.com/single-cell-data/TileDB-SOMA/pull/404/files#diff-f00fe93e3a84cedd18aaa8581c5133478d52f4576500a35eb4da1b65bdfb27ecR196
the C++ code uses a trick:

* Return `cell_num` if one fragment
* Return sum over fragment `cell_num` if the fragments don't overlap
* Return sum over fragment `cell_num` if the fragments do overlap but duplicates are allowed
* But otherwise the trick doesn't work and we'll (in Python) need something like what `main-old` is doing [here](https://github.com/single-cell-data/TileDB-SOMA/blob/main-old/apis/python/src/tiledbsoma/annotation_matrix.py#L37)

**Comment by bkmartinjr** [comment]
I had the impression we wanted to implement the whole thing in C++ so that we did not have duplicate R & Python implementations.  I may have misunderstood, but what is the benefit of pushing this up to the higher level language?

**Comment by gspowley** [comment]
I agree, we do want to implement the whole thing in C++. 

If we want to support overlapping fragments for arrays that allow duplicates (i.e. reads are not deduped), we can extend the C++ implementation.

**Comment by bkmartinjr** [comment]
Gotcha!  We definitely want a full nnz, ie, supporting overlaps.

**Comment by gspowley** [comment]
Closing the loop, the released C++ `nnz()` does support overlapping fragments.

The unsupported corner case is for arrays created with `allows_duplicates=True`. Creating an array of this type is currently not supported in SOMA, so `nnz()` covers all supported cases for SOMA. 

If SOMA decides to support arrays with `allows_duplicates=True` in the future, we will revisit `nnz()`.

**Comment by johnkerl** [comment]
#439 connects C++ `nnz` to Python for `SOMASparseNdArray`

**Comment by eddelbuettel** [comment]
This is done now (#422, #439, #446)
