### ISSUE TITLE
R/C++ read-path integration

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#432]
Note there are two big stages of work:

* Create Rcpp layer
* Go through TileDB-SOMA-R "foundational classes" (`SOMADataFrame`, `SOMASparseNdArray`, and `SOMADenseNdArray`) and replace their usage of tiledb-r queries with invocations of the Rcpp/SOMA-reader layer

PRs:

* #421 
* #422 
* #402 
* #403 
* #417

**Comment by eddelbuettel** [comment]
This is complete in the sense that the existing readers in `SOMADataFrame` and `SOMADenseNdArray` have been converted

This may be incomplete as the `SOMASparseNdArray` had no reader, still has none but probably should have one?

**Comment by johnkerl** [comment]
@eddelbuettel definitely! :)

**Comment by johnkerl** [comment]
@eddelbuettel notes that `SOMASparseNdArray` has a reader as of yesterday
