### ISSUE TITLE
[r/python] Build a Python/R round-trip unit test framework

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#435]
Goal is two-fold:

* Write data from R; read it from Python
* Write data from Python; read it from R

**Comment by johnkerl** [comment]
Update: let's not do this in the current sprint, as R classes for the `main` branch are still being built out.

**Comment by ebezzi** [comment]
What we have now is:
1. A framework that can be used to do roundtrip testing (in `apis/system/test`)
2. A set of tests for: `DataFrame`, `SparseNDArray`, `DenseNDArray`
We'll create another ticket for an end to end test that uses a real dataset. Marking this as done.
