### ISSUE TITLE
[r/python] Support half-slices in array indexing

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#457]
Using `tiledb-py` we can pass ranges like `10:` or `:20` 

```
A = tiledb.open(uri)
table = A.df[:]
table = A.df[10:]
table = A.df[:20]
table = A.df[10:20]
```

Using `libtiledbsoma`, at present we can only accept the first and fourth options, not the second and third.

Note: when @bekadavis9 and I looked into this we realized that when we map `[:10]` and `[10:]` to `[min:10]` and `[10:max]`, respectively, given the current factoring of `SOMAReader` the computation of `min` and `max` needs to happen, not in the C++ `SOMAReader` after all, but rather in Python and R using the array's non-empty domain. Later when we push more logic down to C++, this min/max logic can push down with it, but for now, it belongs at the Python/R level.

[X] Python: 582
[ ] R: needs adaption of #582

**Comment by johnkerl** [comment]
I think this is a non-issue in R as the `[:n]` and `[m:]` syntax analogues simply don't exist in R.

@aaronwolen @mojaveazure @eddelbuettel to confirm 🙏

**Comment by mojaveazure** [comment]
Correct, `[:n]` and `[m:]` don't have analogues in R; all slices must define a start and end (`:` is an analogue of `seq.int()`)

**Comment by eddelbuettel** [comment]
To wit:

```r
> v <- 1:10
> v
 [1]  1  2  3  4  5  6  7  8  9 10
> v[4:6]
[1] 4 5 6
> v[4:]
Error: unexpected ']' in "v[4:]"
> v[:5]
Error: unexpected ':' in "v[:"
> 
```
