### ISSUE TITLE
[python] Conda builds

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#494]
* Follow https://blog.gishub.org/how-to-publish-a-python-package-on-conda-forge
* `. ~/miniconda/bin/activate`
* `conda skeleton pypi tiledbsc` (use the name `tiledbsc` from https://pypi.org/project/tiledbsc/)
* Get `Error: No source urls found for tiledbsc`
  * https://stackoverflow.com/questions/49735655/conda-skeleton-fails

> Conda Skeleton Requires a source distribution. Uploading a wheel to pypi is not sufficient.
> 
> In addition to a build distribution
> ```
>     python setup.py bdist_wheel --universal
> ```
> create a source distribution
> ```
>     python setup.py sdist
> ```
> 
> before uploading to PyPI

**Comment by mlin** [comment]
Following input from @Shelnutt2 we need to decide between two approaches for packaging libtiledbsoma in conda:

1. Minimal conda-forge recipes build by reference to the PyPI and CRAN packages, each using its own built-in recipe for compiling libtiledbsoma. If you install both tiledbsoma-py and tiledbosoma-r conda packages, then you have two copies -- and potentially different versions -- of libtiledbsoma, possibly needing deconfliction (TBD).
2. Dedicated libtiledbsoma [sub]package for conda, which becomes a dependency of tiledbsoma-py and tiledbsoma-r, and can be shared between them. 

The second approach is cleaner considering the conda package structure on its own. However, in the bigger picture, it'd necessitate maintaining a third distinct way of compiling libtiledbsoma into packaged form, given that the standalone PyPI and R packages must have their own compile recipes for it.

**Comment by Shelnutt2** [comment]
> However, in the bigger picture, it'd necessitate maintaining a third distinct way of compiling libtiledbsoma into packaged form, given that the standalone PyPI and R packages must have their own compile recipes for it.

Can you provide more details on what would need to be changed? `libtiledbsoma` can already be compiled and installed standalone. It's a proper CMake project with install targets so I don't think we need to change anything to allow it to be packaged for conda?

**Comment by mlin** [comment]
@Shelnutt2 IME when you have conda-forge feedstocks that merely reference PyPI and CRAN packages, maintaining them is trivial because conda-forge's bots do almost everything for you -- they monitor for new upstream package versions and send a PR updating the recipe that you just have to push merge on. If we factor the conda-forge packages in a more custom way that aren't just referencing the PyPI & CRAN packages (which build libtiledbsoma on their own), then there are more release engineering steps to maintain them -- not difficult but not zero either.

**Comment by mlin** [comment]
@Shelnutt2 is this the example to work from? I'm happy to run with it, just don't want to go down the wrong path either. 

https://github.com/TileDB-Inc/tiledb-vcf-feedstock/blob/master/recipe/meta.yaml

**Comment by nguyenv** [comment]
Updates

- https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/7 - Change the tag to `main` so that the packages can be conda installed.
- https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/8 - Add support for Python versions 3.7-3.9. Previously, there was only support for 3.10.

**Comment by nguyenv** [comment]
Will need to upload packages to `conda-forge` next but marking this issue as closed as we have conda builds working.
