### ISSUE TITLE
API: missing ability to introspect given only a URI

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#539]
The current API has the ability to (examples use Python syntax):
1. introspect the type of an open object (e.g., the `obj.soma_type` property)
2. get a typed handle to an object IF the user already knows the object type (e.g.,  `handle = soma.DenseNdArray(uri)`)
3. given a collection entry, get a typed handle (aka "reify"), e.g., `handle = collection[key]`

However, the API _lacks_ any ability to introspect a URI and determine which underlying type it is.  In other words, you can't do:
```
uri = '...'  # URI to SOMA object of unknown type
soma_handle = soma.open_a_uri_as_soma_object(uri)  # where soma_handle is a SOMACollection, NdArray, etc
```

This makes it challenging to write code that is fully assumption free about SOMA objects/collections.

This missing operation is _implied_ by example (3) above, at least for the current specification where object typing is an object attribute, and the collection will automatically introspect any element in the soma collection, returning a handle.

I believe we should propose a top-level utility function that would expose this functionality, i.e.,:
* given a URI, return the `soma_type` of that URI (or an error if not a SOMA object)
* and/or, open and return a SOMA object representing that URI

Concrete example:

```
uri = '...'

# Lookup soma_type for URI
soma_type = soma.get_soma_type(uri)  # -> "SOMASparseNdArray" or other legal type, or None if not a SOMA object

# open SOMA object for URI
soma_handle = soma.open_uri(uri)  # returns instance of SOMACollection, SOMAIndexedDataFrame, etc, or None

assert soma_type == soma_handle.soma_type
```

Please comment.  CC:  @thetorpedodog @johnkerl @aaronwolen @eddelbuettel @mlin

**Comment by johnkerl** [comment]
@thetorpedodog can we dup this to one of your open tasks? IIUC this functionality will  be appearing soon. (Please correct me if I'm wrong.)

**Comment by thetorpedodog** [comment]
yes, this is as simple as making sure `factory.open` is ready for general consumption and exposing it as `tiledbsoma.open`.

**Comment by johnkerl** [comment]
OK @thetorpedodog I'll leave this open as a checklisting/tracking issue for that.

**Comment by thetorpedodog** [comment]
Reopening after linking this spuriously closed it.
