### ISSUE TITLE
[python] release GIL on reads

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#549]
We should release the GIL on latent API calls that are thread safe.  A starter list is anything that has I/O latency and is in the SOMAReader C++ layer:
- [ ] SOMAReader.\_\_init__  (i.e., open)
- [ ] SOMAReader.submit()
- [ ] SOMAReader.read_next()
- [ ] SOMAReader.nnz()

**Comment by gspowley** [comment]
Closed with #550.
