### ISSUE TITLE
tiledbsoma PyPi tags and supported versions do not match

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#615]
The PyPi metadata says that tiledbsoma works with Python 3.7, but it doesn't (fails on an import of Literal from typing module).

Either need the bug fixed (use `typing_extensions`) or update the metadata tags.

**Comment by johnkerl** [comment]
Duplicates #544

**Comment by johnkerl** [comment]
#620 is merged, solving the Python 3.7 issue

#544 is still open to track Python 3.11 support
