### ISSUE TITLE
[python/r/spec] Normalize parameter names between various classes

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#686]
There are a number of places parameter names should be the same, but are not.

Good example:
> DataFrame.read(ids=...)
> SparseNDArray.read(coords=...)

`ids` and `coords` are the same thing, and should have the same name IMHO

[ ] Python -- on #732 
[ ] R -- on #748

**Comment by johnkerl** [comment]
Note this also affects the spec repo https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md

**Comment by johnkerl** [comment]
Has been done
