### ISSUE TITLE
[python] PyPI package metadata has out-of-date links

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#698]
Looking at the PyPi.org page for the package [here](https://pypi.org/project/tiledbsoma/), the Project Homepage link to an obsolete URL.

> https://github.com/single-cell-data/TileDB-SingleCell/apis/python

I suspect this is due to the metadata being incorrect in `main-old`

**Comment by johnkerl** [comment]
@mlin Clicking around everywhere clickable at https://pypi.org/manage/project/tiledbsoma/settings/ and environs I can find _no_ way to edit the project homepage :(

**Comment by johnkerl** [comment]
@mlin at https://pypi.org/manage/project/tiledbsoma/settings/ I see

> To set the 'tiledbsoma' description, author, links, classifiers, and other details for your next release, use the [setup() arguments in your setup.py file](https://packaging.python.org/tutorials/distributing-packages/#setup-args). Updating these fields will not change the metadata for past releases. Additionally, you must use [Twine](https://twine.readthedocs.io/en/latest/) to upload your files in order to get full support for these fields. See [the Python Packaging User Guide](https://packaging.python.org/tutorials/distributing-packages/) for more help.

but at
https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/python/setup.py#L85
we already have the updated URL -- it's not appearing at https://pypi.org/project/tiledbsoma/ though ... I'll dig into what may be more ways to "use Twine" ...... 🤔

**Comment by johnkerl** [comment]
... aha, I see there was a stale URL on `main-old` at
https://github.com/single-cell-data/TileDB-SOMA/blob/9a8a084a98a8ecc95e2b9f9cae183d8bf27601ff/apis/python/setup.py#L98
and (as it turns out) today I tagged `0.5.0a3` from `main` _and then_ `0.1.20` from `main-old`.

So I believe that this problem will just go away on our _next_ release upload. (And, I've fixed the stale spelling in `main-old`'s `__setup.py__`.)

**Comment by johnkerl** [comment]
Verified fixed at
https://pypi.org/project/tiledbsoma/
as of the most recent push which was
https://github.com/single-cell-data/TileDB-SOMA/releases/tag/0.1.21
