### ISSUE TITLE
Close old PRs/issues/etc

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#707]
- [ ] Close/merge old PRs
- [ ] Close old issues when possible
- [x] Remove old tags/labels

**Comment by maniarathi** [comment]
@johnkerl Think we can close this?

**Comment by johnkerl** [comment]
@maniarathi if you like!

It's a "never done" thing closing issues & PRs; this was just an "extra" reminder for pre-release neatening.

If you're happy with it I'm happy with it & we can go on with life which will (as always) have more closing of things :).
