### ISSUE TITLE
[c++/python] Optimize CSR I/O

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#718]
Just a tracking issue

 * There are some CSR-related things @bkmartinjr can accelerate in Python
 * @gspowley mentioned maybe we can do this in `libtiledbsoma` C++
 * Or maybe even in TileDB core
 
This is a follow-on for #719, in case we need C++ work as well

Also, while https://github.com/single-cell-data/SOMA/pull/83 is fabulous, we may wish to incorporate that logic into `tiledbsoma.io`'s `to_anndata`/`to_h5ad` as well.
 
cc @aaronwolen 

This should also support CSC, for R ecosystem benefit

Parent: #922

Internal tracking: [sc-31074]

**Comment by bkmartinjr** [comment]
Related to #719

**Comment by johnkerl** [comment]
We have a domain expert in the form of the incomparable @lums658 and I'll be collaborating with him -- self-assigning to track this

**Comment by johnkerl** [comment]
[sc-31074]
