### ISSUE TITLE
[python] experiment.axis_query().to_anndata() is slow (CSR opportunity)

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#719]
The bottleneck is primarily the conversion of X data from COO to CSR, for use in AnnData construction.  Investigate possible improvements.

See #718 as a tracker for possible C++ improvements -- this issue per se is for Python work

**Comment by bkmartinjr** [comment]
@johnkerl - you have marked this as a C++ task, which I believe is incorrect.  We *may* follow this up with C++ work, but initially it is just Python.  I am reverting the Title to the original value.  If you would like an additional issue filed, beyond #718, LMK and I can duplicate this.

**Comment by johnkerl** [comment]
Thanks for the clarify @bkmartinjr ! Yes, #718 will do.

**Comment by bkmartinjr** [comment]
Fixed by single-cell-data/SOMA#83
