### ISSUE TITLE
Make 1.0rc0 build

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#738]
Currently blocked by: 
- [x] #603 
- [x] #638 
- [x] #540
- [x] #933 
- [x] #919

**Comment by atolopko-czi** [comment]
Can #603 be closed?
Should #540 be added as a blocker of this RC build?

**Comment by johnkerl** [comment]
Tagged yesterday:
https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.0rc0
