### ISSUE TITLE
[python] Switch from `ndims` to `ndim` (now to-do-tracker only)

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#744]
NumPy, SciPy, Pandas, et al. use `ndim` -- so should we. Affects spec, Python impl, and R impl.

See also:

* https://github.com/single-cell-data/SOMA/issues/84
* https://github.com/single-cell-data/SOMA/pull/85
* #747 

Update:

* #747 has a back-compat alias of `ndims` to `ndim` just until the `somacore` 0.0.0a4` release
* This task now remains open solely as a reminder to act on the TODO there and remove that back-compat alias

**Comment by bkmartinjr** [comment]
`somacore//data.py` defines NDArray class with `ndims`

https://github.com/single-cell-data/SOMA/blob/d0df9ed67647d7c0d9d12d191addceebf7d7ed39/python-spec/src/somacore/data.py#L91

**Comment by johnkerl** [comment]
@bkmartinjr yes, that's correct.

More details to come on https://github.com/single-cell-data/SOMA/issues/84
