### ISSUE TITLE
[python] Re-export `somacore.AxisQuery`

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#780]
Working with Chad Krilow on feature-gap analysis (#643). Here's an example query:

```
import tiledbsoma as soma
import somacore

exp = soma.Experiment('foo')

with exp.axis_query(
    "RNA",
    obs_query=somacore.AxisQuery(value_filter='total_counts > 2000 and n_genes_by_counts > 500'),
) as qry:
    print(qry.obs().concat())
```

Note that `AxisQuery` is defined in `somacore`. This is _good_ in the sense that, well, that's where it's defined. But bad in that `somacore` is an implementation detail.

We should re-export this from `tiledbsoma.experiment_query`.

**Comment by bkmartinjr** [comment]
It is already reexported from the very top-level module.

I.e, this works:
```
import tiledbsoma as soma

print(soma.AxisQuery(value_filter="..."))
```

**Comment by johnkerl** [comment]
derp, missed it

thanks @bkmartinjr !!
