### ISSUE TITLE
[python] Backwards compat with old `soma_object_type values` is broken

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#800]
Late 2022, the TileDB metadata vales for dense and sparse NDArray were changed:
* DenseNdArray became DenseNDArray
* SparseNdArray became SparseNDArray

Backwards compatiability was maintained in the factory.py reification code.

However, backwards compat was broken in TiledBObject.exists(), which only supports the most recent metadata values allowed in the `soma_object_type` metadata key.

We should either:
* remove support for the legacy metata keys from factory.py
* or, support them everywhere (eg, in exists()).

To reproduce:
* create and save soma.Collection, containing a soma.DenseNDArray.
* using tiledb, rewrite the metadata for the dense array so that `soma_object_type` is `SOMADenseNdArray`
* open the dense array (eg., `a = soma.DenseNDArray(uri)`)
* the exists method will return the wrong value (eg, `a.exists()` returns False)

The bug is in the `exists()` method in TileDBObject, which does not properly account for the old `soma_object_type` values.

**Comment by atolopko-czi** [comment]
Do we need this compatibility fix prior to a 1.0 release?
