### ISSUE TITLE
[r,python] Create a helper function to comprehensively show version numbers

### ISSUE THREAD

**Issue by eddelbuettel** [single-cell-data/TileDB-SOMA#851]
As seen in the lively discussion in #728 it surprisingly complex to _concisely_ describe the complete software stack for SOMA.  Moreover, how to do so varies between implementation languages.  A helper function `soma_versions()` or `soma_software_versions()` may be helpful.  From #728 we see 

```py
import tiledbsoma, tiledb, sys
tiledbsoma.__version__
tiledb.__version__
sys.version_info
```

and

```r
packageVersion("tiledbsoma")
packageVersion("tiledb")
tiledb::tiledb_version(TRUE)      # for the TileDB Core version used by package tiledb
R.version.string 
```

which one could arrange in a pretty-fied string.

**Comment by johnkerl** [comment]
The PR #855 is merged but once we tag our next release let's update our bug-reporting template to tell people they can use `tiledbsoma.show_package_versions()` (Python) or `tiledbsoma::show_package_versions()` (R)
