### ISSUE TITLE
[python] SOMA Slice to AnnData bug [main-old branch]

### ISSUE THREAD

**Issue by mdylan2** [single-cell-data/TileDB-SOMA#857]
Trying to slice a specific layer called X_norm from my SOMA Collection. Here's some pseudo code:
```
answer = soco.query(
    obs_ids=['example_1'],
    X_layer_names=["normalized_X"],
)
SOMASlice.concat(answer)
```

Throws the error:
```
KeyError: 'data'
```

Should this function have another variable for the X layer being queried?
https://github.com/single-cell-data/TileDB-SOMA/blob/a85213b595d7932aa9616aa0d2b53ec051f8479f/apis/python/src/tiledbsoma/soma_slice.py#L74

**Comment by johnkerl** [comment]
Hi @mdylan2 -- can I please get your `tiledbsoma.__version__`?

**Comment by mdylan2** [comment]
0.1.22

**Comment by mdylan2** [comment]
CLosing because this is based on old SOMA spec
