### ISSUE TITLE
[python] Question about subsetting SOMA Collections based on SOMA names [main-old branch]

### ISSUE THREAD

**Issue by mdylan2** [single-cell-data/TileDB-SOMA#859]
I have a SOMA collection that consists of 100s of SOMAs but I only want to run a query on a defined set of SOMAs (I know the names of the SOMAs that I want to look at). Currently the `SOMACollection.query` populates all the SOMAs. 

Is there some method to "short-list" the SOMAs of interest off the bat? Does this fit into the obs_attrs querying syntax?

**Comment by johnkerl** [comment]
@mdylan2 I would suggest `SOMA.queries`:
https://github.com/single-cell-data/TileDB-SOMA/blob/0.1.22/apis/python/src/tiledbsoma/soma.py#L491-L505

**Comment by mdylan2** [comment]
Feel free to close if needed because this solves our issue
