### ISSUE TITLE
[python] Top-level namespace needs review

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#872]
The top-level exported namespace for the python package needs refinement.  Current status as of `0.5.0a8` contains some private stuff (eg, TileDBArray), some missing items (eg, #791, and possibly some items from `.options`), etc.  Our prior design discussion concluded that any name _commonly_ used by end-users should be promoted to the top level.  Uncommonly used items could stay within sub-namespaces.

A particular gap is the re-export of some useful `somacore` names (one example is highlighted in #791).  Another pair we use in `cell_census` are:
```
from somacore.query.query import AxisColumnNames
from somacore.options import SparseDFCoord
```

Current state of the top-level package:

```
In [2]: dir(soma)
Out[2]: 
['AxisQuery',
 'Collection',
 'DataFrame',
 'DenseNDArray',
 'DoesNotExistError',
 'Experiment',
 'ExperimentAxisQuery',
 'Measurement',
 'MetadataMapping',
 'SOMAError',
 'SparseNDArray',
 'TileDBArray',
 'TileDBObject',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'collection',
 'constants',
 'dataframe',
 'dense_nd_array',
 'exception',
 'experiment',
 'general_utilities',
 'get_SOMA_version',
 'get_implementation',
 'get_implementation_version',
 'get_storage_engine',
 'libtiledbsoma',
 'measurement',
 'metadata_mapping',
 'options',
 'query_condition',
 'sparse_nd_array',
 'tiledb_array',
 'tiledb_object',
 'types',
 'util',
 'util_arrow',
 'util_iter',
 'util_tiledb']
```

**Comment by johnkerl** [comment]
@bkmartinjr some things have been done since 0.5.0a8 (in `HEAD`); more to do, though -- thanks for pointing this out.

**Comment by johnkerl** [comment]
@bkmartinjr here is `HEAD` as of right now:

import tiledbsoma as soma

module = soma
# module = soma.options

for e in sorted(dir(module)):
    if not e.startswith("__"):
            #print(e)
            print(e, type(module.__getattribute__(e)))

[then some hand-editing to organize by type]

AxisQuery                  <class 'type'>
DoesNotExistError          <class 'type'>
ExperimentAxisQuery        <class 'type'>
SOMAError                  <class 'type'>
Collection                 <class 'abc.ABCMeta'>
DataFrame                  <class 'abc.ABCMeta'>
DenseNDArray               <class 'abc.ABCMeta'>
Experiment                 <class 'abc.ABCMeta'>
Measurement                <class 'abc.ABCMeta'>
SparseNDArray              <class 'abc.ABCMeta'>

stats_disable              <class 'builtin_function_or_method'>
stats_dump                 <class 'builtin_function_or_method'>
stats_enable               <class 'builtin_function_or_method'>
stats_reset                <class 'builtin_function_or_method'>
get_SOMA_version           <class 'function'>
get_implementation         <class 'function'>
get_implementation_version <class 'function'>
get_storage_engine         <class 'function'>
show_package_versions      <class 'function'>

collection                 <class 'module'>
common_nd_array            <class 'module'>
constants                  <class 'module'>
dataframe                  <class 'module'>
dense_nd_array             <class 'module'>
exception                  <class 'module'>
experiment                 <class 'module'>
general_utilities          <class 'module'>
libtiledbsoma              <class 'module'>
measurement                <class 'module'>
metadata_mapping           <class 'module'>
options                    <class 'module'>
query_condition            <class 'module'>
sparse_nd_array            <class 'module'>
tiledb_array               <class 'module'>
tiledb_object              <class 'module'>
types                      <class 'module'>
util                       <class 'module'>
util_arrow                 <class 'module'>
util_iter                  <class 'module'>
util_tiledb                <class 'module'>
```

Likewise for `tiledbsoma.options`:

```
SOMATileDBContext     <class 'type'>
soma_tiledb_context   <class 'module'>
tiledb_create_options <class 'module'>
```

Things to add to the top-level namespace:

* `AxisColumnNames` (#791)
* `SparseDFCoord`
* Which of the above three items from `tiledbsoma.options` do you want re-exported at top level?

Things to remove from the top-level namespace:

* None, since #856 was merged last week -- ?

**Comment by johnkerl** [comment]
Also with regard to https://github.com/single-cell-data/TileDB-SOMA/pull/896/files#r1098987617 -- do we really want stats accessors at top level? I've added this question to the agenda for our Friday spec-discussion meeting.

**Comment by johnkerl** [comment]
https://github.com/single-cell-data/TileDB-SOMA/issues/872#issuecomment-1421218864
was discussed in #915 and is being implemented in #944

**Comment by johnkerl** [comment]
Re-export of `somacore.options.SparseDFCoord` is on #946

@bkmartinjr given the discussion on #915 -- which turns the question "what to export at top level" into "what should users be calling directly" -- which of the following from `somacore.options` do you expect users to be calling directly?

```
Any                            _SpecialForm
BatchSize                      type
DenseCoord                     _UnionGenericAlias
DenseNDCoords                  _GenericAlias
Final                          _SpecialForm
IOfN                           type
Literal                        _SpecialForm
Mapping                        _SpecialGenericAlias
OpenMode                       _GenericAlias
Optional                       _SpecialForm
PlatformConfig                 _GenericAlias
ReadPartitions                 type
ResultOrder                    EnumMeta
ResultOrderStr                 _UnionGenericAlias
Sequence                       _SpecialGenericAlias
SparseDFCoord                  _UnionGenericAlias
SparseDFCoords                 _GenericAlias
SparseNDCoords                 _UnionGenericAlias
Union                          _SpecialForm

attrs                          module
enum                           module
np                             module
npt                            module
pa                             module

SOMA_JOINID                    str
```

I imagine:

* `BatchSize`
* `DenseCoord`
* `DenseNDCoords`
* `IOfN`
* `ResultOrder`

but I defer to the experience you and @atolopko-czi have with the cell-census builder. cc also @thetorpedodog .

**Comment by thetorpedodog** [comment]
Neither `DenseCoord` nor `DenseNDCoords` (or any of the `Coord` types) are instantiable so they should not be exported. The only types that we expect users to use are available directly from the `somacore` level, so they can be re-exported from there.

**Comment by bkmartinjr** [comment]
Tiny nit:  the other thing you might look at is all of the exported, but not useful class module names Python gives us by default (eg., tiledbsoma.arrow_types).  I don't think there is any way to clean this up unless we consolidate it all inside an "internals" sub-module, but if @thetorpedodog knows some magic, and it is easy to apply, it might help remove some of the detritus.

**Comment by thetorpedodog** [comment]
The usual strategy there is to name modules not intended for public consumption with a `_`, like [`_mixin.py`](https://github.com/single-cell-data/SOMA/blob/main/python-spec/src/somacore/_mixin.py). You can still re-export members *from* those modules, but putting the `_` is the hint that clients should not be importing those modules directly.

This establishes a hierarchy:

- The most important things directly re-exported at the root module level
- Non–`_`-prefixed modules are available for public consumption but contain things for less-important use cases
- `_`-prefixed modules are internal-only

**Comment by bkmartinjr** [comment]
@thetorpedodog, @johnkerl  - that is super cool. Do you see any reason we can't do that?

**Comment by johnkerl** [comment]
@bkmartinjr @thetorpedodog we can and we should, and I will

Thank you!

**Comment by atolopko-czi** [comment]
> Which of the above three items from tiledbsoma.options do you want re-exported at top level?

Just `SOMATileDBContext`

**Comment by atolopko-czi** [comment]
Any enums and types that might be used in client code to parameterize its own calls into a SOMA implementation should be included.  

If we're looking for a rule, perhaps the `.*GenericAlias`s and `Type`s are worth exporting, but not the `SpecialForm`s or `module`s.

Census does use `OpenMode`, could use `ResultOrder`, `SOMA_JOINID`

**Comment by thetorpedodog** [comment]
Here’s my take on this:

> Any enums and types that might be used in client code to parameterize its own calls into a SOMA implementation should be included.
> 
> If we're looking for a rule, perhaps the `.*GenericAlias`s and `Type`s are worth exporting, but not the `SpecialForm`s or `module`s.

In most cases, the generic aliases are not actual types and users can’t do anything useful with them (these are what I’m referring to in [the comment above](https://github.com/single-cell-data/TileDB-SOMA/issues/872#issuecomment-1431543978)).

> Census does use `OpenMode`, could use `ResultOrder`, `SOMA_JOINID`

`ResultOrder`, `SOMA_JOINID`: Absolutely export these; client code uses these values directly.

`OpenMode`: Since this is just a `Literal`, it can’t actually be used in client code anywhere other than type annotations. This fits into the "still available from a visible module, but not directly in the main namespace" level of importance.

**Comment by atolopko-czi** [comment]
I agree the types do not need to be exported, as long as they are accessible (and they are). Would only be using them to parameterize "builder" code methods.

**Comment by johnkerl** [comment]
@atolopko-czi @thetorpedodog current contents:

```

Collection                     ABCMeta
DataFrame                      ABCMeta
DenseNDArray                   ABCMeta
Experiment                     ABCMeta
Measurement                    ABCMeta
SparseNDArray                  ABCMeta

AxisColumnNames                _TypedDictMeta
AxisQuery                      type
DoesNotExistError              type
ExperimentAxisQuery            type
SOMAError                      type
SOMATileDBContext              type

get_SOMA_version               function
get_implementation             function
get_implementation_version     function
get_storage_engine             function
open                           function
show_package_versions          function
tiledbsoma_stats_disable       builtin_function_or_method
tiledbsoma_stats_dump          builtin_function_or_method
tiledbsoma_stats_enable        builtin_function_or_method
tiledbsoma_stats_reset         builtin_function_or_method

SOMA_JOINID                    str

libtiledbsoma                  module
options                        module
```

**Comment by johnkerl** [comment]
Looks like we only lack `ResultOrder` now

**Comment by johnkerl** [comment]
Closing since the final PR #973 is merged.

Please let me know ASAP if we find anything else we need to add/delete regarding the Python top-level namespace.
