### ISSUE TITLE
[backlog] Look into string deduplication for Arrow tables

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#874]
**Is your feature request related to a problem? Please describe.**

We shoud look into having the `SOMAReader` (i.e. R/Python read path in `tiledbsoma`) do string deduplication in the same way that TileDB-Py does when the configuration setting `py.deduplicate` has value `True`.

**Describe the solution you'd like**

This refers to duplicates in the Arrow array (or column) itself.  It is definitely true that [pyarrow.Table.to_pandas](http://pyarrow.table.to_pandas) has dedup on by default (as does `Arrow.StringArray)`.
So, is there a need for an option to have the Arrow Table, as created by `SOMAReader`, do de-dup to save memory?

**Describe alternatives you've considered**

This currently works; the ask here is for a memory-reduction option.

**Comment by eddelbuettel** [comment]
That happens automagically for us by R and we have no control (once we bring them in from Arrow).  Consider:

```r
> txt <- c("The quick brown fox")
> object.size(txt)      # not the same as nchar() as the SEXP holding the object has some fixed size
136 bytes
> txtvec <- rep(txt, 100)
> object.size(txtvec)    # not '100x' but (approx.) 100 x size of pointer plus fixed size of SEXP
928 bytes
> txtvec2 <- rep(txt, 1000)
> object.size(txtvec2)   # ditto
8128 bytes
> object.size("")
112 bytes
> 
```

It is a little different once you use ALTREP objects explicitly which I believe Arrow does but I have not yet looked into details.

**Comment by eddelbuettel** [comment]
The comment from Feb 3, 2023 still holds:  we already got the 'hashed entry' behavior from R itself so no extra work needed.  R deals with its string data in a separate pool and hashes them already.  That is not an exposed UI and all internal.

(Historically, if my memory serves me here, 'factors/emums' were the initial way to save here and it was later supplanted by the (much) improved internal representation which is also the reason 'factors as default' was later removed / demoted (as it confused some newer users, and the gains were had already via internal hashing).

So in a way we are not covered twice.  I think we are covered well enough here.

**Comment by johnkerl** [comment]
Thanks @eddelbuettel !
