### ISSUE TITLE
[BUG] Python regression -- `SparseNDArray` allows duplicates

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#875]
**Describe the bug**
Recent releases of `tiledbsoma` `SparseNDArray` create underlying TileDB arrays with `allows_duplicates=True`, which is a regression from the spec and past behavior.

**To Reproduce**

```python
In [7]: A = soma.SparseNDArray.create("./foo", type=pa.float32(), shape=(10, 100))

In [8]: A.uri
Out[8]: './foo'

In [9]: with tiledb.open(A.uri) as ta: print(ta.schema)
ArraySchema(
  domain=Domain(*[
    Dim(name='soma_dim_0', domain=(0, 9), tile=10, dtype='int64', filters=FilterList([ZstdFilter(level=3), ])),
    Dim(name='soma_dim_1', domain=(0, 99), tile=100, dtype='int64', filters=FilterList([ZstdFilter(level=3), ])),
  ]),
  attrs=[
    Attr(name='soma_data', dtype='float32', var=False, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
  ],
  cell_order='row-major',
  tile_order='row-major',
  capacity=100000,
  sparse=True,
  allows_duplicates=True,
)
```

**Versions (please complete the following information):**

Latest main branch HEAD.

**Additional context**

The code is in `common_nd_array.py`, and seems to have been intentional - but is definitely a regression. Need a test case to control for this in future revisions.

**Comment by bkmartinjr** [comment]
This bug points out that we should have unit tests that validate the underlying TileDB schema for various tiledbsoma constructs.

**Comment by bkmartinjr** [comment]
See also #876 

I think ideally the `allow_duplicates` parameter in the call to tiledb.ArraySchema would be:
>         allows_duplicates=create_options.get("allows_duplicates", False),

**Comment by johnkerl** [comment]
@bkmartinjr indeed, we are on the same page -- #876 is open and tracks the problem it reports. This issue remains an immediate bugfix.
