### ISSUE TITLE
[docs] Pre-release setup for `single-cell-data` organization

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#884]
Ideas from @bkmartinjr : 

[X] Description
[X] Link
[X] Contact info
[X] `README.md`
[X] Pinned repos (marginal gain, but why not)

See some examples of desirable top-level:
* https://github.com/microsoft/
* https://github.com/apache/
* https://github.com/google/

Ours:

* https://github.com/single-cell-data/

**Comment by johnkerl** [comment]
cc @maniarathi @Shelnutt2 @stavrospapadopoulos -- looking at the microsoft/apache/google examples, I think we could use some graphic-design help :)

**Comment by pablo-gar** [comment]
Should we remove/archive mams? @BAevermann @ambrosejcarr

**Comment by pablo-gar** [comment]
Should include logos of participating organizations?

**Comment by BAevermann** [comment]
Joshua Campbell is planning to move MAMS to its own repo the week of Feb 27th

**Comment by johnkerl** [comment]
All the requested items have been done at
https://github.com/single-cell-data

The graphics are ... adequate ... albeit not in their final form. I'm meeting with graphic-design/marketing folks on Friday re logo work. Getting better logos in place will be fabulous, but, IMO we shouldn't hold this task open for that.
