### ISSUE TITLE
[Bug] Reading slices beyond shape of an `NDArray` errors incorrectly

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#900]
**Describe the bug**

Requesting a slice to be read, where the slice extends beyond the end of the dimension, will error.  This is not correct - it should simply read any portion of the array defined by the slice.

There seems to be a logic error in the interface which converts the slice into a point list for SOMAReader.

**To Reproduce**

Test case:
```python
import pyarrow as pa
import numpy as np
import scipy.sparse
import tiledbsoma as soma

with soma.Collection.create("./testcollection") as collection:
    snda = collection.add_new_sparse_ndarray(
        "snda", type=pa.float32(), shape=(100, 100)
    )
    snda.write(
        pa.SparseCOOTensor.from_scipy(
           scipy.sparse.random(100, 100, dtype=np.float32)
        )
    )

with soma.SparseNDArray.open("testcollection/snda", mode="r") as snda:
    some_data = snda.read((slice(0, 101),)).tables().concat()
```

Result:
```
RuntimeError                              Traceback (most recent call last)
Cell In[24], line 17
     10     snda.write(
     11         pa.SparseCOOTensor.from_scipy(
     12            scipy.sparse.random(100, 100, dtype=np.float32)
     13         )
     14     )
     16 with soma.SparseNDArray.open("testcollection/snda", mode="r") as snda:
---> 17     some_data = snda.read((slice(0, 101),)).tables().concat()

File ~/TileDB-SOMA/apis/python/src/tiledbsoma/sparse_nd_array.py:125, in SparseNDArray.read(***failed resolving arguments***)
    121         if lo < 0 or hi < 0:
    122             raise ValueError(
    123                 f"slice start and stop may not be negative; got ({lo}, {hi})"
    124             )
--> 125         sr.set_dim_ranges(dim_name, [lo_hi])
    126     # Else, no constraint in this slot. This is `slice(None)` which is like
    127     # Python indexing syntax `[:]`.
    128 elif isinstance(
    129     coord, (collections.abc.Sequence, pa.Array, pa.ChunkedArray)
    130 ):

RuntimeError: [TileDB::Subarray] Error: Cannot add range to dimension 'soma_dim_0'; Range [0, 101] is out of domain bounds [0, 99]
```

**Versions (please complete the following information):**

tiledbsoma.__version__    0.5.0a8.post62.dev2571341179
tiledb.__version__        0.20.0
core version              2.14.0
python version            3.9.16.final.0

**Comment by johnkerl** [comment]
@bkmartinjr looking to see what was missed on #485 ... 👀

**Comment by johnkerl** [comment]
Python PR closed. I need to check R status before closing this issue.

**Comment by johnkerl** [comment]
The issue does indeed repro in R. Working on a fix.

**Comment by johnkerl** [comment]
@eddelbuettel I could use some help with porting #901 to R.

I've spent a few hours looking through the R code and I believe this to be the route:

* `read_arrow_table` in `R/SOMASparseNDArray.R`
* `soma_reader` in `R/RcppExports.R` does ` .Call(`_tiledbsoma_soma_reader`, ...)`
* `soma_reader` in `src/rinterface.cpp` calls `apply_dim_points`
* `src/rutilities.cpp` implements `apply_dim_points`

I think to port #901 I need somewhere:

* `arr <- iledb::tiledb_array('/var/s/v/krasnow/obs')`
* in loop over dim names, e.g. `'soma_joinid'`
  * `ned <- tiledb_array_get_non_empty_domain_from_name(a, )`

but I'm not sure the best place to do this -- in particular with our desire to minimize the number of open-array calls ...

cc also @aaronwolen and @gspowley

**Comment by eddelbuettel** [comment]
A [minimally reproducible verifiable example](https://stackoverflow.com/help/minimal-reproducible-example) would, as always, help. _Which_ array are you hitting _how_?  R can be "interesting" in how indexing operations get evaluated and expanded "when" so details would likely help.

**Comment by johnkerl** [comment]
Sorry @eddelbuettel I knew I was forgetting something.

Adapted from `tests/testthat/test_SOMASparseNdArray.R`:

```
create_sparse_matrix_with_int_dims <- function(nrows = 10, ncols = 5, seed = 1, repr = "T") {
  set.seed(seed)
  Matrix::rsparsematrix(
    nrow = nrows,
    ncol = ncols,
    density = 0.6,
    rand.x = function(n) as.integer(runif(n, min = 1, max = 100)),
    repr = repr
  )
}

# ----------------------------------------------------------------
uri <- "fooexp"
ndarray <- SOMASparseNDArray$new(uri)

# Uncomment just once for first run:
# ndarray$create(arrow::int32(), shape = c(10, 10))
# mat <- create_sparse_matrix_with_int_dims(10, 10)
# ndarray$write(mat)

tbl <- ndarray$read_arrow_table(
  # coords = list(soma_dim_0=0, soma_dim_1=0:8), # crash = no
  coords = list(soma_dim_0=0, soma_dim_1=0:12), # crash = yes
  result_order = "COL_MAJOR"
)
print(tbl)
```

**Comment by eddelbuettel** [comment]
What is the actual command that fails?  (`source(...)` is a portmanteau and and not an issue)

What did you expect?  What did you get?

Asking `[10, 10]` on something that is _known smaller_ is, to a first approximation, still a user error.  One can always put more wrappers around but in general there is tradeoff between _performance_ and _useability_.

**Comment by johnkerl** [comment]
What I got was the exception shown above.

What I expected was not to get the exception -- rather, just to get data to the end of the array as in #901.

If the R-community consensus (@eddelbuettel @aaronwolen @mojaveazure ) is that indexing beyond the end of the array is to be prohibited in R (even though it's already established that indexing beyond the array is _pythonically_ acceptable), then we can close this issue now. Then we will have TileDB-SOMA's Python and R implementations differing _from one another_ in how they handle over-indexing, but each will be _compatible with its own language culture_.

I just need consensus on this from the R experts here. (cc also @mlin for CZI R perspective, and @bkmartinjr who filed this issue).

**Comment by eddelbuettel** [comment]
I am somewhat fundamentally at a loss between what is expected here (or "what would be nice to have") and what the language we are _actually using_ supports.  My frame of mind is simplisitic and along the lines of "if I have a vector of size X and ask for Y > X what am I really expecting ?"

```r
 x <- seq(1:10)
> x[144]
[1] NA
> 
```

**Comment by johnkerl** [comment]
Here's what Python does with slice-beyond-end:

```
>>> x = list(range(10))
>>> x[0:20]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

and #901 makes TileDB-SOMA-Py do the Pythonic thing.

Here's what R does with slice-beyond-end:

```
> x <- seq(1:10)
> x[0:20]
 [1]  1  2  3  4  5  6  7  8  9 10 NA NA NA NA NA NA NA NA NA NA
```

and we have two things going on:

1. A decision: do we want TileDB-SOMA-R to do the R-like thing with slice-beyond-end? (Currently TileDB-SOMA-R crashes on slice-beyond-end of `SOMASparseNDArray`, as demonstrated above)
2. Implementation: I would need some help (as detailed above) in modifying the current implementation from what it is now.

**Comment by eddelbuettel** [comment]
I think what you observe is not a crash. It is an error condition caught only at the C++ level leading to a throw that is translated to an error returning you to the R prompt.  That should be easy to catch before the (explicitly created) coords list is submitted.  The same thing happens for SOMADataFrame too (with the added caveat that we don't seem to convert to indices to int64 first).

```r
> dplyr::collect(sdf$read(coords=list(soma_dim_0=0, soma_dim_1=as.integer64(0:8))))
# A tibble: 4 × 3
  soma_dim_0 soma_dim_1 soma_data
       <int>      <int>     <int>
1          0          0        25
2          0          1        26
3          0          2        41
4          0          5        79
> dplyr::collect(sdf$read(coords=list(soma_dim_0=0, soma_dim_1=as.integer64(0:12))))
Error: [TileDB::Subarray] Error: Cannot add range to dimension 'soma_dim_1'; Range [10, 10] is out of domain bounds [0, 9]
> 
```

And just as a note: no 'crash' here. It's an error caught at the C++ layer which throws which leads to a return to R with error.  So the desired object is not created.

**Comment by eddelbuettel** [comment]
I created a SC ticket.  We need to decide where / how to best incur the cost of domain validation each time we index with `coords` (or if we want to error differently).

**Comment by eddelbuettel** [comment]
@johnkerl   I worked quite a bit on this and have a draft of C++-side solution (which did create some issues in CI with Python, it may be more difficult to fix this 'more generally' but @gspowley and I can take another look.  I also added fairly clean solution just within the R package; that is in #920.  Your initial failing example works fine with it as shown below; if you set the log_level back to "warn" it is quiet as before but the logging details what is happening here, _i.e._ that the 'outside of domain' range is no longer set.

```r
> library(tiledbsoma)
> uri <- "/tmp/tiledb/foosnda"
> ndarray <- SOMASparseNDArray$new(uri)
> tbl_bad <- ndarray$read_arrow_table(coords = list(soma_dim_0=0, soma_dim_1=0:12), log_level="info")
[2023-02-11 16:56:51.933] [default] [Process: 1570260] [info] [soma_reader] Reading from /tmp/tiledb/foosnda
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [soma_reader] Dimension soma_dim_0 type INT64 domain [0,9] extent 10
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [soma_reader] Dimension soma_dim_1 type INT64 domain [0,9] extent 10
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [apply_dim_points] Applying dim point 0 on soma_dim_0
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [apply_dim_points] Applying dim point 0 on soma_dim_1
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [apply_dim_points] Applying dim point 1 on soma_dim_1
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [apply_dim_points] Applying dim point 2 on soma_dim_1
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [apply_dim_points] Applying dim point 3 on soma_dim_1
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [apply_dim_points] Applying dim point 4 on soma_dim_1
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [apply_dim_points] Applying dim point 5 on soma_dim_1
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [apply_dim_points] Applying dim point 6 on soma_dim_1
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [apply_dim_points] Applying dim point 7 on soma_dim_1
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [apply_dim_points] Applying dim point 8 on soma_dim_1
[2023-02-11 16:56:51.936] [default] [Process: 1570260] [info] [apply_dim_points] Applying dim point 9 on soma_dim_1
[2023-02-11 16:56:51.939] [default] [Process: 1570260] [info] [soma_reader] Read complete with 5 rows and 3 cols
[2023-02-11 16:56:51.939] [default] [Process: 1570260] [info] [soma_reader] Accessing soma_dim_0 at 0
[2023-02-11 16:56:51.939] [default] [Process: 1570260] [info] [soma_reader] Incoming name soma_dim_0
[2023-02-11 16:56:51.939] [default] [Process: 1570260] [info] [soma_reader] Accessing soma_dim_1 at 1
[2023-02-11 16:56:51.939] [default] [Process: 1570260] [info] [soma_reader] Incoming name soma_dim_1
[2023-02-11 16:56:51.939] [default] [Process: 1570260] [info] [soma_reader] Accessing soma_data at 2
[2023-02-11 16:56:51.939] [default] [Process: 1570260] [info] [soma_reader] Incoming name soma_data
> print(dplyr::collect(tbl_bad))
# A tibble: 5 × 3
  soma_dim_0 soma_dim_1 soma_data
       <int>      <int>     <int>
1          0          0        25
2          0          1        26
3          0          2        41
4          0          5        79
5          0          9        48
> 
```

**Comment by johnkerl** [comment]
#920 is merged
