### ISSUE TITLE
[r] Synchronize `man`/ `roxygenise` updates

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#906]
In the R package, `man/*.Rd` files are currently out of date with respect to `R/*.R` source.

There are two opportunities:

* Get these up to date manually for the next release and/or head
* Automate this:
  * Maybe some release-time CI perhaps -- ?
  * Maybe some pre-commit hook that runs `roxygenise` on every PR that alters `roxygen` inputs -- ?

**Comment by eddelbuettel** [comment]
Minor vote against CI automation, this really needs to part of every PR altering roxygen input.

**Comment by johnkerl** [comment]
@eddelbuettel 🙏 thank you -- I updated the description just now
