### ISSUE TITLE
default read timestamp incorrect for writer+reader use case

### ISSUE THREAD

**Issue by atolopko-czi** [single-cell-data/TileDB-SOMA#913]
**Describe the bug**
When a process performs writes followed by reads (using a new open() handle), the reads do not return the written data.

This occurs because the `SOMATileDBContext.read_timestamp` is set at _process_ initialization time, and so will always be _before_ the write timestamp, which is set to a greater value.

**To Reproduce**
TODO: @atolopko-czi 
Roughly:
```
with soma.Collection.create('youcantreadme') as c:
    c.metadata["key"] = "anything"
with soma.Collection.open('youcantreadme') as c:
    assert c.metadata["key"] == "anything" # fails

with soma.Collection.open('youcantreadme', SOMATileDBContext(read_timestamp=int(time.time() * 1000)) as c:
    assert c.metadata["key"] == "anything" # succeeds, thanks to the explicit "now" read timestamp
```

**Versions (please complete the following information):**
 - TileDB-SOMA version: 0.0.5a9
 - Language and language version (e.g. Python 3.8, R 4.2.2): Py 3.10.6, but shouldn't matter
 - OS (e.g. MacOS, Ubuntu Linux): MacOS, of course

**Additional context**
Need to test on 0.0.5a10, just in case this is already fixed!

**Comment by bkmartinjr** [comment]
CC @mlin

**Comment by mlin** [comment]
Hmm, still looking, but I wasn't immediately able to reproduce by adding this to `test_collection.py`

```python
def test_real_timestamped_ops(tmp_path):
    with soma.Collection.create(tmp_path.as_uri()) as sc:
        sc.metadata["key"] = "anything"
        sc.add_new_sparse_ndarray("A", type=pa.uint8(), shape=(2, 2)).write(
            pa.SparseCOOTensor.from_scipy(
                sparse.coo_matrix(([1], ([0], [0])), shape=(2,2))
            )
        )
    with soma.Collection.open(tmp_path.as_uri()) as sc:
        assert sc.metadata["key"] == "anything"
        assert "A" in sc
        assert sc["A"].nnz == 1
```

The default initialization of the read timestamp occurs here:

https://github.com/single-cell-data/TileDB-SOMA/blob/badb5d66318d33469adec04b78534a3ca932256d/apis/python/src/tiledbsoma/options/soma_tiledb_context.py#L35

The timing of this is controlled by attrs, and I *assumed* that the idea of the "factory lambda" is to generate it at *object* initialization time, not *process* wide...but admittedly I don't see that explicated in the attrs docs. (cc @thetorpedodog)

@atolopko-czi can you think of any other distinguishing characteristics of how you encountered this? can you try putting in some debug print of `c.context.read_timestamp` to confirm if the default read timestamp was generated prematurely, or else if something else more subtle is going on?

**Comment by bkmartinjr** [comment]
@mlin is right - it gets called at __init__ time, so something else must be going on...

```python
In [2]: import time
   ...: 
   ...: import attrs
   ...: 
   ...: 
   ...: def factory():
   ...:     print("Factory called")
   ...:     return int(time.time() * 1000)
   ...: 
   ...: 
   ...: @attrs.define
   ...: class Foo:
   ...:     x: int = 0
   ...:     read_timestamp: int = attrs.field(factory=lambda: factory())
   ...: 

In [3]: Foo()
Factory called
Out[3]: Foo(x=0, read_timestamp=1676000166828)

In [4]: Foo()
Factory called
Out[4]: Foo(x=0, read_timestamp=1676000169850)
```

**Comment by atolopko-czi** [comment]
The bug is in the client code, which maintains a _global_ `SOMATileDBContext`, locking in the read timestamp for the duration of the process that is performing writes followed by reads. Closing this issue!
