### ISSUE TITLE
[python] Point-in-time child object access fails when using explicit write_timestamp

### ISSUE THREAD

**Issue by atolopko-czi** [single-cell-data/TileDB-SOMA#919]
**Describe the bug**
When a _single_ process attempts to access a DataFrame as a child of a Collection that was created by an earlier `create()` (using a independent context manager block) , the child access _transiently_ fails to "see" the DataFrame _if_ 1) a sibling collection was created before the DataFrame, and 2) a `write_timestamp` is explicitly provided via the `SOMATileDBContext`.

Apologies, but I can't whittle this down to a simpler case.  All of these conditions seem to be necessary.

**To Reproduce**
https://gist.github.com/atolopko-czi/26683305258a9f77a57ccc364916338f

**Versions (please complete the following information):**
TileDB-SOMA version: 0.0.5a9
Language and language version (e.g. Python 3.8, R 4.2.2): Py 3.10.6, but shouldn't matter
OS (e.g. MacOS, Ubuntu Linux): MacOS, of course

**Additional context**

Test code results look like:
```
test_case 0 FAILED: "Experiment has no item 'df'", read_timestamp=1676138942753, write_timestamp=100
test_case 1 PASSED, read_timestamp=18446744073709551615, write_timestamp=None
test_case 2 FAILED: "Experiment has no item 'df'", read_timestamp=18446744073709551615, write_timestamp=100
```
Sometimes they all pass, but 0 and 2 fails transiently, sometimes with only one of them failing. 😵‍💫 

See reproduction test case, above, to interpret.

I am seeing that some of the TileDB groups and metadata files do _not_ have the specified explicit `write_timestamp`.
```
❯ find /tmp/pit/ -regex '.*/__[0-9]+_.*'
# Test case 0, failure: The expt/df/__schema timestamp is NOT set to the specified write_timestamp
/tmp/pit/0/__meta/__100_100_2424680daedc4bb6839a5f6507335d89
/tmp/pit/0/expt/__meta/__100_100_3621c4e641b14a42950df4cb4e9b8696
/tmp/pit/0/expt/df/__meta/__100_100_40fd7a800ca041d3a4bb82d3d3c43bec
/tmp/pit/0/expt/df/__schema/__1676140033065_1676140033065_cb4dd07d67bf4635a6140c082e200b27
/tmp/pit/0/expt/causes_bug/__meta/__100_100_09451752238549b696401ea472a452d2
/tmp/pit/0/expt/__group/__100_100_82aab386278a47a6bcf328f8eb097e86
/tmp/pit/0/expt/__group/__100_100_fd6a676262ad4133811f81cfdc21dc53
/tmp/pit/0/__group/__100_100_933e497ede614591892874c34ff311a1

# Test case 1, success: All timestamps set to time-of-write (no write_timestamp specified)
/tmp/pit/1/__meta/__1676140033073_1676140033073_fc1aecdbb1574a2b84c2322f125c6200
/tmp/pit/1/expt/__meta/__1676140033073_1676140033073_da311b32d958414f91399cd0f4679f5f
/tmp/pit/1/expt/df/__meta/__1676140033078_1676140033078_c3dc56e7e4bf44e3abb7d5b4e8509cd6
/tmp/pit/1/expt/df/__schema/__1676140033077_1676140033077_03ec4c4615164b1eb1c51ded25692d6b
/tmp/pit/1/expt/causes_bug/__meta/__1676140033076_1676140033076_4bc1f602956041c298e4a275eafd6b66
/tmp/pit/1/expt/__group/__1676140033080_1676140033080_8c65f4dd95534ed2b1704ffb60466312
/tmp/pit/1/expt/__group/__1676140033077_1676140033077_b16ef49e894a4b4e89b00eea48917272
/tmp/pit/1/__group/__1676140033074_1676140033074_debf8fb463184a668b81350fb77d5e52

# Test case 2, failure: The expt/df/__schema timestamp is NOT set to the specified write_timestamp
/tmp/pit/2/__meta/__100_100_cd544a461243469d9aafb9429cb3c5c5
/tmp/pit/2/expt/__meta/__100_100_fa4ea4daf65d4b8ca4174fe8672465d7
/tmp/pit/2/expt/df/__meta/__100_100_a21a3122a0a542edba8e75ad0f9ac8bf
/tmp/pit/2/expt/df/__schema/__1676140033088_1676140033088_2a20345e92c343c9ba9639293968e521
/tmp/pit/2/expt/causes_bug/__meta/__100_100_f65e84fa88ff4a7da060ba2183e87680
/tmp/pit/2/expt/__group/__100_100_77e752638a194b918bc8b95c053a7bd0
/tmp/pit/2/expt/__group/__100_100_ba9e76025300461a958ad39f8e199bcc
/tmp/pit/2/__group/__100_100_94d46c8958604aecb032c493dca07092
```

**Comment by mlin** [comment]
@atolopko-czi Looking into this...one quick clarification of "transient": does this mean that

1. the read initially fails, but the same read on the same object would succeed *after enough time has passed*?
2. less specifically it's "nondeterministic", just sometimes the test succeeds and other times it fails?

**Comment by mlin** [comment]
I've distilled @atolopko-czi's example using TileDB-Py only:

https://gist.github.com/mlin/233f3cef28027e20ced171843f3395da

Observations:

1. An additional necessary condition is that `causes_bug` and `df` are added to the group *in two separate write operations*, with the tiledb.Group handle reopened in between them. (Our `tiledbsoma.Collection._set_element` indeed reopens our tiledb.Group handle.)
2. The failure rate is 50%.

Findings (80% confidence):

This is probably a pathological case of of [TileDB ordering the two writes randomly](https://github.com/single-cell-data/TileDB-SOMA/blob/a9e3031c179e11e0f2af9abb95aa255ef6180365/apis/python/src/tiledbsoma/options/soma_tiledb_context.py#L55-L57) (=> 50% failure rate) when they share the same timestamp. Although we previously discussed that pitfall, we didn't appreciate that the two writes each adding *distinct* group elements still aren't commutative: the first write we do evidently says "the contents of the group are `causes_bug`", not "add `causes_bug` to the contents of the group."

Further supporting this, add `causes_bug2` to the collection, with a reopened tiledb.Group handle, after adding `causes_bug` and before adding `df`. Then the failure rate is 67%.

**Comment by mlin** [comment]
interest @thetorpedodog @nguyenv @Shelnutt2, this is looking gnarly

**Comment by atolopko-czi** [comment]
> one quick clarification of "transient": does this mean that
> 
> 1. the read initially fails, but the same read on the same object would succeed _after enough time has passed_?

Tested, and it appears a 2nd read attempt always succeeds.

> 2. less specifically it's "nondeterministic", just sometimes the test succeeds and other times it fails?

for the the first read, it's nondeterministic (and the second always succeeds).

**Comment by Shelnutt2** [comment]
>  Although we previously discussed that pitfall, we didn't appreciate that the two writes each adding distinct group elements still aren't commutative: the first write we do evidently says "the contents of the group are causes_bug", not "add causes_bug to the contents of the group."

The writes to groups need to be done in a batch at the end. I thought this was made explicitly clear during discussions around opening and closing. We must open for write once at the group level. We should not be opening and closing for each item, that violates the open/close principals. This is an implementation bug, and we should fix this ASAP.

**Comment by mlin** [comment]
Reopening the group write handle is itself a workaround for a [different sharp edge](https://github.com/single-cell-data/TileDB-SOMA/blob/fc9182a15572c0ec74bb657fcfffbd911fc8ab89/apis/python/src/tiledbsoma/collection.py#L440-L448) in the group API, needing two transactions to replace an existing key. To get away from it, we might need to disallow replacing an existing key in `SOMACollection` for now. That'd be fine by me (can relax at a future date), but any POV @thetorpedodog @johnkerl? ([historical version of the workaround](https://github.com/single-cell-data/TileDB-SOMA/blob/0892c69a3c11e8dc13651614fd9653993346b1ec/apis/python/src/tiledbsoma/collection.py#L303-L331) for reference -- rereading it, I'm not sure the new version covers all the cases that the old version did, particularly wrt timestamp sharing within the same millisecond) 

Even then however, we wouldn't be preventing the end user/developer from reopening the `SOMACollection` themselves between their writes, for whatever reason they might choose to do that -- for example, to delete and then replace an existing key if we've disallowed doing so in one step. Considering that we've tripped on this ourselves within 1 week, it seems likely to burn others eventually beyond our control!

To clarify @Shelnutt2, are we expecting that these `tiledb.Group` behaviors we're working around are permanent in the foreseeable, and defining any burns from them as user error? Or can we think more in terms of temporary workarounds? That'd be helpful to know for planning. Thx

**Comment by mlin** [comment]
@atolopko-czi It's very interesting that a second read succeeds after the first one fails; that's not predicted by my theory. Would you mind showing the exact code for that just so I can see details of are handles getting reopened etc.?

In addition to the write ordering, there is indeed caching in the collection implementation which may also be contributing.

**Comment by atolopko-czi** [comment]
> @atolopko-czi It's very interesting that a second read succeeds after the first one fails; that's not predicted by my theory. 

Revisited the test code and it was a false result. Failing reads fail consistently, and succeeding reads succeed on the first attempt always.

**Comment by thetorpedodog** [comment]
To summarize some discussion we've been having:

- Currently, the code flushes writes out on every collection operation. This is not needed or desired.
- Most common operations—accessing existing members, creating new not-yet-present members—are allowed. In these cases flushing should never be necessary.
- The cases that are forbidden—changing the URI of an existing member, deleting a newly-added member, and a few others—are fairly uncommon.

We can either minimize flushing by only doing so when performing an otherwise-forbidden operation (introducing potential consistency bugs) or simply raise an error.

We would probably want to implement something similar with metadata, since the semantics there are similar.

**Comment by mlin** [comment]
@thetorpedodog SGTM, good point about the metadata. Do you want to take a crack at this or shall I? (just to decide- I'm neutral)

Suggest also we pay attention to the likelihood that a user finds herself blocked from the replace operation, so reopens `SOMACollection` herself to do the 2-step update and generates this problem. We can simply define that as user error for now, but we should at least provide clear signage around the nondeterministic hazard area.

**Comment by thetorpedodog** [comment]
Since I'm thinking of using the same solution as in metadata and would have to update that anyways, I can take it.

**Comment by mlin** [comment]
@thetorpedodog one further thought-- 

> We can either minimize flushing by only doing so when performing an otherwise-forbidden operation (introducing potential consistency bugs) or simply raise an error.

We need to keep in mind that any series of multiple write+flush ops sharing the same timestamp will be applied in _literally random order_. Needless to say, that's difficult to reason about intuitively, what might & might not be commutative under such randomization. So IMO, we'd better strongly err on the side of **raising an error** when asked to go down that path!
