### ISSUE TITLE
[r] Have the `schema` accessor return Arrow schema not TileDB schema

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#937]
For compliance with the [spec](https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md).

Context: #839

**Comment by johnkerl** [comment]
Hi @eddelbuettel can you take a look at this one please?

**Comment by eddelbuettel** [comment]
Looks like a fragment is in place but croaking.

**Comment by johnkerl** [comment]
@eddelbuettel thanks! To clarify, can you please take this over from @aaronwolen ?

**Comment by eddelbuettel** [comment]
Yes I have.   One line addition _make it work_:

```sh
edd@rob:~/git/tiledb-soma/apis/r(de/sc-25640/arrow_schema)$ r -ltiledbsoma,tiledb -e'arr <- tiledb_array("~/git/tiledb-soma/test/soco/pbmc3k_processed/obs/"); as <- tiledbsoma:::arrow_schema_from_tiledb_schema(schema(arr)); print(as)'
Schema
soma_joinid: int64 not null
obs_id: string not null
n_genes: int64 not null
percent_mito: float not null
n_counts: float not null
louvain: string not null
is_b_cell: bool not null
edd@rob:~/git/tiledb-soma/apis/r(de/sc-25640/arrow_schema)$ 
```

Question now is where we 'wire this up'.  What does the spec say -- is this to be a property of each SOMA object i.e. should stick into SOMAArrayBase, say?

**Comment by eddelbuettel** [comment]
Yup, to confirm the idea is to replace / extend / enhance this function in TileDBArray:

```r
    #' @description Retrieve the array schema (lifecycle: experimental)
    #' @return A [`tiledb::tiledb_array_schema`] object
    schema = function() {
      tiledb::schema(self$object)
    },
```

**Comment by johnkerl** [comment]
@eddelbuettel I think `SOMAArrayBase` is indeed the right place as all three array types need an arrow-schema getter:

* https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md#somadataframe-1
* https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md#somadensendarray-1
* https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md#somasparsendarray-1

**Comment by eddelbuettel** [comment]
It already was in TileDBArray as my previous comment stated.  That works eg in SDF:

```sh
edd@rob:~/git/tiledb-soma/apis/r(de/sc-25640/arrow_schema)$ r -ltiledbsoma \ 
      -e'sdf <- SOMADataFrame$new("~/git/tiledb-soma/test/soco/pbmc3k_processed/obs/"); print(sdf$schema())'
Schema
soma_joinid: int64 not null
obs_id: string not null
n_genes: int64 not null
percent_mito: float not null
n_counts: float not null
louvain: string not null
is_b_cell: bool not null
edd@rob:~/git/tiledb-soma/apis/r(de/sc-25640/arrow_schema)$ 
```

**Comment by eddelbuettel** [comment]
The class inheritance per a sketch I have here is

```
## Class Inheritance

### Arrays and DataFrame to ArrayBase to Array to Object

SOMASparseNdArray:		SOMAArrayBase
SOMADenseNdArray:		SOMAArrayBase
SOMADataFrame:			SOMAArrayBase

SOMAArrayBase:			TileDBArray

TileDBArray:			TileDBObject

```

so it works already.  I'll commit as a change to the existing method.  If it should move to the other class we can revisit.  Ok?

**Comment by johnkerl** [comment]
Yeah sounds great! Doing this in a base class should make everything work as desired :)

**Comment by eddelbuettel** [comment]
I spoke too soon and may have to hand this back to @aaronwolen as the tests are now blowing.  The existing accessor seems to have been required making this a little trickier.

**Comment by eddelbuettel** [comment]
Ok -- so `schema()` is (currently, at least) expected to return a TileDB schema as it is used to be fed to `dimensions()` and `attrs()`.

So as a first pass the new function is now `arrow_schema()`.   We can consider renamed `schema()` to `tdb_schema()` or some other moniker, adjust all uses and tests, and then move `arrow_schema()` to back the then-vacated `schema()`.

**Comment by johnkerl** [comment]
@eddelbuettel that's a great plan as the spec asks for prefixless `schema` to return Arrow schema but meanwhile your iterative plan will more incremental & easier to check as you go along

**Comment by eddelbuettel** [comment]
So question to the floor:  what's the sanest id for a TileDB schema accessor?  `tiledb_schema`  ?

**Comment by johnkerl** [comment]
Works for me! :)

**Comment by eddelbuettel** [comment]
OO for the win.  Three lines changed.  Tests pass.   "Abstractions matter" as they say.  And they were right :grinning:
