### ISSUE TITLE
[python] Augment `DataFrame` unit tests once `SOMAReader` supports index types beyond int/string

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#956]
The current DataFrame unit tests are lacking in a couple of areas:
* tests that utilize more than one indexing column
* tests that cover the full gamut of types in an indexed column

Examples:
* indexing on a float-typed column
* indexing on both a string, float and int-typed column

etc.

**Comment by johnkerl** [comment]
* Tests that utilize more than one indexing column are here:
  * https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a11/apis/python/tests/test_dataframe.py#L369-L384
  * https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a11/apis/python/tests/test_dataframe.py#L678-L703
* These cover the full gamut of types currently supported by `SOMAReader` in an indexed column 
  * As tracked at #922 `SOMAReader` currently only handles int and string indices
  * https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a11/libtiledbsoma/src/pyapi/libtiledbsoma.cc#L328-L350
  * Indexing on float depends on 922
  * Indexing on a combination of string/int exists as linked above
  * Indexing on a combination of string/float/int depends on 922
 
cc @maniarathi I believe this is a non-blocker for the rc _unless_ we decide that we want `SOMAReader`'s current inability to index `DataFrame` on other than int/string to itself be a blocker for the rc. No more work can be done on this particular issue until that `SOMAReader` work is done.

**Comment by johnkerl** [comment]
Dup of #960, as every remaining ask on this PR is being implemented in issue #960 / PR #968
