### ISSUE TITLE
[python] Run sdist/bdist build GitHub workflow more frequently

### ISSUE THREAD

**Issue by mlin** [single-cell-data/TileDB-SOMA#965]
We only trigger our [python-packaging GH workflow](https://github.com/single-cell-data/TileDB-SOMA/blob/main/.github/workflows/python-packaging.yml) upon release (or manual) to save CI resources, since it takes awhile to build all the wheels on different platforms. However this can allow breaking changes to creep into `main` and we won't necessarily find out until going through the release process.

Ideas:
- build nightly
- auto trigger on some risk heuristic, e.g. diffs that modify `apis/python/setup.py`

interest @johnkerl @nguyenv

**Comment by johnkerl** [comment]
See also #693 and #697 for prior context

**Comment by johnkerl** [comment]
@mlin this is a great idea!! :) This idea was floated in #693 but I failed to keep it 'alive' in a still-open issue so thanks for keeping on top of this :)

**Comment by nguyenv** [comment]
Yes I think adding nightly builds is a great idea. We have this in several of our repos including TileDB core and TileDB-Py.
