### ISSUE TITLE
[Bug] [python] `nnz` raises `RuntimeError` when `allows_duplicates=True`

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#988]
**Describe the bug**

SOMAReader.nnz raises an error when the underlying array has `allow_duplicates=True`.  It should not do so.

Example:
```
In [10]: A = tiledb.open('file:///home/bruce/cell-census/tmp/census/2023-02-22/soma/census_data/homo_sapiens/obs')

In [11]: A.schema
Out[11]: 
ArraySchema(
  domain=Domain(*[
    Dim(name='soma_joinid', domain=(0, 9223372036854775806), tile=2048, dtype='int64', filters=FilterList([DoubleDeltaFilter(), ZstdFilter(level=19), ])),
  ]),
  attrs=[
    Attr(name='dataset_id', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='assay', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='assay_ontology_term_id', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='cell_type', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='cell_type_ontology_term_id', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='development_stage', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='development_stage_ontology_term_id', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='disease', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='disease_ontology_term_id', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='donor_id', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='is_primary_data', dtype='bool', var=False, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
    Attr(name='self_reported_ethnicity', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='self_reported_ethnicity_ontology_term_id', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='sex', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='sex_ontology_term_id', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='suspension_type', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='tissue', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='tissue_ontology_term_id', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='tissue_general', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
    Attr(name='tissue_general_ontology_term_id', dtype='<U0', var=True, nullable=False, filters=FilterList([DictionaryFilter(), ZstdFilter(level=19), ])),
  ],
  cell_order='row-major',
  tile_order='row-major',
  capacity=65536,
  sparse=True,
  allows_duplicates=True,
)

In [12]: A = soma.open('file:///home/bruce/cell-census/tmp/census/2023-02-22/soma/census_data/homo_sapiens/obs')

In [13]: A.count
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[13], line 1
----> 1 A.count

File ~/cell-census/venv/lib/python3.9/site-packages/tiledbsoma/_dataframe.py:137, in DataFrame.count(self)
    133 """
    134 Return the number of rows in the dataframe. Same as `len(df)`.
    135 """
    136 self._check_open_read()
--> 137 return cast(int, self._soma_reader().nnz())

RuntimeError: [SOMAReader] nnz not supported when duplicates are allowed
```

**Versions (please complete the following information):**
tiledbsoma.__version__    1.0rc0
tiledb.__version__        0.20.0
core version              2.14.0
python version            3.9.16.final.0

**Additional context**
Blocker for cell census

**Comment by johnkerl** [comment]
This happens at
https://github.com/single-cell-data/TileDB-SOMA/blame/1.0rc0/libtiledbsoma/src/soma_reader.cc#L277
-- it's only when we call `nnz_slow` and we do _that_ only when
https://github.com/single-cell-data/TileDB-SOMA/issues/930

The check there to prohibit `.nnz` when `allow_duplicates=True` is well-intentioned, but, I believe that we've arrived at a point of view wherein `allow_duplicates=True` is allowed/supported _only when the application has otherwise ensured uniqueness_. Which is the case for the CZI cell census.

So I think we need to just change that line from a throw to a log-warn saying something like "allow_duplicates=True and we are doing slow nnz which, caveat emptor, only works assuming there are no duplicate cells in the data"

I'll try that out.

**Comment by bkmartinjr** [comment]
> So I think we need to just change that line from a throw to a log-warn saying something like "allow_duplicates=True and we are doing slow nnz which, caveat emptor, only works assuming there are no duplicate cells in the data"

For our use case, I would prefer no logging, as there is no issue to concern users.

Possible ways to work around this:
* make it a LOG_DEBUG saying "computing nnz assuming no dups"
* add a param that says "don't warn the user" which just disables the logging or error, eg., `nnz(force: Optional[bool] = False) -> int`

**Comment by mlin** [comment]
The path where we use nnz_slow for any consolidated fragment is [relatively new](https://github.com/single-cell-data/TileDB-SOMA/pull/788/files#diff-f00fe93e3a84cedd18aaa8581c5133478d52f4576500a35eb4da1b65bdfb27ecR214-R218), added incidentally (?) when we were refactoring the optimized nnz to use the read timestamp (if any). I put the question mark there because I don't *think* that branch is directly related to timestamps per se. Maybe testing the timestamp support incidentally revealed should have been there in the first place?

If we have the "force" flag, then it might actually be appropriate to use the optimized nnz instead of nnz_slow. That's what we were doing before the recent change, and the possibility of duplicates is the newly commented reason for using nnz_slow for consolidated fragments. Emphasize I'm really fuzzy on this fragment stuff though, so take this only as a suggestion that needs further vetting...

This info also highly relevant to #930

**Comment by johnkerl** [comment]
@bkmartinjr I thought about `nnz(force)` but on reflection, we've established the pattern (championed by you!) that `allow_duplicates=True` puts the burden on the application to guarantee uniqueness and I think proceed-with-caveats honors that spirit.

As an additional complication, `SOMAReader.nnz()` (the method) is exposed within TileDB-SOMA's Python API as `@property` which supports no args -- in particular,  no place to put the `force` flag. So we could put the `force` flag _in between_ the user-level `@property` and the C++-level `SOMAReader.nnz()` but given the previous paragraph I feel like this is not necessary.

**Comment by johnkerl** [comment]
@mlin here's how consolidation relates to timestamps:

Suppose there is a write at `t=10` and another at `t=20`.

Without consolidate:
* There are two fragments:
  * One with `tiledb.fragment.FragmentInfoList[i].timestamp_range = (10, 10)`
  * One with `tiledb.fragment.FragmentInfoList[i].timestamp_range = (20, 20)`
With consolidate:
* There is one fragment:
  * One with `tiledb.fragment.FragmentInfoList[i].timestamp_range = (10, 20)`

**Comment by bkmartinjr** [comment]
@johnkerl - I agree that `force` is a bad idea.  Upon further reflection, it doesn't even solve the issue I am focused on.

I am still concerned the current code is slightly wrong - I'll respond with some more thoughts after a bit of research

**Comment by johnkerl** [comment]
@bkmartinjr we are on the same page regarding `allows_dup=True`:

> Put another way: where a creator has set allows_dups=True, AND written duplicate rows, it is OK to produce somewhat undefined behavior, and we don't need to protect against it.

The only way we were differing is I was leaning slightly in favor of debug-logging _something_ while not doing the protect-against-that bit; and your point is well taken that even the debug-logging bit isn't necessary.

So we are fully on the same page.

**Comment by bkmartinjr** [comment]
I agree that debug logging is _not_ necessary (and not desired). Rationale:
* the situation where the logging is helpful require a condition known to be "out of scope".  The situation where logging _most commonly_ will occur, i.e., the census app writes data not containing dups, is a red herring - it is warning about something that is _not_ a problem and misdirects the user.
* consistency: you are logging in one operation, but not providing the same level of protection in others (e.g., read).

So I'm strongly in favor of no logging, and just returning the "rows including dups" consistently.

**Comment by johnkerl** [comment]
@bkmartinjr thanks for the re-confirm; we're already fully on the same page and #989 is updated accordingly.
